import type { LeadView } from '../../types/leads';
import type { AssignmentView } from '../../types/leads';

export function assignmentToLeadView(a: AssignmentView): LeadView {
  return {
    lead_id: a.lead_id,
    org_id: a.org_id,
    org_name: a.branch,
    first_name: '',
    middle_name: null,
    last_name: '',
    full_name: a.lead_full_name ?? '',
    phone: a.lead_phone,
    email: a.lead_email,
    address_line1: null,
    city: null,
    city_name: null,
    state_name: null,
    country_name: null,
    stage: a.lead_stage ?? '',
    stage_label: a.lead_stage_label ?? a.lead_stage ?? '',
    source: null,
    followup_required: false,
    is_rejected: false,
    is_terminated: a.is_terminated,
    outcome: a.lead_stage_outcome,
    outcome_label: a.lead_stage_outcome_label,
    outcome_comment: null,
    stage_id: '',
    outcome_id: null,
    scheduled_at: null,
    is_followup_overdue: false,
    campaign_name: null,
    platform: null,
    assigned_rep_name: a.assigned_rep_name,
    assigned_rep_email: a.assigned_rep_email,
    tags: [],
    metadata: {},
    created_at: new Date(a.lead_created_at),
    updated_at: new Date(a.assigned_at),
    is_deleted: false,
    assigned_user_id: a.assigned_to,
    campaign_id: null,
  };
}
