// Brand presets, fonts and modes a tenant / user may choose. Pure data — safe
// for client, server and (mirrored as Zod enums) the identity-service schema.
//
// The preset list is the design system's ("Precision Enterprise Kinetic",
// Stitch Tenant Branding screen, 2026-10-02). `indigo-kinetic` is the
// platform default and the only preset whose LIGHT scheme is the hand-tuned
// Stitch palette in theme.css verbatim; every other preset, any custom seed,
// and every dark scheme is generated by buildScheme().

export const THEME_PRESETS = [
  { id: 'indigo-kinetic', label: 'Indigo Kinetic', seed: '#4f46e5' },
  { id: 'pacific-ocean', label: 'Pacific Ocean', seed: '#2563eb' },
  { id: 'teal-horizon', label: 'Teal Horizon', seed: '#0d9488' },
  { id: 'sky-velocity', label: 'Sky Velocity', seed: '#0284c7' },
  { id: 'emerald-fit', label: 'Emerald Fit', seed: '#059669' },
  { id: 'royal-violet', label: 'Royal Violet', seed: '#7c3aed' },
  { id: 'electric-amber', label: 'Electric Amber', seed: '#ea580c' },
  { id: 'slate-modern', label: 'Slate Modern', seed: '#0f172a' },
] as const;

export type ThemePresetId = (typeof THEME_PRESETS)[number]['id'];
export const DEFAULT_PRESET_ID: ThemePresetId = 'indigo-kinetic';

export const BRAND_FONTS = [
  { id: 'inter', label: 'Inter', cssVar: '--font-inter' },
  { id: 'manrope', label: 'Manrope', cssVar: '--font-manrope' },
  { id: 'dm-sans', label: 'DM Sans', cssVar: '--font-dm-sans' },
  { id: 'ibm-plex-sans', label: 'IBM Plex Sans', cssVar: '--font-ibm-plex-sans' },
  { id: 'plus-jakarta-sans', label: 'Plus Jakarta Sans', cssVar: '--font-plus-jakarta-sans' },
  { id: 'public-sans', label: 'Public Sans', cssVar: '--font-public-sans' },
  { id: 'outfit', label: 'Outfit', cssVar: '--font-outfit' },
] as const;

export type BrandFontId = (typeof BRAND_FONTS)[number]['id'];
export const DEFAULT_FONT_ID: BrandFontId = 'inter';

/** 'system' = follow the device's prefers-color-scheme. */
export const THEME_MODES = ['light', 'dark', 'system'] as const;
export type ThemeMode = (typeof THEME_MODES)[number];

/**
 * Text size steps. `pct` is the <html> font-size as a percentage of the
 * browser default, so every rem-based size (type tokens, spacing, grids)
 * scales together and a browser-level font preference still applies.
 * Personal only: a tenant never sets it and the theme lock does not cover it.
 */
export const FONT_SIZES = [
  { id: 'sm', label: 'Small', pct: 87.5 },
  { id: 'md', label: 'Default', pct: 100 },
  { id: 'lg', label: 'Large', pct: 112.5 },
  { id: 'xl', label: 'Extra large', pct: 125 },
] as const;

export type FontSizeId = (typeof FONT_SIZES)[number]['id'];
export const DEFAULT_FONT_SIZE_ID: FontSizeId = 'md';

/**
 * A theme choice as stored (tenant branding or a user's override). Exactly one
 * of preset / seed_hex drives the colours; seed_hex wins when both are set.
 * snake_case: this shape crosses the API.
 */
export interface ThemeChoice {
  preset?: ThemePresetId | null;
  seed_hex?: string | null;
  font?: BrandFontId | null;
  mode?: ThemeMode | null;
  font_size?: FontSizeId | null;
}

/** Fully-resolved theme a layout renders with — no nulls. */
export interface EffectiveTheme {
  preset: ThemePresetId | null;
  seed_hex: string;
  font: BrandFontId;
  mode: ThemeMode;
  font_size: FontSizeId;
}

export const DEFAULT_THEME: EffectiveTheme = {
  preset: DEFAULT_PRESET_ID,
  seed_hex: '#4f46e5',
  font: DEFAULT_FONT_ID,
  mode: 'light',
  font_size: DEFAULT_FONT_SIZE_ID,
};

export const HEX_COLOR_RE = /^#[0-9a-fA-F]{6}$/;

export function presetById(id: string | null | undefined) {
  return THEME_PRESETS.find((p) => p.id === id) ?? null;
}

export function fontById(id: string | null | undefined) {
  return BRAND_FONTS.find((f) => f.id === id) ?? null;
}

export function fontSizeById(id: string | null | undefined) {
  return FONT_SIZES.find((f) => f.id === id) ?? FONT_SIZES.find((f) => f.id === DEFAULT_FONT_SIZE_ID)!;
}

/**
 * Merge layers (lowest priority first) into one EffectiveTheme. Unknown ids /
 * malformed hex are ignored rather than trusted — the API validates on write,
 * this guards the read side against stale rows.
 */
export function resolveTheme(...layers: Array<ThemeChoice | null | undefined>): EffectiveTheme {
  const out: EffectiveTheme = { ...DEFAULT_THEME };
  for (const layer of layers) {
    if (!layer) continue;
    if (layer.seed_hex && HEX_COLOR_RE.test(layer.seed_hex)) {
      out.seed_hex = layer.seed_hex.toLowerCase();
      out.preset = null;
    } else if (layer.preset) {
      const p = presetById(layer.preset);
      if (p) {
        out.preset = p.id;
        out.seed_hex = p.seed;
      }
    }
    if (layer.font && fontById(layer.font)) out.font = layer.font;
    if (layer.mode && (THEME_MODES as readonly string[]).includes(layer.mode)) out.mode = layer.mode;
    if (layer.font_size && FONT_SIZES.some((s) => s.id === layer.font_size)) out.font_size = layer.font_size;
  }
  return out;
}
