-- ===================================================================
-- 00_extensions_schemas_roles.sql
--
-- Extensions, schemas and database roles.
-- Must run first: everything else needs the schemas and every GRANT needs a grantee.
-- btree_gist is required here by hr.reporting_lines' EXCLUDE constraint in 03_.
--
-- Generated by the db_scripts consolidation. Fresh-install only:
-- there is no in-place upgrade path, no ALTER-after-the-fact section,
-- and no _migrations/ folder. Schema changes are made in the
-- CREATE statement itself and the database is rebuilt.
-- ===================================================================

BEGIN;

-- ── Extensions ─────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_bytes() used by public.gen_uuidv7()
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS btree_gin;

DO $$
BEGIN
  EXECUTE 'CREATE EXTENSION IF NOT EXISTS "vector"';
EXCEPTION WHEN OTHERS THEN
  RAISE WARNING 'pgvector not available (%). AI embedding features disabled.', SQLERRM;
END;
$$;

-- ── Schemas ────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS geo;
CREATE SCHEMA IF NOT EXISTS entity;
CREATE SCHEMA IF NOT EXISTS iam;
CREATE SCHEMA IF NOT EXISTS lms;
CREATE SCHEMA IF NOT EXISTS marketing;
CREATE SCHEMA IF NOT EXISTS audit;
CREATE SCHEMA IF NOT EXISTS ext;
-- Cross-product messaging config (WhatsApp/email templates). Shared tier, like
-- entity/iam/audit — communication-service is a cross-product relay, so its
-- catalog must be readable by every product login. It deliberately does NOT
-- live in lms/hr/task: 04_roles_and_grants.sql revokes each product schema from
-- the other products' logins, which would wall the catalog off from them.
CREATE SCHEMA IF NOT EXISTS comms;

-- ── Roles (idempotent) ─────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user NOLOGIN NOINHERIT;
  ELSE
    ALTER ROLE app_user NOLOGIN NOINHERIT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tenant_admin') THEN
    CREATE ROLE tenant_admin NOLOGIN NOINHERIT;
  ELSE
    ALTER ROLE tenant_admin NOLOGIN NOINHERIT;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'root_service') THEN
    CREATE ROLE root_service WITH LOGIN PASSWORD 'CrmSvc_Dev2025' BYPASSRLS;
  ELSE
    ALTER ROLE root_service WITH LOGIN PASSWORD 'CrmSvc_Dev2025' BYPASSRLS;
  END IF;
END $$;

-- readonly_user — defense-in-depth role for read_only actors (product rank 0).
-- withRoleTx selects this role (instead of app_user) and marks the transaction
-- read-only for such actors, so the DB physically rejects every write even if an
-- app-layer authorization check is missed. It is created WITH INHERIT and made a
-- member of app_user so that pg_has_role(readonly_user,'app_user','USAGE') is
-- TRUE — every `TO app_user` RLS SELECT policy then applies unchanged, giving
-- read_only sessions identical read visibility while the read-only transaction
-- blocks all writes. No direct write GRANTs are given to it.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'readonly_user') THEN
    CREATE ROLE readonly_user NOLOGIN INHERIT;
  ELSE
    ALTER ROLE readonly_user NOLOGIN INHERIT;
  END IF;
  -- Inherit app_user's grants + RLS-policy applicability (read visibility).
  GRANT app_user TO readonly_user;
END $$;

DO $$ BEGIN EXECUTE format('GRANT CONNECT ON DATABASE %I TO root_service', current_database()); END; $$;

-- ===================================================================
-- SERVICE LOGIN ROLES  (per-microservice credentials)
-- Each service connects with its own login role, then does:
--   SET LOCAL ROLE app_user;          -- activates RLS + grants
--   SET LOCAL app.current_org_id = '...';
--   SET LOCAL app.current_user_id = '...';
-- ===================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lead_svc') THEN
    CREATE ROLE lead_svc WITH LOGIN PASSWORD 'LeadSvc_Dev2025' NOINHERIT;
  ELSE ALTER ROLE lead_svc WITH LOGIN PASSWORD 'LeadSvc_Dev2025' NOINHERIT; END IF;
END; $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'campaign_svc') THEN
    CREATE ROLE campaign_svc WITH LOGIN PASSWORD 'replace_in_env' NOINHERIT;
  ELSE ALTER ROLE campaign_svc WITH LOGIN NOINHERIT; END IF;
END; $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'user_mgmt_svc') THEN
    CREATE ROLE user_mgmt_svc WITH LOGIN PASSWORD 'replace_in_env' NOINHERIT;
  ELSE ALTER ROLE user_mgmt_svc WITH LOGIN NOINHERIT; END IF;
END; $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'notif_svc') THEN
    CREATE ROLE notif_svc WITH LOGIN PASSWORD 'replace_in_env' NOINHERIT;
  ELSE ALTER ROLE notif_svc WITH LOGIN NOINHERIT; END IF;
END; $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'intake_svc') THEN
    CREATE ROLE intake_svc WITH LOGIN PASSWORD 'replace_in_env' NOINHERIT;
  ELSE ALTER ROLE intake_svc WITH LOGIN NOINHERIT; END IF;
END; $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tenant_dash_svc') THEN
    CREATE ROLE tenant_dash_svc WITH LOGIN PASSWORD 'TenantSvc_Dev2025' NOINHERIT;
  ELSE ALTER ROLE tenant_dash_svc WITH LOGIN PASSWORD 'TenantSvc_Dev2025' NOINHERIT; END IF;
END; $$;

-- analytics_svc: BYPASSRLS + SELECT only (read replica)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'analytics_svc') THEN
    CREATE ROLE analytics_svc WITH LOGIN PASSWORD 'replace_in_env' BYPASSRLS NOINHERIT;
  ELSE ALTER ROLE analytics_svc WITH LOGIN BYPASSRLS NOINHERIT; END IF;
END; $$;

DO $$
DECLARE v_db TEXT := current_database();
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO lead_svc',        v_db);
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO campaign_svc',    v_db);
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO user_mgmt_svc',   v_db);
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO notif_svc',       v_db);
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO intake_svc',      v_db);
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO tenant_dash_svc', v_db);
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO analytics_svc',   v_db);
END; $$;

-- ── meta_svc login role ───────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'meta_svc') THEN
    CREATE ROLE meta_svc WITH LOGIN PASSWORD 'MetaSvc_Dev2025' NOINHERIT;
  ELSE ALTER ROLE meta_svc WITH LOGIN PASSWORD 'MetaSvc_Dev2025' NOINHERIT; END IF;
END; $$;
DO $$
DECLARE v_db TEXT := current_database();
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO meta_svc', v_db);
END; $$;-- ===================================================================
-- 03_product_schema.sql
-- Consolidated DDL (3/6): the FULL hr + task product schema union --
--   * hr/task foundation (entity.tenant_modules, HR lookups,
--     hr.departments/designations, hr.employee_profiles)  [once]
--   * leave management (+ leave_ledger idempotency)
--   * attendance (geofencing / shifts / regularizations)
--   * reporting lines
--   * the complete task.* model (task_lists, tasks, task_status_log,
--     task_comments, views)
-- The lookup tables tenant-scoped by the historical 22_tenant-scope-lookups.sql
-- carry tenant_id + their org/tenant SELECT policies directly in their CREATE
-- TABLE here: hr.leave_types / hr.employment_types / hr.attendance_statuses /
-- task.task_statuses / task.task_priorities (lms.roles / hr.roles / task.roles
-- live in 04_roles_and_grants.sql).
-- entity.organizations.geo_lat/geo_lng (historically an ALTER in
-- 13_init-attendance.sql) now lives in 02_schema.sql.
-- Idempotent: safe to re-run.
-- ===================================================================

-- ===================================================================
-- CRM Monorepo — HR + Task Platform Foundation (Phase 0, DB layer only)
-- Adds: hr + task schemas, hr_svc/task_svc login roles,
--       entity.tenant_modules (module entitlements),
--       HR global lookups, org-scoped hr.departments / hr.designations,
--       hr.employee_profiles (IAM↔HR bridge, incl. dormant face-verify cols).
-- Prerequisite: 01_init-db.sql + 01_init-lookup-data.sql already applied.
-- Idempotent: safe to re-run (IF NOT EXISTS / ON CONFLICT DO NOTHING /
--             guarded DO blocks / DROP+CREATE for triggers & policies).
-- Style, guard patterns and ordering mirror db_scripts/01_init-db.sql.
-- No existing table, trigger or policy is modified.
-- ===================================================================


-- ── Schemas ────────────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS hr;
CREATE SCHEMA IF NOT EXISTS task;   -- no tables yet — populated in a later increment


-- ===================================================================
-- NEW SERVICE LOGIN ROLES  (per-microservice credentials, via app_user)
-- Mirrors the lead_svc / meta_svc setup in 01_init-db.sql: each service
-- connects with its own login role, then does SET LOCAL ROLE app_user +
-- session GUCs so RLS + app_user grants apply.
-- ===================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'hr_svc') THEN
    CREATE ROLE hr_svc WITH LOGIN PASSWORD 'HrSvc_Dev2025' NOINHERIT;
  ELSE ALTER ROLE hr_svc WITH LOGIN PASSWORD 'HrSvc_Dev2025' NOINHERIT; END IF;
END; $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'task_svc') THEN
    CREATE ROLE task_svc WITH LOGIN PASSWORD 'TaskSvc_Dev2025' NOINHERIT;
  ELSE ALTER ROLE task_svc WITH LOGIN PASSWORD 'TaskSvc_Dev2025' NOINHERIT; END IF;
END; $$;

DO $$
DECLARE v_db TEXT := current_database();
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO hr_svc',   v_db);
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO task_svc', v_db);
END; $$;


-- ===================================================================
-- CRM Monorepo — Leave Management (Phase 1, DB layer)
-- Adds the complete hr.* leave-management model:
--   holiday_calendars / holidays, leave_policies, hr_settings,
--   leave_ledger (append-only), leave_requests (+ status log),
--   leave_request_approvals, hr.can_approve_leave(), and the
--   dashboard views (vw_leave_balances / vw_leave_requests_enriched /
--   vw_team_leave_calendar).
-- Prerequisite: 01_init-db.sql + 01_init-lookup-data.sql + 10_init-hr-task-schemas.sql
--               (hr schema, hr_svc role, HR lookups, employee_profiles).
-- Idempotent: safe to re-run (IF NOT EXISTS / ON CONFLICT DO NOTHING /
--             guarded DO blocks / DROP+CREATE for triggers & policies).
-- Style, guard patterns, trigger recipe and RLS mirror db_scripts/01 and 10.
-- Operational tables use the marketing.ad_campaigns recipe; append-only logs
-- (leave_ledger, leave_request_status_log) mirror lms.lead_status_log.
-- No existing table, trigger or policy is modified except the note below:
--   hr.leave_ledger.leave_request_id FK depends on hr.leave_requests, so
--   leave_requests DDL is emitted before leave_ledger.
-- ===================================================================


-- ── Extensions ─────────────────────────────────────────────────────
-- btree_gist lets an exclusion constraint mix equality (user_id) with a
-- range overlap (daterange) — used for the no-overlapping-leave guard.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ===================================================================
-- 1. lms_svc — new product login for the LMS product (leads-service,
-- meta-conversion-api). Mirrors the lead_svc/hr_svc/task_svc creation
-- pattern. lead_svc itself is left alone (still used, unrestricted, by
-- identity-service/notifications-service/admin-service/meta legacy path
-- until those are re-plumbed) — lms_svc is the new, scoped login that
-- leads-service and meta-conversion-api switch to.
-- ===================================================================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'lms_svc') THEN
    CREATE ROLE lms_svc WITH LOGIN PASSWORD 'LmsSvc_Dev2025' NOINHERIT;
  ELSE ALTER ROLE lms_svc WITH LOGIN PASSWORD 'LmsSvc_Dev2025' NOINHERIT; END IF;
END; $$;

DO $$
DECLARE v_db TEXT := current_database();
BEGIN
  EXECUTE format('GRANT CONNECT ON DATABASE %I TO lms_svc', v_db);
END; $$;

COMMIT;
