-- ===================================================================
-- 01_functions_shared.sql
--
-- Shared trigger/utility functions.
-- Split out ahead of the tables because nearly every CREATE TABLE has
-- DEFAULT public.gen_uuidv7() — a column default is early-bound, so the
-- function must already exist when the table is created.
--
-- Generated by the db_scripts consolidation. Fresh-install only:
-- there is no in-place upgrade path, no ALTER-after-the-fact section,
-- and no _migrations/ folder. Schema changes are made in the
-- CREATE statement itself and the database is rebuilt.
-- ===================================================================

BEGIN;

-- ── UUIDv7 generator (RFC 9562 §5.7) ──────────────────────────────
-- Time-ordered UUIDs: 48-bit ms timestamp prefix eliminates the
-- random-insert B-tree fragmentation caused by public.gen_uuidv7() (v4).
-- Works on PostgreSQL 14+ with no extensions required.
CREATE OR REPLACE FUNCTION public.gen_uuidv7() RETURNS UUID
LANGUAGE plpgsql AS $$
DECLARE
  v_millis BIGINT;
  v_bytes  BYTEA;
  v_hex    TEXT;
BEGIN
  v_millis := (EXTRACT(EPOCH FROM CLOCK_TIMESTAMP()) * 1000)::BIGINT;
  v_bytes  := gen_random_bytes(10);
  v_hex :=
    -- 48-bit unix_ts_ms: high 32 bits (8 hex) + low 16 bits (4 hex)
    lpad(to_hex(v_millis >> 16), 8, '0') ||
    lpad(to_hex(v_millis & 65535), 4, '0') ||
    -- version nibble (7) + 12-bit rand_a
    '7' ||
    lpad(to_hex(((get_byte(v_bytes, 0) & 15) << 8) | get_byte(v_bytes, 1)), 3, '0') ||
    -- variant bits (10xxxxxx) + rand_b
    lpad(to_hex((get_byte(v_bytes, 2) & 63) | 128), 2, '0') ||
    lpad(to_hex(get_byte(v_bytes, 3)), 2, '0') ||
    encode(substring(v_bytes from 5 for 6), 'hex');
  RETURN (
    substring(v_hex, 1, 8)  || '-' ||
    substring(v_hex, 9, 4)  || '-' ||
    substring(v_hex, 13, 4) || '-' ||
    substring(v_hex, 17, 4) || '-' ||
    substring(v_hex, 21, 12)
  )::UUID;
END; $$;

-- ===================================================================
-- CORE TABLES
-- ===================================================================

-- ── Utility functions (needed before table triggers) ──────────────

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at := CLOCK_TIMESTAMP(); RETURN NEW; END; $$;

-- Converts a physical DELETE into a soft delete (UPDATE is_deleted=TRUE).
-- root_service bypasses this and performs a real delete (GDPR/purge).
-- Also clears is_active (where the table has that column) so tables with a
-- chk_*_active_deleted CHECK (NOT (is_active AND is_deleted)) constraint
-- (entity.tenants, entity.organizations, iam.users) don't fail the soft
-- delete on a row that was still active.
CREATE OR REPLACE FUNCTION public.soft_delete_row()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_user_id UUID;
  v_has_is_active BOOLEAN;
BEGIN
  IF current_user = 'root_service' THEN RETURN OLD; END IF;
  BEGIN
    v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_user_id := NULL; END;

  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = TG_TABLE_SCHEMA
      AND table_name   = TG_TABLE_NAME
      AND column_name  = 'is_active'
  ) INTO v_has_is_active;

  IF v_has_is_active THEN
    EXECUTE format(
      'UPDATE %I.%I SET is_active = FALSE, is_deleted = TRUE, deleted_at = CLOCK_TIMESTAMP(), deleted_by = $1 WHERE id = $2',
      TG_TABLE_SCHEMA, TG_TABLE_NAME
    ) USING v_user_id, OLD.id;
  ELSE
    EXECUTE format(
      'UPDATE %I.%I SET is_deleted = TRUE, deleted_at = CLOCK_TIMESTAMP(), deleted_by = $1 WHERE id = $2',
      TG_TABLE_SCHEMA, TG_TABLE_NAME
    ) USING v_user_id, OLD.id;
  END IF;
  RETURN NULL;
END; $$;

-- Auto-populates created_by from app.current_user_id on INSERT.
CREATE OR REPLACE FUNCTION public.set_created_by()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_user_id UUID;
BEGIN
  IF NEW.created_by IS NULL THEN
    BEGIN
      v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
    EXCEPTION WHEN OTHERS THEN v_user_id := NULL; END;
    NEW.created_by := v_user_id;
  END IF;
  RETURN NEW;
END; $$;

-- Auto-populate org_id from session GUC when not provided explicitly.
CREATE OR REPLACE FUNCTION public.set_org_id()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_org TEXT;
BEGIN
  IF NEW.org_id IS NULL THEN
    v_org := current_setting('app.current_org_id', true);
    IF v_org IS NULL OR v_org = '' THEN
      RAISE EXCEPTION 'org_id is NULL and app.current_org_id GUC is not set';
    END IF;
    NEW.org_id := v_org::uuid;
  END IF;
  RETURN NEW;
END; $$;

-- ===================================================================
-- SHARED TRIGGER FUNCTION — derive member_roles.tenant_id from org_id
-- tenant_id is denormalized onto member_roles so the tenant_admin RLS
-- policy needs no join. This trigger sets it authoritatively from the
-- org's real tenant on every INSERT/UPDATE, so an app_user cannot write
-- a spoofed tenant_id to escape isolation.
-- ===================================================================
CREATE OR REPLACE FUNCTION public.set_member_role_tenant_id()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  SELECT tenant_id INTO NEW.tenant_id
  FROM entity.organizations
  WHERE id = NEW.org_id;
  IF NEW.tenant_id IS NULL THEN
    RAISE EXCEPTION 'org_id % does not resolve to a tenant', NEW.org_id;
  END IF;
  RETURN NEW;
END; $$;

COMMIT;
