-- ===================================================================
-- 02_tables_core.sql
--
-- Core tables: geo, entity, iam, lms, marketing, audit, ext, comms.
-- FK targets for the product tables in 03_.
--
-- Generated by the db_scripts consolidation. Fresh-install only:
-- there is no in-place upgrade path, no ALTER-after-the-fact section,
-- and no _migrations/ folder. Schema changes are made in the
-- CREATE statement itself and the database is rebuilt.
-- ===================================================================

BEGIN;

-- ===================================================================
-- 01_extensions_and_roles.sql
-- Consolidated DDL (1/6): schema-version tracking, Postgres extensions,
-- schema-namespace declarations, the gen_uuidv7() generator, and the
-- platform-wide DB login roles (app_user / tenant_admin / root_service).
-- Idempotent: safe to re-run.
-- ===================================================================

--rollback
--drop database crm (force)
--create database crm_v2
-- ===================================================================
-- CRM Monorepo — Merged Production Schema
-- Combines: monorepo UUID-based design + EXISTING_WORKING_CODE features
-- UUID PKs for all operational/lookup tables
-- SMALLINT/INTEGER PKs for geographic tables (geo.countries/states/cities)
-- Idempotent: safe to re-run (IF NOT EXISTS, ON CONFLICT DO NOTHING)
-- ===================================================================


-- ── Schema version tracking ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.schema_versions (
  version     TEXT        PRIMARY KEY,
  description TEXT,
  applied_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);-- ===================================================================
-- 02_schema.sql
-- Consolidated DDL (2/6): geo + operational lookup tables, core entity/iam
-- tables (tenants, organizations, users), lms/marketing tables, iam
-- api_clients, audit tables, and the ext.* (Meta integration) tables.
-- Every column a table ever ends up with (per db_scripts history) is present
-- here directly -- no later ALTER TABLE ADD COLUMN.
-- Idempotent: safe to re-run.
-- ===================================================================

-- ===================================================================
-- GEOGRAPHIC LOOKUP TABLES — see below, after entity.tenants.
--
-- geo.* used to live here, at the very top of the file, because it was
-- global reference data with no dependencies. It is now tenant-scoped and
-- carries a tenant_id FK, so it has to be created AFTER entity.tenants.
-- ===================================================================


-- ===================================================================
-- OPERATIONAL LOOKUP TABLES  (UUID PKs)
-- ===================================================================

-- NOTE (Tier C): iam.user_roles is defined further down, right after
-- iam.departments — it now carries tenant_id + department_id FKs, which require
-- entity.tenants / entity.organizations / iam.departments to exist first.

CREATE TABLE IF NOT EXISTS entity.org_types (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  name        TEXT    NOT NULL UNIQUE,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS entity.tenant_domains (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  name        TEXT    NOT NULL UNIQUE,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS entity.tenant_plan_types (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  name        TEXT    NOT NULL UNIQUE,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

-- ── TENANTS ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS entity.tenants (
  id           UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  name         TEXT    NOT NULL UNIQUE,
  domain_id    UUID    REFERENCES entity.tenant_domains(id),
  plan_type_id UUID    REFERENCES entity.tenant_plan_types(id),
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at   TIMESTAMPTZ,
  deleted_by   UUID,
  metadata     JSONB   NOT NULL DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_tenants_active_deleted CHECK (NOT (is_active AND is_deleted))
);

-- ===================================================================
-- GEOGRAPHIC LOOKUP TABLES  (UUID PKs, tenant-scoped)
--
-- Tenants operate in different countries, states and cities, and each one
-- curates its own list — so geo is a tenant catalog like lms.lead_stage,
-- not global reference data. It follows the same template pattern:
--   tenant_id IS NULL     = platform template row, seeded by
--                           reference_data/01_geo.sql. RLS (08_rls.sql)
--                           hides these from every application role;
--                           entity.seed_tenant_geo() clones them into a
--                           tenant at provisioning time.
--   tenant_id IS NOT NULL = a row the tenant owns and can edit.
--
-- PKs are UUID v7 (public.gen_uuidv7()), matching every other table in the
-- model. The old SMALLINT/INTEGER identity keys could not survive rows
-- being authored independently per tenant.
--
-- Deletes are soft (is_active = FALSE): entity.organizations and
-- lms.marketing_leads reference these rows ON DELETE RESTRICT, so a place
-- that has ever been used must stay resolvable.
--
-- The UNIQUE (tenant_id, id) keys exist so the child FKs can be composite.
-- Without them a tenant's city could hang off another tenant's state; RLS
-- does not prevent that, only a composite FK does. Name uniqueness lives in
-- 06_indexes.sql as partial index pairs (NULLs are distinct in a unique
-- index, so one constraint cannot cover both templates and tenant rows).
-- ===================================================================

CREATE TABLE IF NOT EXISTS geo.countries (
  id          UUID     PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID     REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT     NOT NULL,
  iso_code    CHAR(2)  NOT NULL,
  description TEXT,
  is_active   BOOLEAN  NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_countries_tenant_id UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS geo.states (
  id          UUID     PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID     REFERENCES entity.tenants(id) ON DELETE CASCADE,
  country_id  UUID     NOT NULL,
  name        TEXT     NOT NULL,
  code        TEXT,
  description TEXT,
  is_active   BOOLEAN  NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_states_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT fk_states_country
    FOREIGN KEY (tenant_id, country_id) REFERENCES geo.countries (tenant_id, id)
    ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS geo.cities (
  id          UUID     PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID     REFERENCES entity.tenants(id) ON DELETE CASCADE,
  state_id    UUID     NOT NULL,
  name        TEXT     NOT NULL,
  description TEXT,
  is_active   BOOLEAN  NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_cities_tenant_id UNIQUE (tenant_id, id),
  CONSTRAINT fk_cities_state
    FOREIGN KEY (tenant_id, state_id) REFERENCES geo.states (tenant_id, id)
    ON DELETE RESTRICT
);

-- ===================================================================
-- TENANT-SCOPED LMS / MARKETING LOOKUP TABLES
-- Created here (rather than up in the OPERATIONAL LOOKUP TABLES block)
-- because each carries a tenant_id FK to entity.tenants, which must exist
-- first. Every table that FKs into these (marketing.ad_campaigns,
-- lms.marketing_leads, lms.lead_follow_ups, lms.lead_interactions, ...) is
-- created further down, so this placement introduces no forward reference.
-- ===================================================================

-- lms.lead_stage / lead_stage_outcome / interaction_types / follow_up_statuses
-- / lead_sources / marketing.marketing_platforms / campaign_statuses are
-- tenant-scoped (historically added via 26_tenant-scope-lms-lookups.sql
-- ALTER; folded directly into the CREATE TABLE here). tenant_id is left
-- NULLABLE (not NOT NULL, unlike the original post-migration end state):
-- 07_seed_lookup_data.sql (untouched per scope — seed data, not schema)
-- still seeds these 7 tables as global rows with no tenant_id, and there is
-- no per-tenant catalog-provisioning path wired up for them (unlike the 8
-- tables covered by 05_catalogs.sql / entity.seed_tenant_defaults()) — a
-- pre-existing gap, not something introduced by this consolidation. See
-- KNOWN FOLLOW-UP note in the original 26_tenant-scope-lms-lookups.sql.
CREATE TABLE IF NOT EXISTS lms.lead_stage (
  id                UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id         UUID    REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name              TEXT    NOT NULL,
  label             TEXT    NOT NULL,
  description       TEXT,
  sort_order        INT     NOT NULL DEFAULT 0,
  followup_required BOOLEAN NOT NULL DEFAULT FALSE,
  is_rejected       BOOLEAN NOT NULL DEFAULT FALSE,
  is_terminated     BOOLEAN NOT NULL DEFAULT FALSE,
  is_active         BOOLEAN NOT NULL DEFAULT TRUE,
  -- Per-tenant uniqueness: each tenant owns its own copy of this
  -- catalog, so the machine key is only unique within a tenant.
  CONSTRAINT uq_lead_stage_tenant_name UNIQUE (tenant_id, name),
  -- Lets ext.lead_stage_capi_event_map take a composite (tenant_id, stage_id)
  -- FK, so a tenant's CAPI mapping cannot hang off another tenant's stage.
  CONSTRAINT uq_lead_stage_tenant_id UNIQUE (tenant_id, id)
);

CREATE TABLE IF NOT EXISTS lms.lead_stage_outcome (
  id               UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id        UUID    REFERENCES entity.tenants(id) ON DELETE CASCADE,
  stage_id         UUID    NOT NULL REFERENCES lms.lead_stage(id) ON DELETE RESTRICT,
  name             TEXT    NOT NULL,
  label            TEXT    NOT NULL,
  description      TEXT,
  requires_comment BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order       INT     NOT NULL DEFAULT 0,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_lead_stage_outcome_stage_name UNIQUE (stage_id, name)
);


CREATE TABLE IF NOT EXISTS lms.interaction_types (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  -- Per-tenant uniqueness: each tenant owns its own copy of this
  -- catalog, so the machine key is only unique within a tenant.
  CONSTRAINT uq_interaction_types_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS lms.follow_up_statuses (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  -- Per-tenant uniqueness: each tenant owns its own copy of this
  -- catalog, so the machine key is only unique within a tenant.
  CONSTRAINT uq_follow_up_statuses_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS marketing.marketing_platforms (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  -- Per-tenant, not global. This was UNIQUE (name) while the table was
  -- already tenant-scoped and RLS'd, which made it impossible to clone the
  -- templates into a tenant -- the second tenant's copy collided with the
  -- first. That is why entity.seed_tenant_lms_catalogs() never provisioned
  -- these two and every tenant saw an empty dropdown.
  CONSTRAINT uq_marketing_platforms_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS marketing.campaign_statuses (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  -- Per-tenant, not global. This was UNIQUE (name) while the table was
  -- already tenant-scoped and RLS'd, which made it impossible to clone the
  -- templates into a tenant -- the second tenant's copy collided with the
  -- first. That is why entity.seed_tenant_lms_catalogs() never provisioned
  -- these two and every tenant saw an empty dropdown.
  CONSTRAINT uq_campaign_statuses_tenant_name UNIQUE (tenant_id, name)
);

-- Monorepo addition: source channel for organic / non-campaign leads
CREATE TABLE IF NOT EXISTS lms.lead_sources (
  id        UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id UUID    REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name      TEXT    NOT NULL,
  label     TEXT    NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  -- Per-tenant uniqueness: each tenant owns its own copy of this
  -- catalog, so the machine key is only unique within a tenant.
  CONSTRAINT uq_lead_sources_tenant_name UNIQUE (tenant_id, name)
);

-- ── ORGANIZATIONS ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS entity.organizations (
  id            UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id     UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE RESTRICT,
  name               TEXT    NOT NULL,
  legal_entity_name  TEXT,
  brand_name         TEXT,
  org_type_id        UUID    REFERENCES entity.org_types(id),
  address_line1 TEXT,
  address_line2 TEXT,
  landmark      TEXT,
  pincode       TEXT,
  -- free-text city (monorepo); structured FK city below for enriched queries
  city          TEXT,
  -- geo.* is tenant-scoped, so these are COMPOSITE FKs on (tenant_id, x_id).
  -- An org can only point at a place its own tenant owns — enforced here at
  -- write time, not left to the RLS on geo.
  city_id       UUID,
  state_id      UUID,
  country_id    UUID,
  timezone      TEXT    NOT NULL DEFAULT 'Asia/Kolkata',
  -- Geofence-centre coordinates used by the HR attendance module
  -- (historically added via 13_init-attendance.sql ALTER TABLE ... ADD COLUMN
  -- IF NOT EXISTS; folded directly into the CREATE TABLE here).
  geo_lat       NUMERIC(9,6),
  geo_lng       NUMERIC(9,6),
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at    TIMESTAMPTZ,
  deleted_by    UUID,
  metadata      JSONB   NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT uq_organizations_tenant_name  UNIQUE (tenant_id, name),
  CONSTRAINT chk_organizations_active_deleted CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT fk_organizations_city
    FOREIGN KEY (tenant_id, city_id)    REFERENCES geo.cities    (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_organizations_state
    FOREIGN KEY (tenant_id, state_id)   REFERENCES geo.states    (tenant_id, id) ON DELETE RESTRICT,
  CONSTRAINT fk_organizations_country
    FOREIGN KEY (tenant_id, country_id) REFERENCES geo.countries (tenant_id, id) ON DELETE RESTRICT
);

-- ── DEPARTMENTS (IAM, tenant-scoped — Tier C) ─────────────────────
-- Departments live in IAM (moved out of hr.departments) so a role in ANY product
-- can belong to a department. tenant_id scopes them per tenant; org_id NULL = a
-- tenant-wide department shared by all the tenant's branches, org_id set = a
-- branch-specific department.
CREATE TABLE IF NOT EXISTS iam.departments (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id)       ON DELETE CASCADE,
  org_id      UUID             REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at  TIMESTAMPTZ,
  deleted_by  UUID,
  created_by  UUID,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_iam_departments_active_deleted CHECK (NOT (is_active AND is_deleted))
);

-- ── ROLE CATALOG (tenant-scoped — Tier C) ─────────────────────────
-- Relocated from the lookup section: it now references iam.departments and
-- entity.tenants. tenant_id NULL = a GLOBAL ANCHOR role shared by every tenant
-- (read_only 0 / org_admin 980 / tenant_admin 990 / super_admin 1000 — the fixed
-- ranks in @platform/rbac); tenant_id set = a tenant-specific role tied to a
-- department, with a dynamic rank in the 1..979 band.
CREATE TABLE IF NOT EXISTS iam.user_roles (
  id            UUID     PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id     UUID              REFERENCES entity.tenants(id)  ON DELETE CASCADE,
  department_id UUID              REFERENCES iam.departments(id) ON DELETE RESTRICT,
  name          TEXT     NOT NULL,
  label         TEXT     NOT NULL,
  description   TEXT,
  rank          INT      NOT NULL DEFAULT 0
                         CONSTRAINT chk_user_roles_rank CHECK (rank >= 0 AND rank <= 1000),
  is_active     BOOLEAN  NOT NULL DEFAULT TRUE
);

-- ── CAPABILITY CATALOG (Tier C3) ──────────────────────────────────
-- The set of things a role may be allowed to do. Rows are the SAME stable string
-- keys declared in @platform/rbac's CAPABILITY map — code references the key, the
-- DB decides who holds it. `area` groups keys for the admin UI and matches
-- @platform/rbac's AREA (lms | hr | tasks | admin).
--
-- The CATALOG is global (platform-shipped): a tenant cannot invent a capability,
-- because nothing in code would honour it. What a tenant CAN change is the grant
-- — see iam.role_capabilities below.
CREATE TABLE IF NOT EXISTS iam.capabilities (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  key         TEXT    NOT NULL UNIQUE,
  -- Where this node sits in the access tree:
  --   tool -> page -> tab -> operation -> scope
  kind        TEXT    NOT NULL CHECK (kind IN ('tool','page','tab','operation','scope')),
  parent_key  TEXT             REFERENCES iam.capabilities(key) ON DELETE CASCADE,
  label       TEXT    NOT NULL,
  description TEXT,
  -- Display order among siblings. For kind='scope' this is ALSO the breadth
  -- ordering: effective scope is the granted sibling with the highest value.
  sort_order  INT     NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  -- Only a tool may be a root; everything else must hang off a parent.
  CONSTRAINT chk_iam_capabilities_root CHECK ((kind = 'tool') = (parent_key IS NULL))
);

-- ── ROLE → CAPABILITY GRANTS (tenant-scoped — Tier C3) ────────────
-- tenant_id NULL = the PLATFORM DEFAULT grant, shipped in the seed and shared by
-- every tenant. tenant_id set = that tenant's OVERRIDE of the same (role,
-- capability) pair, which wins. is_granted FALSE is therefore meaningful: it is
-- how a tenant revokes a default without deleting the platform row.
--
-- Resolution order (see iam.fn_role_capability_matrix): tenant override →
-- platform default → deny. Default-deny is the point: an unlisted pair is not
-- accessible, so adding a capability key to code without seeding grants fails
-- closed rather than open.
CREATE TABLE IF NOT EXISTS iam.role_capabilities (
  id            UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id     UUID             REFERENCES entity.tenants(id) ON DELETE CASCADE,
  role_id       UUID    NOT NULL REFERENCES iam.user_roles(id) ON DELETE CASCADE,
  capability_id UUID    NOT NULL REFERENCES iam.capabilities(id) ON DELETE CASCADE,
  is_granted    BOOLEAN NOT NULL DEFAULT TRUE,
  created_by    UUID,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── USERS ─────────────────────────────────────────────────────────
-- full_name is GENERATED ALWAYS AS STORED — never insert it directly.
CREATE TABLE IF NOT EXISTS iam.users (
  id                    UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id                UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  first_name            TEXT    NOT NULL,
  middle_name           TEXT,
  last_name             TEXT    NOT NULL DEFAULT '',
  full_name             TEXT    GENERATED ALWAYS AS (
                          TRIM(first_name
                            || COALESCE(' ' || NULLIF(middle_name, ''), '')
                            || COALESCE(' ' || NULLIF(last_name,   ''), ''))
                        ) STORED,
  email                 TEXT    NOT NULL UNIQUE,
  mobile                TEXT,
  password_hash         TEXT    NOT NULL,
  role_id               UUID    NOT NULL REFERENCES iam.user_roles(id) ON DELETE RESTRICT,
  -- self-referential adjacency list; NULL = top of hierarchy
  manager_id            UUID    REFERENCES iam.users(id) ON DELETE SET NULL,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at            TIMESTAMPTZ,
  deleted_by            UUID,
  created_by            UUID,
  force_password_change BOOLEAN NOT NULL DEFAULT TRUE,
  password_changed_at   TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  last_login_at         TIMESTAMPTZ,
  -- Account-level brute-force throttle. The gateway's IP rate limiter cannot
  -- stop an attacker who rotates source IPs against one known email; these
  -- move the counter onto the account itself. Reset on successful login or
  -- password change. See _migrations/17_account_lockout.sql.
  failed_login_attempts INT     NOT NULL DEFAULT 0,
  locked_until          TIMESTAMPTZ,
  -- Lets a stale attempt count expire instead of accumulating forever.
  -- See _migrations/18_account_lockout_decay.sql.
  last_failed_login_at  TIMESTAMPTZ,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  -- The single, coarse cross-product role that survives in the shrunk JWT.
  -- Nullable (backfilled by the roles/grants backfill step, made NOT NULL in
  -- the Phase E contract). Drives PG-role selection and platform-wide
  -- capabilities only; product authority comes from <product>.member_roles.
  platform_role         TEXT
                        CONSTRAINT chk_users_platform_role
                        CHECK (platform_role IN ('super_admin','tenant_admin','org_admin','member')),
  -- ── Profile photo / avatar (platform-wide; also the biometric reference for
  --    HR face-attendance once enrolled). Bytes live in blob storage; only the
  --    opaque key + metadata are kept here. photo_key IS NULL ⇒ no photo.
  --    photo_consent_at records the user's DPDP attestation captured at upload.
  --    See _migrations/20_user_photos_and_attendance_retention.sql.
  photo_key             TEXT,
  photo_content_type    TEXT,
  photo_uploaded_at     TIMESTAMPTZ,
  photo_uploaded_by     UUID,
  photo_consent_at      TIMESTAMPTZ,
  CONSTRAINT chk_user_not_own_manager    CHECK (id <> manager_id),
  CONSTRAINT chk_users_active_deleted    CHECK (NOT (is_active AND is_deleted))
);

-- ── iam.user_org_mapping ─────────────────────────────────────────
-- Source of truth for which orgs a user can access and at what role.
-- Replaces the single org_id + role_id on iam.users for access control.
--
-- iam.users.org_id  remains as the user's PRIMARY / home org (FK integrity
--               and fallback when no org is selected).
-- iam.users.role_id remains as the user's DEFAULT role (mirrors the home
--               org row here; kept for backward-compat during transition).
CREATE TABLE IF NOT EXISTS iam.user_org_mapping (
  user_id    UUID        NOT NULL REFERENCES iam.users(id)         ON DELETE CASCADE,
  org_id     UUID        NOT NULL REFERENCES entity.organizations(id)  ON DELETE CASCADE,
  role_id    UUID        NOT NULL REFERENCES iam.user_roles(id)     ON DELETE RESTRICT,
  is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
  -- % share of new leads this user should auto-receive within this org.
  -- Sums to 100 (or all-zero = auto-assignment disabled) across an org's
  -- mapped rows; enforced at the application layer, not by a DB constraint.
  lead_assignment_weight SMALLINT NOT NULL DEFAULT 0 CHECK (lead_assignment_weight BETWEEN 0 AND 100),
  granted_by UUID        REFERENCES iam.users(id)                   ON DELETE SET NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  PRIMARY KEY (user_id, org_id)
);

-- ── iam.reporting_lines ───────────────────────────────────────────
-- THE reporting hierarchy for the whole platform. One row = "user_id reports to
-- manager_id, in org_id, for [effective_from, effective_to)". effective_to NULL
-- = the currently-open line. At most one active line per user per org at any
-- instant (exclusion constraint). A NULL manager_id is not stored — absence of a
-- line means "no reporting line", and the leave approver resolver falls back to
-- a deterministic org_admin/hr_admin.
--
-- Lives in iam, not hr: 07_grants.sql REVOKEs schema hr from lms_svc/task_svc,
-- so a tree owned by a product schema is unreadable by the other products. LMS
-- lead assignment, HR leave/attendance approval and Tasks team scope all resolve
-- authority from this one table, via iam.fn_is_in_subtree (04_) and the
-- iam.vw_user_team_members / vw_user_org_chart views (05_).
--
-- Effective-dated on purpose: every authority question is answerable "as of" any
-- date, so a re-org does not rewrite history and past decisions stay auditable.
-- Acting is checked as of today; historical reads pass the record's own date.
--
-- Cross-org managers are expressed through iam.user_org_mapping and nothing
-- else: iam.check_reporting_line_membership() (04_) requires BOTH parties to
-- hold an active mapping in org_id, so a manager shared across branches has one
-- mapping and one line per branch, and no chain ever crosses an org boundary.
-- iam.users.manager_id is a trigger-maintained display mirror of this table,
-- never an authority source, and is scheduled for removal.
CREATE TABLE IF NOT EXISTS iam.reporting_lines (
  id             UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id      UUID    NOT NULL REFERENCES entity.tenants(id)        ON DELETE CASCADE,
  org_id         UUID    NOT NULL REFERENCES entity.organizations(id)  ON DELETE CASCADE,
  user_id        UUID    NOT NULL REFERENCES iam.users(id)             ON DELETE CASCADE,
  manager_id     UUID    NOT NULL REFERENCES iam.users(id)             ON DELETE RESTRICT,
  effective_from DATE    NOT NULL DEFAULT CURRENT_DATE,
  effective_to   DATE,
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted     BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at     TIMESTAMPTZ,
  deleted_by     UUID,
  created_by     UUID,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_reporting_lines_active_deleted CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT chk_reporting_lines_not_self       CHECK (user_id <> manager_id),
  CONSTRAINT chk_reporting_lines_range          CHECK (effective_to IS NULL OR effective_to > effective_from),
  -- No two overlapping active lines for the same user in the same org. The
  -- half-open daterange [from, to) lets a new line start on the exact day the
  -- previous one ends without tripping the constraint. Soft-deleted rows are
  -- excluded so a re-org can supersede history. (btree_gist, created in 00_,
  -- is what allows mixing the equality columns with the range overlap.)
  CONSTRAINT excl_reporting_lines_overlap EXCLUDE USING gist (
    org_id  WITH =,
    user_id WITH =,
    daterange(effective_from, effective_to, '[)') WITH &&
  ) WHERE (NOT is_deleted)
);

-- ── AD_CAMPAIGNS ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS marketing.ad_campaigns (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id      UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  name        TEXT    NOT NULL,
  platform_id UUID    NOT NULL REFERENCES marketing.marketing_platforms(id) ON DELETE RESTRICT,
  status_id   UUID    NOT NULL REFERENCES marketing.campaign_statuses(id)   ON DELETE RESTRICT,
  budget      NUMERIC(12,2),
  started_at  TIMESTAMPTZ,
  ended_at    TIMESTAMPTZ,
  is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at  TIMESTAMPTZ,
  deleted_by  UUID,
  created_by  UUID,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  -- Links a Meta lead's campaign_id (bigint, raw on ext.meta_leads) to a real
  -- lms.marketing_leads.campaign_id FK, so the "Campaign" field on the lead
  -- edit screen (sourced from marketing_leads_vw -> marketing.ad_campaigns)
  -- is populated for Meta-sourced leads instead of always showing "-".
  meta_campaign_id BIGINT,
  CONSTRAINT chk_campaign_dates
    CHECK (ended_at IS NULL OR started_at IS NULL OR started_at < ended_at)
);

-- ── MARKETING_LEADS ───────────────────────────────────────────────
-- full_name is GENERATED ALWAYS AS STORED.
-- city TEXT = free-text (monorepo); city_id/state_id/country_id = structured FK (EXISTING).
-- is_active: false when the record has been superseded or transferred out.
-- superseded_by: old row → newer active row (same-org re-submission or walk-in dedup).
--   All cross-org transfers and merge audit trail live in lms.lead_links.
-- embedding column stub: uncomment after pgvector confirmed.
CREATE TABLE IF NOT EXISTS lms.marketing_leads (
  id               UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id           UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  first_name       TEXT    NOT NULL,
  middle_name      TEXT,
  last_name        TEXT    NOT NULL DEFAULT '',
  full_name        TEXT    GENERATED ALWAYS AS (
                     TRIM(first_name
                       || COALESCE(' ' || NULLIF(middle_name, ''), '')
                       || COALESCE(' ' || NULLIF(last_name,   ''), ''))
                   ) STORED,
  phone            TEXT,
  email            TEXT,
  -- address fields
  address_line1    TEXT,
  address_line2    TEXT,
  landmark         TEXT,
  pincode          TEXT,
  -- free-text city (backwards-compatible); structured FKs below
  city             TEXT,
  -- geo.* is tenant-scoped, but a lead carries only org_id — its tenant is
  -- reached through entity.organizations — so these cannot be composite FKs
  -- the way entity.organizations' are. Same-tenant-ness is enforced by
  -- public.check_lead_geo_tenant() in 04_functions_triggers.sql, and every
  -- read joins geo on tenant_id as well as id.
  city_id          UUID REFERENCES geo.cities(id)    ON DELETE RESTRICT,
  state_id         UUID REFERENCES geo.states(id)    ON DELETE RESTRICT,
  country_id       UUID REFERENCES geo.countries(id) ON DELETE RESTRICT,
  -- CRM state
  stage_id         UUID    REFERENCES lms.lead_stage(id)         ON DELETE RESTRICT,
  outcome_id       UUID    REFERENCES lms.lead_stage_outcome(id)  ON DELETE RESTRICT,
  outcome_comment  TEXT,
  -- current/next follow-up due time; source of truth for "is this lead overdue".
  -- Kept in sync by the app on every follow-up create/reschedule/complete; NULL = no open follow-up.
  scheduled_at     TIMESTAMPTZ,
  -- source tracking
  campaign_id      UUID    REFERENCES marketing.ad_campaigns(id) ON DELETE SET NULL,
  source_id        UUID    REFERENCES lms.lead_sources(id),
  -- assignment
  assigned_user_id UUID    REFERENCES iam.users(id) ON DELETE SET NULL,
  -- lead linking: dedup chain + transfer supersession
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  superseded_by    UUID    REFERENCES lms.marketing_leads(id) ON DELETE SET NULL,
  -- raw/enrichment data
  raw_webhook_data JSONB   NOT NULL DEFAULT '{}',
  metadata         JSONB   NOT NULL DEFAULT '{}',
  tags             TEXT[]  NOT NULL DEFAULT '{}',
  -- embedding vector(1536), -- uncomment after pgvector confirmed
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at       TIMESTAMPTZ,
  deleted_by       UUID,
  created_by       UUID,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

COMMENT ON COLUMN lms.marketing_leads.is_active IS
  'FALSE when this record has been superseded by a newer submission or transferred out. Filter WHERE is_active = TRUE for the live lead pipeline.';
COMMENT ON COLUMN lms.marketing_leads.superseded_by IS
  'Points forward to the newer active lead that replaced this one (same org). Set on both re-submission duplicates and walk-in dedup. Cross-org transfers are tracked in lms.lead_links.';

-- ── LEAD_LINKS ────────────────────────────────────────────────────
-- Audit trail for all lead-to-lead relationships:
--   link_type = 'merge'    → same-org dedup (re-submission or walk-in), source_org_id = dest_org_id
--   link_type = 'transfer' → executive cross-org transfer,             source_org_id ≠ dest_org_id
-- dest_lead_id is nullable: set after the destination lead row is created.
CREATE TABLE IF NOT EXISTS lms.lead_links (
  id              UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  -- source (the record being retired / transferred out)
  source_lead_id  UUID        NOT NULL REFERENCES lms.marketing_leads(id) ON DELETE RESTRICT,
  source_org_id   UUID        NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  -- destination (the active record going forward)
  dest_lead_id    UUID        REFERENCES lms.marketing_leads(id) ON DELETE SET NULL,
  dest_org_id     UUID        NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  -- discriminator
  link_type       TEXT        NOT NULL CHECK (link_type IN ('merge', 'transfer')),
  -- who & why
  created_by      UUID        REFERENCES iam.users(id) ON DELETE SET NULL,
  reason          TEXT,
  notes           TEXT,
  -- lifecycle of the link action itself
  status          TEXT        NOT NULL DEFAULT 'completed' CHECK (status IN ('pending', 'completed', 'rejected')),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── ORG_API_KEYS (removed) ─────────────────────────────────────────
-- Legacy per-org API key table for the website lead-intake form. Confirmed no
-- external traffic; superseded by iam.api_clients / POST /public/v1/leads.
-- Dropped outright — no consumers to preserve compatibility for.
DROP TABLE IF EXISTS lms.org_api_keys CASCADE;

-- ── IAM.API_CLIENTS ────────────────────────────────────────────────
-- Scoped credentials for the public/partner API (/public/v1/*). Each key is
-- tenant-bound and optionally bound to one or more branches (see
-- iam.api_client_orgs below); carries explicit scopes. Only the HMAC hash of
-- the raw key is stored — never the plaintext. Lives in iam (not ext) because
-- it's a platform/gateway auth primitive, not LMS/Meta-integration data (N-4) —
-- identity-service owns its CRUD and, post-D8 grants, only iam is guaranteed
-- reachable from a shared service.
CREATE TABLE IF NOT EXISTS iam.api_clients (
  id                 UUID         NOT NULL DEFAULT gen_uuidv7() PRIMARY KEY,
  tenant_id          UUID         NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name               VARCHAR(120) NOT NULL,
  key_prefix         TEXT         NOT NULL,          -- display-only, e.g. "crmk_live_Ab12Cd"
  key_hash           TEXT         NOT NULL UNIQUE,   -- HMAC-SHA256(pepper, raw key); never plaintext
  scopes             TEXT[]       NOT NULL DEFAULT '{}',
  rate_limit_per_min INTEGER      NOT NULL DEFAULT 60,
  scope_all_orgs     BOOLEAN      NOT NULL DEFAULT FALSE, -- TRUE = tenant-wide (all branches, incl. future ones)
  is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
  expires_at         TIMESTAMPTZ,
  last_used_at       TIMESTAMPTZ,
  revoked_at         TIMESTAMPTZ,
  created_by         UUID         REFERENCES iam.users(id) ON DELETE SET NULL,
  created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ── IAM.API_CLIENT_ORGS ────────────────────────────────────────────
-- Junction table: which branches an iam.api_clients row is scoped to. Zero
-- rows for a client means tenant-wide (only valid when scope_all_orgs = TRUE).
-- Created here (ahead of iam.api_clients' own RLS policies below) because
-- the org_isolation_policy on iam.api_clients references this table.
CREATE TABLE IF NOT EXISTS iam.api_client_orgs (
  api_client_id UUID NOT NULL REFERENCES iam.api_clients(id)      ON DELETE CASCADE,
  org_id        UUID NOT NULL REFERENCES entity.organizations(id) ON DELETE CASCADE,
  CONSTRAINT pk_api_client_orgs PRIMARY KEY (api_client_id, org_id)
);

-- ── LEAD_REPORT_SNAPSHOT ────────────────────────────────────────────
-- Daily history for the lead report (email + public page), which the live
-- views (lms.vw_lead_report_branch/_user, 05_views.sql) cannot provide on
-- their own since they only ever compute NOW(). Written once per tenant per
-- day by the send-lead-report cron job.
--
-- One row per (branch, assignee, source) bucket, same shape as
-- vw_lead_report_user plus the lead's source, PLUS one synthetic all-zero row
-- per (branch, source) combination that had no leads that day (assigned_user_id
-- NULL, is_unassigned TRUE) — the write path guarantees this so a quiet
-- branch/source still appears in history, matching the live per-source
-- branch grid's "zero row, not a missing row" guarantee.
--
-- source_id NULL = the "Unknown" bucket (no source recorded on the lead),
-- same convention as the live getTenantSourceReport queries in
-- analytics.repository.ts. The PLAIN (non-source) branch/assignee compare
-- (getSnapshotForDate) sums across every source_id for a given
-- (org_id, assigned_user_id) to recover the combined-across-sources total —
-- see that function's header comment.
--
-- Deliberately ONE table, not a branch table plus a user table: branch-,
-- source- and tenant-level rollups are all derived at read time via
-- `SUM(...) GROUP BY GROUPING SETS (...)`, the same technique
-- tenantBranchReportQuery uses over live data — a stored total could never
-- disagree with the rows it was summed from, and the row counts here
-- (branches x staff x sources, per tenant per day) are far too small for the
-- extra aggregation to matter.
CREATE TABLE IF NOT EXISTS lms.lead_report_snapshot (
  tenant_id          UUID        NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  org_id             UUID        NOT NULL REFERENCES entity.organizations(id) ON DELETE CASCADE,
  org_name           TEXT        NOT NULL,
  -- NULL = the Unassigned bucket for this branch/source, or the zero-lead placeholder.
  assigned_user_id   UUID        REFERENCES iam.users(id) ON DELETE SET NULL,
  assignee           TEXT        NOT NULL,
  is_unassigned      BOOLEAN     NOT NULL DEFAULT FALSE,
  -- NULL = "Unknown" (no source_id on the lead). Never dropped on the
  -- referenced lead_sources row's deletion — a historical snapshot must keep
  -- its own label even if the tenant later renames/deactivates the source.
  source_id          UUID        REFERENCES lms.lead_sources(id) ON DELETE SET NULL,
  source_label       TEXT        NOT NULL DEFAULT 'Unknown',
  -- Branch-local calendar date, same semantics as report_date in the views.
  report_date        DATE        NOT NULL,
  total_leads        INT         NOT NULL,
  new_count          INT         NOT NULL,
  new_leads_today    INT         NOT NULL,
  unassigned_count   INT         NOT NULL,
  followup_scheduled INT         NOT NULL,
  followup_overdue   INT         NOT NULL,
  converted_count    INT         NOT NULL,
  unqualified_count  INT         NOT NULL,
  captured_at        TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT uq_lead_report_snapshot UNIQUE NULLS NOT DISTINCT (tenant_id, org_id, assigned_user_id, source_id, report_date)
);

-- ── LEAD_INTERACTIONS ─────────────────────────────────────────────
-- Append-only log — no updated_at, no update trigger.
CREATE TABLE IF NOT EXISTS lms.lead_interactions (
  id                  UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id              UUID    NOT NULL REFERENCES entity.organizations(id)   ON DELETE RESTRICT,
  lead_id             UUID    NOT NULL REFERENCES lms.marketing_leads(id) ON DELETE CASCADE,
  user_id             UUID    NOT NULL REFERENCES iam.users(id)           ON DELETE RESTRICT,
  interaction_type_id UUID    REFERENCES lms.interaction_types(id)        ON DELETE RESTRICT,
  notes               TEXT,
  duration_seconds    INT,
  occurred_at         TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at          TIMESTAMPTZ,
  deleted_by          UUID,
  created_by          UUID,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── LEAD_FOLLOW_UPS ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lms.lead_follow_ups (
  id               UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id           UUID    NOT NULL REFERENCES entity.organizations(id)   ON DELETE RESTRICT,
  lead_id          UUID    NOT NULL REFERENCES lms.marketing_leads(id) ON DELETE CASCADE,
  assigned_user_id UUID    NOT NULL REFERENCES iam.users(id)           ON DELETE RESTRICT,
  status_id        UUID    NOT NULL REFERENCES lms.follow_up_statuses(id) ON DELETE RESTRICT,
  -- Snapshot of the lead's stage/outcome at the moment this entry was appended (history context).
  stage_id         UUID    REFERENCES lms.lead_stage(id)         ON DELETE RESTRICT,
  outcome_id       UUID    REFERENCES lms.lead_stage_outcome(id) ON DELETE RESTRICT,
  scheduled_at     TIMESTAMPTZ NOT NULL,
  completed_at     TIMESTAMPTZ,
  notes            TEXT,
  is_deleted       BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at       TIMESTAMPTZ,
  deleted_by       UUID,
  created_by       UUID,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── LEAD_ASSIGNMENT_LOG ───────────────────────────────────────────
-- Populated automatically by trigger on lms.marketing_leads.
CREATE TABLE IF NOT EXISTS lms.lead_assignment_log (
  id                   UUID PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id               UUID NOT NULL REFERENCES entity.organizations(id)   ON DELETE RESTRICT,
  lead_id              UUID NOT NULL REFERENCES lms.marketing_leads(id) ON DELETE CASCADE,
  assigned_by_id       UUID REFERENCES iam.users(id) ON DELETE SET NULL,
  assigned_to_id       UUID REFERENCES iam.users(id) ON DELETE SET NULL,
  previous_assignee_id UUID REFERENCES iam.users(id) ON DELETE SET NULL,
  action               TEXT NOT NULL DEFAULT 'reassigned'
                       CONSTRAINT chk_assignment_action CHECK (
                         action IN ('initial','reassigned','unassigned','self_assigned','bulk_assigned')
                       ),
  note                 TEXT,
  assigned_at          TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── ACTIVITIES ────────────────────────────────────────────────────
-- Fire-and-forget log written by audit.activities-service.
CREATE TABLE IF NOT EXISTS audit.activities (
  id           UUID PRIMARY KEY DEFAULT public.gen_uuidv7(),
  action_type  TEXT NOT NULL,
  performed_by UUID REFERENCES iam.users(id),
  target_id    UUID,
  target_type  TEXT,
  org_id       UUID REFERENCES entity.organizations(id),
  meta         JSONB,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── LEAD_STATUS_LOG ───────────────────────────────────────────────
-- Immutable stage-transition log. Written by trigger only.
CREATE TABLE IF NOT EXISTS lms.lead_status_log (
  id               UUID PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id           UUID NOT NULL REFERENCES entity.organizations(id)   ON DELETE RESTRICT,
  lead_id          UUID NOT NULL REFERENCES lms.marketing_leads(id) ON DELETE CASCADE,
  changed_by_id    UUID REFERENCES iam.users(id)            ON DELETE SET NULL,
  old_stage_id     UUID REFERENCES lms.lead_stage(id)       ON DELETE RESTRICT,
  new_stage_id     UUID NOT NULL REFERENCES lms.lead_stage(id) ON DELETE RESTRICT,
  old_outcome_id   UUID REFERENCES lms.lead_stage_outcome(id) ON DELETE RESTRICT,
  new_outcome_id   UUID REFERENCES lms.lead_stage_outcome(id) ON DELETE RESTRICT,
  assigned_user_id UUID REFERENCES iam.users(id)            ON DELETE SET NULL,
  transition_note  TEXT,
  changed_at       TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── MARKETING_LEADS_HISTORY ───────────────────────────────────────
-- Dedicated audit table for lms.marketing_leads field changes.
-- UPDATE: diff-style {"field": {"old": v, "new": v}}
-- DELETE: full to_jsonb(OLD) snapshot
CREATE TABLE IF NOT EXISTS audit.marketing_leads_history (
  id                 UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  lead_id            UUID    NOT NULL REFERENCES lms.marketing_leads(id) ON DELETE RESTRICT,
  changed_by_user_id UUID    REFERENCES iam.users(id) ON DELETE SET NULL,
  operation          CHAR(1) NOT NULL CHECK (operation IN ('I','U','D')),
  changed_fields     JSONB,
  changed_at         TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ── AUDIT_LOG ─────────────────────────────────────────────────────
-- Generic audit for all operational tables except lms.marketing_leads
-- (which has its own history table above).
-- Columns cover both the monorepo convention and EXISTING_WORKING_CODE convention.
CREATE TABLE IF NOT EXISTS audit.audit_log (
  id             UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  table_name     TEXT        NOT NULL,
  operation      CHAR(1)     NOT NULL CHECK (operation IN ('U', 'D')),
  -- EXISTING_WORKING_CODE naming
  record_id      UUID,
  changed_by     UUID,
  changed_fields JSONB,
  -- row_id/actor_id (monorepo-naming aliases of record_id/changed_by) were
  -- dropped by the historical "remove duplicate alias columns" cleanup
  -- (issue #32) — never created here.
  old_data       JSONB,
  new_data       JSONB,
  -- common
  org_id         UUID,
  changed_at     TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);

-- ===================================================================
-- COMMS -- CROSS-PRODUCT MESSAGE TEMPLATES
-- ===================================================================
-- The catalog of outbound message templates every product picks from:
-- LMS messaging a lead, HR welcoming a new joiner, Tasks nudging an overdue
-- item, and whatever ships next. communication-service is a stateless
-- cross-product relay, so its catalog lives in the shared tier next to
-- entity/iam/audit rather than inside any one product schema. Putting it in
-- lms would wall it off outright: 04_roles_and_grants.sql revokes USAGE on
-- lms/marketing/ext from hr_svc and task_svc.
--
-- Resolution is (module, channel, name) narrowed by audience, most specific
-- wins: an org row beats a tenant row beats a global row. That lets one branch
-- override the wording of a template without forking it for everyone.
--
-- The two channels are genuinely different shapes, which is why the columns
-- are channel-conditional rather than one-size-fits-all:
--
--   whatsapp  Meta forbids business-initiated free text outside the 24h reply
--             window, so the body lives in the APPROVED TEMPLATE at Meta and we
--             only send ordered placeholder values. provider_template_name is
--             the handle; subject/body_template are meaningless and must be NULL.
--   email     No external approval, so the copy lives HERE in subject +
--             body_template and we interpolate it ourselves.
--
-- header_fields/body_fields are ORDERED placeholder tokens. The table stores
-- token NAMES only; each product service owns its own whitelist and resolver
-- (leads-service knows what lead_first_name means, hr-service knows
-- employee_name). Deliberately no central registry of every product's fields —
-- that would couple this table to every product's data model.
CREATE TABLE IF NOT EXISTS comms.message_templates (
  id                     UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  -- Audience, widest to narrowest. Both NULL = platform-wide default.
  -- org_id without tenant_id is meaningless, hence the CHECK below.
  tenant_id              UUID    REFERENCES entity.tenants(id)       ON DELETE CASCADE,
  org_id                 UUID    REFERENCES entity.organizations(id) ON DELETE CASCADE,
  -- Which product surface offers this template. Mirrors the vocabulary of
  -- entity.tenant_modules.module; left unconstrained so a new product can seed
  -- its templates without a schema change.
  module                 TEXT    NOT NULL,
  channel                TEXT    NOT NULL CHECK (channel IN ('whatsapp', 'email')),
  name                   TEXT    NOT NULL,
  label                  TEXT    NOT NULL,
  description            TEXT,
  -- WhatsApp only: the name approved in the Interakt/Meta console.
  provider_template_name TEXT,
  language_code          TEXT    NOT NULL DEFAULT 'en',
  -- Email only: the copy we send and interpolate ourselves.
  subject                TEXT,
  body_template          TEXT,
  preview_text           TEXT,
  header_fields          TEXT[]  NOT NULL DEFAULT '{}',
  body_fields            TEXT[]  NOT NULL DEFAULT '{}',
  sort_order             INT     NOT NULL DEFAULT 0,
  is_active              BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted             BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at             TIMESTAMPTZ,
  deleted_by             UUID,
  created_by             UUID,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),

  CONSTRAINT ck_message_templates_org_needs_tenant
    CHECK (org_id IS NULL OR tenant_id IS NOT NULL),
  -- Each channel must carry its own payload and only its own, so a
  -- half-configured row fails at seed time rather than at send time.
  CONSTRAINT ck_message_templates_whatsapp_shape
    CHECK (channel <> 'whatsapp' OR (
      provider_template_name IS NOT NULL AND subject IS NULL AND body_template IS NULL)),
  CONSTRAINT ck_message_templates_email_shape
    CHECK (channel <> 'email' OR (
      subject IS NOT NULL AND body_template IS NOT NULL AND provider_template_name IS NULL))
);

COMMENT ON TABLE comms.message_templates IS
  'Cross-product outbound message catalog. Resolve by (module, channel, name), most specific audience wins: org > tenant > global.';
COMMENT ON COLUMN comms.message_templates.module IS
  'Product surface offering the template (lms, leave, attendance, tasks, ...). Mirrors entity.tenant_modules.module.';
COMMENT ON COLUMN comms.message_templates.provider_template_name IS
  'WhatsApp only. The template name approved in the Interakt/Meta console, sent verbatim to the Interakt API. NULL for email.';
COMMENT ON COLUMN comms.message_templates.body_template IS
  'Email only. The body we send and interpolate. NULL for WhatsApp, where the body lives in the approved template at Meta.';
COMMENT ON COLUMN comms.message_templates.body_fields IS
  'Ordered placeholder tokens. Token NAMES only — each product service owns its own whitelist and resolver.';

-- ===================================================================
-- SECURITY HARDENING BLOCK
-- (Issues: #4 JWT blocklist, #15 audit.activities RLS, #19 view
--  security_invoker, #28 iam.user_org_mapping policy split, #32 audit.audit_log)
-- ===================================================================

-- ── TOKEN BLOCKLIST (issue #4: DB-backed JWT revocation) ──────────
-- Supports revocation at JTI (logout), user, org, and tenant level.
CREATE TABLE IF NOT EXISTS iam.token_blocklist (
  id          UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  jti         TEXT,
  user_id     UUID        REFERENCES iam.users(id)         ON DELETE CASCADE,
  org_id      UUID        REFERENCES entity.organizations(id) ON DELETE CASCADE,
  tenant_id   UUID,
  revoked_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_by  UUID        REFERENCES iam.users(id)         ON DELETE SET NULL,
  reason      TEXT,
  expires_at  TIMESTAMPTZ NOT NULL,
  CONSTRAINT chk_blocklist_has_scope CHECK (
    jti IS NOT NULL OR user_id IS NOT NULL OR org_id IS NOT NULL OR tenant_id IS NOT NULL
  )
);

-- ===================================================================
-- META CONVERSION API — Tables for bidirectional Meta Lead Ads integration
-- Inbound:  Meta webhook → lms.marketing_leads + ext.meta_leads
-- Outbound: CRM stage changes → Meta CAPI conversion events
-- ===================================================================


-- ── META_ORG_CONFIG (removed) ──────────────────────────────────────
-- Superseded by ext.meta_tenant_config + ext.meta_page_form_org_map below:
-- one Meta App/Business Manager is registered per TENANT (not per org), and
-- individual orgs/branches are attributed via their Page+Form combination,
-- since a single tenant-level app can have many orgs' Pages/Forms behind it.
DROP TABLE IF EXISTS ext.meta_org_config CASCADE;

-- ── META_TENANT_CONFIG: per-tenant Meta app credentials + CAPI config ─
-- tenant_id is nullable to support ONE additional row shared across
-- MULTIPLE tenants (a single Meta App/Business Manager receiving leads
-- for more than one tenant). That row's webhook callback URL omits the
-- integration id (POST /meta/webhook instead of /meta/webhook/:integrationId);
-- tenant AND org are then both resolved from ext.meta_page_form_org_map via
-- page_id/form_id, which is already globally unique
-- (uq_meta_page_form_org_map UNIQUE (page_id, form_id)).
-- Per-tenant rows (tenant_id NOT NULL) are unaffected and work as before.
CREATE TABLE IF NOT EXISTS ext.meta_tenant_config (
  id                 UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id          UUID        REFERENCES entity.tenants(id),
  app_secret         TEXT        NOT NULL,
  verify_token       TEXT        NOT NULL,
  pixel_id           TEXT        NOT NULL,
  access_token       TEXT        NOT NULL,
  graph_api_version  TEXT        NOT NULL DEFAULT 'v21.0',
  is_active          BOOLEAN     NOT NULL DEFAULT true,
  capi_trigger_stages UUID[]     NOT NULL DEFAULT '{}',
  field_mappings     JSONB,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meta_tenant_config_tenant UNIQUE (tenant_id)
);

-- ── META_PAGE_FORM_ORG_MAP: Page+Form -> org attribution ──────────
-- A Meta lead form always belongs to exactly one Page, but a single Page can
-- run many forms across different campaigns/purposes, and those forms are not
-- guaranteed to belong to the same org (e.g. a shared/corporate Page running
-- location-specific forms). form_id, when set, is the authoritative routing
-- key (globally unique in Meta's system) and narrows routing to that one
-- form. form_id may be NULL for a page-level subscription: every leadgen
-- form discovered under that Page routes to the row's org, unless a more
-- specific form_id row exists for that same page (exact form_id match always
-- wins over the page-level fallback — see common/mappings.py::resolve() and
-- page-org-map.service.ts::resolveOrgId).
CREATE TABLE IF NOT EXISTS ext.meta_page_form_org_map (
  id          UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID        NOT NULL REFERENCES entity.tenants(id),
  org_id      UUID        NOT NULL REFERENCES entity.organizations(id),
  page_id     BIGINT      NOT NULL,
  form_id     BIGINT,
  platform    TEXT        NOT NULL CHECK (platform IN ('fb', 'ig', 'wa')),
  is_active   BOOLEAN     NOT NULL DEFAULT true,
  -- Recorded by sync_leads.py after each pull run against a form, for
  -- observability/reporting (Meta's /{form-id}/leads edge does not
  -- reliably support server-side "since" filtering, so this is not used
  -- as a query filter — dedup on ext.meta_leads.meta_lead_id is the real
  -- cursor).
  last_synced_at TIMESTAMPTZ,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meta_page_form_org_map UNIQUE (page_id, form_id)
);

-- Postgres treats NULL as distinct in a UNIQUE constraint, so the constraint
-- above alone would allow multiple page-level (form_id IS NULL) rows for the
-- same page. At most one active page-level subscription per page is allowed.
CREATE UNIQUE INDEX IF NOT EXISTS uq_meta_page_form_org_map_page_level
  ON ext.meta_page_form_org_map (page_id)
  WHERE form_id IS NULL AND is_active = true;

-- ── META_FORMS: cache of discovered Lead Ads forms per tenant/page ─────
-- Populated by sync_forms.py. Lets an admin see which forms exist on Meta
-- vs. which ones already have an org mapping in ext.meta_page_form_org_map.
CREATE TABLE IF NOT EXISTS ext.meta_forms (
  id                 UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id          UUID        NOT NULL REFERENCES entity.tenants(id),
  page_id            BIGINT      NOT NULL,
  form_id            BIGINT      NOT NULL,
  name               TEXT,
  status             TEXT,
  leads_count        INT,
  meta_created_time  TIMESTAMPTZ,
  last_synced_at     TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meta_forms_form_id UNIQUE (form_id)
);

-- ── META_LEADS: raw Meta lead data linked to lms.marketing_leads ──────
CREATE TABLE IF NOT EXISTS ext.meta_leads (
  id                 UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id             UUID        NOT NULL REFERENCES entity.organizations(id),
  marketing_lead_id  UUID        REFERENCES lms.marketing_leads(id) ON DELETE SET NULL,
  meta_lead_id       BIGINT      NOT NULL,
  page_id            BIGINT,
  form_id            BIGINT      NOT NULL,
  campaign_id        BIGINT,
  adset_id           BIGINT,
  ad_id              BIGINT,
  platform           TEXT        CHECK (platform IN ('fb', 'ig', 'wa')),
  lead_created_at    TIMESTAMPTZ NOT NULL,
  full_name          TEXT,
  first_name         TEXT,
  last_name          TEXT,
  email              TEXT,
  phone              TEXT,
  whatsapp_number    TEXT,
  raw_field_data     JSONB,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meta_leads_meta_lead_id UNIQUE (meta_lead_id)
);

-- ── META_LEAD_CUSTOM_FIELDS: unmapped form fields (1:many) ────────
CREATE TABLE IF NOT EXISTS ext.meta_lead_custom_fields (
  id                 UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  meta_lead_id       UUID        NOT NULL REFERENCES ext.meta_leads(id) ON DELETE CASCADE,
  org_id             UUID        NOT NULL REFERENCES entity.organizations(id),
  question_key       TEXT        NOT NULL,
  question_value     TEXT,
  CONSTRAINT uq_meta_custom_field UNIQUE (meta_lead_id, question_key)
);

-- ── META_CAPI_OUTBOUND_LOGS: CAPI event audit trail ──────────────
CREATE TABLE IF NOT EXISTS ext.meta_capi_outbound_logs (
  id                   UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id               UUID        NOT NULL REFERENCES entity.organizations(id),
  marketing_lead_id    UUID        NOT NULL REFERENCES lms.marketing_leads(id),
  meta_lead_id         UUID        REFERENCES ext.meta_leads(id) ON DELETE SET NULL,
  event_name           TEXT        NOT NULL,
  event_id             TEXT        NOT NULL,
  delivery_status      TEXT        NOT NULL CHECK (delivery_status IN ('SUCCESS', 'FAILED', 'PENDING')),
  fb_trace_id          TEXT,
  request_payload      JSONB       NOT NULL,
  response_payload     JSONB,
  triggered_by         TEXT        NOT NULL CHECK (triggered_by IN ('auto_stage_change', 'manual')),
  triggered_by_user_id UUID,
  sent_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── META_CAPI_EVENT_TYPES: lookup of supported Meta CAPI event names ──
CREATE TABLE IF NOT EXISTS ext.meta_capi_event_types (
  id          SMALLINT     GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code        VARCHAR(50)  NOT NULL,
  label       VARCHAR(100) NOT NULL,
  description TEXT,
  is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
  sort_order  SMALLINT     NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_meta_capi_event_types_code UNIQUE (code)
);

-- ── LEAD_STAGE_CAPI_EVENT_MAP: lms.lead_stage -> Meta CAPI event fired on transition ──
-- Joined by stage_id (UUID), never by stage name text — a stage with no row
-- here simply does not fire a CAPI event on transition.
--
-- TENANT-SCOPED, because lms.lead_stage is: every tenant owns its own copy of
-- the stage catalog, so this table holds one row per tenant per mapped stage.
-- The header used to call it a "global mapping mirroring lms.lead_stage being
-- a shared lookup" — that stopped being true when the stage catalog was
-- cloned per tenant, and the tenant_id/RLS never followed. app_user holds
-- SELECT/INSERT/UPDATE here (07_grants.sql), so without them one tenant could
-- read and repoint another tenant's conversion-event wiring.
--
-- tenant_id IS NULL marks a platform template row, exactly as in lms.lead_stage
-- itself; entity.seed_tenant_lms_catalogs() clones it per tenant.
--
-- The FK is composite on (tenant_id, stage_id): RLS scopes reads, but only the
-- FK stops a row being written against another tenant's stage in the first
-- place. Same reasoning as the geo tables above.
CREATE TABLE IF NOT EXISTS ext.lead_stage_capi_event_map (
  id                 UUID        PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id          UUID        REFERENCES entity.tenants(id) ON DELETE CASCADE,
  stage_id           UUID        NOT NULL UNIQUE,
  capi_event_type_id SMALLINT    NOT NULL REFERENCES ext.meta_capi_event_types(id) ON DELETE RESTRICT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_capi_event_map_stage
    FOREIGN KEY (tenant_id, stage_id) REFERENCES lms.lead_stage (tenant_id, id)
    ON DELETE CASCADE
);

-- ── META_LEAD_ADDRESSES: address fields from Meta lead forms (1:1) ────
CREATE TABLE IF NOT EXISTS ext.meta_lead_addresses (
  meta_lead_id    UUID        PRIMARY KEY REFERENCES ext.meta_leads(id) ON DELETE CASCADE,
  org_id          UUID        NOT NULL REFERENCES entity.organizations(id),
  street_address  TEXT,
  city            TEXT,
  state           TEXT,
  province        TEXT,
  country         TEXT,
  postal_code     TEXT,
  zip_code        TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── META_LEAD_PROFESSIONAL: job/company fields from Meta lead forms (1:1) ─
CREATE TABLE IF NOT EXISTS ext.meta_lead_professional (
  meta_lead_id      UUID        PRIMARY KEY REFERENCES ext.meta_leads(id) ON DELETE CASCADE,
  org_id            UUID        NOT NULL REFERENCES entity.organizations(id),
  job_title         TEXT,
  company_name      TEXT,
  work_email        TEXT,
  work_phone_number TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── META_LEAD_DEMOGRAPHICS: demographic fields from Meta lead forms (1:1) ─
CREATE TABLE IF NOT EXISTS ext.meta_lead_demographics (
  meta_lead_id         UUID        PRIMARY KEY REFERENCES ext.meta_leads(id) ON DELETE CASCADE,
  org_id               UUID        NOT NULL REFERENCES entity.organizations(id),
  date_of_birth        DATE,
  gender               TEXT,
  marital_status       TEXT,
  relationship_status  TEXT,
  military_status      TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMIT;
