-- ===================================================================
-- 03_tables_product.sql
--
-- Product tables: hr, task, per-product RBAC (lms/hr/task.roles + member_roles),
-- the tenant-catalog engine tables, and entity.tenant_modules.
-- All of these reference entity.tenants / iam.users from 02_.
--
-- Generated by the db_scripts consolidation. Fresh-install only:
-- there is no in-place upgrade path, no ALTER-after-the-fact section,
-- and no _migrations/ folder. Schema changes are made in the
-- CREATE statement itself and the database is rebuilt.
-- ===================================================================

BEGIN;

-- ===================================================================
-- entity.tenant_modules — per-tenant module entitlements (§4.4)
-- Gates which platform modules (crm | leave | attendance | tasks) a tenant
-- has licensed. Only root_service writes; tenant_admin + app_user read (so a
-- service can check entitlement for its current org's tenant).
-- ===================================================================
CREATE TABLE IF NOT EXISTS entity.tenant_modules (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  module      TEXT    NOT NULL CHECK (module IN ('lms','leave','attendance','tasks')),
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  enabled_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT uq_tenant_modules_tenant_module UNIQUE (tenant_id, module)
);


-- ===================================================================
-- HR GLOBAL LOOKUP TABLES  (UUID PKs, same shape as lms.lead_stage — no RLS)
-- Managed globally (admin-service slugs); readable by every subject role.
-- ===================================================================

-- employment_types / leave_types / attendance_statuses / leave_request_statuses
-- are tenant-scoped (the first three historically via 22_tenant-scope-lookups.sql
-- ALTER; folded directly into the CREATE TABLE here). No un-scoped seed INSERT:
-- per-tenant default rows are provisioned by entity.seed_tenant_defaults()
-- (registry in reference_data/07_catalog_registry.sql) at tenant-creation time,
-- not at DDL time — no tenant exists yet when this script runs.
--
-- hr.leave_request_statuses was the one exception, left global "per 22's
-- original scope note". That made it the odd one out among four sibling HR
-- lookups and the only one a tenant could not see listed alongside the rest.
-- It is tenant-scoped as of 1.26.0 and provisioned through the same registry.
--
-- NOTE the `name` values here are a MACHINE vocabulary, not free text:
-- lms/hr workflow logic keys on 'approved'/'pending'/'cancelled' etc. — see
-- hr.check_leave_request_completion() in 04_functions_triggers.sql. A tenant
-- may relabel a status; renaming or deleting one breaks leave approval.
CREATE TABLE IF NOT EXISTS hr.employment_types (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_employment_types_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS hr.leave_types (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_paid     BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_leave_types_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS hr.leave_request_statuses (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_leave_request_statuses_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS hr.attendance_statuses (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_attendance_statuses_tenant_name UNIQUE (tenant_id, name)
);


-- ===================================================================
-- ORG-SCOPED HR REFERENCE TABLES
-- Standard operational-table recipe (copied from marketing.ad_campaigns):
-- UUIDv7 PK, org_id FK, soft-delete + audit columns, set_updated_at +
-- soft_delete_row + set_org_id + set_created_by + audit_row_changes triggers,
-- org_isolation_policy + tenant_isolation_policy RLS.
-- ===================================================================

-- ── hr.departments → MOVED to iam.departments (Tier C) ─────────────
-- Departments now live in IAM (see db_scripts/02_schema.sql: iam.departments),
-- tenant-scoped, so roles in every product can belong to a department.
-- hr.employee_profiles.department_id below references iam.departments.

-- ── hr.designations ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS hr.designations (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id      UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  name        TEXT    NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at  TIMESTAMPTZ,
  deleted_by  UUID,
  created_by  UUID,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_designations_active_deleted CHECK (NOT (is_active AND is_deleted))
);


-- ===================================================================
-- hr.employee_profiles — the IAM ↔ HR bridge (§4.1)
-- 1:1 with iam.users (PK = user_id). Holds employment facts; keeps
-- iam.users pure (auth + hierarchy). tenant_id is denormalized and kept
-- consistent with org_id by a BEFORE trigger so employee_code can be made
-- unique per tenant (a joined-scope index isn't possible).
-- Face-verification columns are created now but stay dormant until Prompt 11.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.employee_profiles (
  user_id             UUID    PRIMARY KEY REFERENCES iam.users(id)            ON DELETE RESTRICT,
  org_id              UUID    NOT NULL    REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  -- denormalized from entity.organizations.tenant_id via trigger (see below);
  -- exists solely to enforce employee_code uniqueness per tenant.
  tenant_id           UUID    NOT NULL    REFERENCES entity.tenants(id)       ON DELETE RESTRICT,
  employee_code       TEXT,
  date_of_joining     DATE    NOT NULL,
  date_of_exit        DATE,
  employment_type_id  UUID    REFERENCES hr.employment_types(id) ON DELETE RESTRICT,
  department_id       UUID    REFERENCES iam.departments(id)     ON DELETE RESTRICT,
  designation_id      UUID    REFERENCES hr.designations(id)     ON DELETE RESTRICT,
  probation_end_date  DATE,
  -- days of week off, 0=Sunday .. 6=Saturday; overridable by shift assignment
  weekly_off_pattern  SMALLINT[] NOT NULL DEFAULT '{0,6}',
  metadata            JSONB   NOT NULL DEFAULT '{}',
  -- ── Face-verification enrollment (dormant until Prompt 11) ──
  reference_photo_url TEXT,
  face_subject_id     TEXT,
  face_enrolled_at    TIMESTAMPTZ,
  face_consent_at     TIMESTAMPTZ,
  -- ── standard soft-delete / audit ──
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at          TIMESTAMPTZ,
  deleted_by          UUID,
  created_by          UUID,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_employee_profiles_exit_after_joining
    CHECK (date_of_exit IS NULL OR date_of_exit >= date_of_joining),
  CONSTRAINT chk_employee_profiles_active_deleted CHECK (NOT (is_active AND is_deleted))
);


-- ===================================================================
-- 1. hr.holiday_calendars — org-scoped operational table
--    Standard recipe (marketing.ad_campaigns): UUIDv7 PK, org_id FK,
--    soft-delete + audit, set_updated_at / soft_delete_row / set_org_id /
--    set_created_by / audit_row_changes triggers, org + tenant RLS.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.holiday_calendars (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id      UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  name        TEXT    NOT NULL,
  year        INT     NOT NULL,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at  TIMESTAMPTZ,
  deleted_by  UUID,
  created_by  UUID,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_holiday_calendars_active_deleted CHECK (NOT (is_active AND is_deleted))
);


-- ── hr.holidays ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS hr.holidays (
  id            UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  calendar_id   UUID    NOT NULL REFERENCES hr.holiday_calendars(id) ON DELETE CASCADE,
  org_id        UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  holiday_date  DATE    NOT NULL,
  name          TEXT    NOT NULL,
  is_optional   BOOLEAN NOT NULL DEFAULT FALSE,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at    TIMESTAMPTZ,
  deleted_by    UUID,
  created_by    UUID,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_holidays_active_deleted CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT uq_holidays_calendar_date   UNIQUE (calendar_id, holiday_date)
);


-- ===================================================================
-- 2. hr.leave_policies — per (tenant, org?, leave_type) rules (§4.2)
--    org_id NULL = tenant-wide default; an org row overrides it. Effective-
--    dated by applicable_from (new row per revision, never mutate history).
--    Writes are restricted to the tenant_admin RLS role; the app layer will
--    ALSO gate policy management to hr_admin / org_admin via serviceDb.
--    NB: no set_org_id trigger — org_id is intentionally nullable here.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.leave_policies (
  id                            UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id                     UUID    NOT NULL REFERENCES entity.tenants(id)       ON DELETE CASCADE,
  org_id                        UUID    REFERENCES entity.organizations(id)          ON DELETE CASCADE,
  leave_type_id                 UUID    NOT NULL REFERENCES hr.leave_types(id)       ON DELETE RESTRICT,
  accrual_frequency             TEXT    NOT NULL DEFAULT 'none'
                                          CHECK (accrual_frequency IN ('monthly','quarterly','yearly','none')),
  accrual_amount                NUMERIC(5,2) NOT NULL DEFAULT 0,
  max_balance                   NUMERIC(5,2),
  carry_forward                 BOOLEAN NOT NULL DEFAULT FALSE,
  max_carry_forward             NUMERIC(5,2),
  max_consecutive_days          SMALLINT,
  min_notice_days               SMALLINT NOT NULL DEFAULT 0,
  allow_half_day                BOOLEAN NOT NULL DEFAULT TRUE,
  requires_document_after_days  SMALLINT,
  -- Approval depth: any value >= 1. The approver chain walks manager_id upward
  -- N levels; a chain shorter than N terminates at the highest available
  -- manager (org_admin / hr_admin fallback). See Platform_Expansion_Plan §4.2.
  approval_levels               SMALLINT NOT NULL DEFAULT 1 CHECK (approval_levels >= 1),
  applicable_from               DATE    NOT NULL,
  is_active                     BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted                    BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at                    TIMESTAMPTZ,
  deleted_by                    UUID,
  created_by                    UUID,
  created_at                    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at                    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_leave_policies_active_deleted CHECK (NOT (is_active AND is_deleted))
);


-- ===================================================================
-- 2b. hr.hr_settings — leave-cycle configuration (§4.2)
--     tenant-wide default (org_id NULL), org row overrides. Read by every
--     app_user in the tenant; written via the service path.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.hr_settings (
  id                       UUID     PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id                UUID     NOT NULL REFERENCES entity.tenants(id)        ON DELETE CASCADE,
  org_id                   UUID     REFERENCES entity.organizations(id)           ON DELETE CASCADE,
  -- 4 = April–March financial year (India FY default)
  leave_cycle_start_month  SMALLINT NOT NULL DEFAULT 4
                                      CHECK (leave_cycle_start_month BETWEEN 1 AND 12),
  created_at               TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);


-- ===================================================================
-- 4. hr.leave_requests — emitted BEFORE hr.leave_ledger because the ledger's
--    leave_request_id FK references this table (§3 note). Standard operational
--    recipe + a self policy (users always see & insert their own requests) +
--    an is_open exclusion guard against overlapping active requests.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.leave_requests (
  id            UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  user_id       UUID    NOT NULL REFERENCES iam.users(id)                   ON DELETE RESTRICT,
  org_id        UUID    NOT NULL REFERENCES entity.organizations(id)        ON DELETE RESTRICT,
  leave_type_id UUID    NOT NULL REFERENCES hr.leave_types(id)              ON DELETE RESTRICT,
  start_date    DATE    NOT NULL,
  end_date      DATE    NOT NULL,
  start_half    TEXT    NOT NULL DEFAULT 'full'
                          CHECK (start_half IN ('full','first_half','second_half')),
  end_half      TEXT    NOT NULL DEFAULT 'full'
                          CHECK (end_half IN ('full','first_half','second_half')),
  days_count    NUMERIC(5,2) NOT NULL CHECK (days_count > 0),
  reason        TEXT,
  status_id     UUID    NOT NULL REFERENCES hr.leave_request_statuses(id)   ON DELETE RESTRICT,
  document_url  TEXT,
  -- Maintained by trigger from status_id: TRUE while pending/approved, else
  -- FALSE. Drives the overlap exclusion constraint below.
  is_open       BOOLEAN NOT NULL DEFAULT TRUE,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at    TIMESTAMPTZ,
  deleted_by    UUID,
  created_by    UUID,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_leave_requests_active_deleted CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT chk_leave_requests_date_order     CHECK (end_date >= start_date),
  -- No two OPEN (pending/approved), non-deleted requests for the same user may
  -- have overlapping inclusive date ranges.
  CONSTRAINT excl_leave_requests_no_overlap
    EXCLUDE USING gist (
      user_id WITH =,
      daterange(start_date, end_date, '[]') WITH &&
    ) WHERE (is_open AND NOT is_deleted)
);


-- ── hr.leave_request_status_log — append-only (mirrors lms.lead_status_log) ──
CREATE TABLE IF NOT EXISTS hr.leave_request_status_log (
  id             UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id         UUID    NOT NULL REFERENCES entity.organizations(id)     ON DELETE RESTRICT,
  request_id     UUID    NOT NULL REFERENCES hr.leave_requests(id)        ON DELETE CASCADE,
  changed_by_id  UUID    REFERENCES iam.users(id)                         ON DELETE SET NULL,
  old_status_id  UUID    REFERENCES hr.leave_request_statuses(id)         ON DELETE RESTRICT,
  new_status_id  UUID    NOT NULL REFERENCES hr.leave_request_statuses(id) ON DELETE RESTRICT,
  note           TEXT,
  changed_at     TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);


-- ===================================================================
-- 3. hr.leave_ledger — append-only source of truth for balances (§4.2)
--    SELECT-only for app_user (own rows) + tenant_admin (tenant scope);
--    INSERT only via the service path (root_service / hr-service), exactly as
--    lms.lead_status_log locks down its privileges. leave_request_id FK is
--    valid now that hr.leave_requests exists above.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.leave_ledger (
  id                UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  user_id           UUID    NOT NULL REFERENCES iam.users(id)            ON DELETE RESTRICT,
  org_id            UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  leave_type_id     UUID    NOT NULL REFERENCES hr.leave_types(id)       ON DELETE RESTRICT,
  entry_type        TEXT    NOT NULL
                              CHECK (entry_type IN ('accrual','consumption','adjustment','carry_forward','encashment','lapse')),
  amount            NUMERIC(6,2) NOT NULL CHECK (amount <> 0),
  leave_request_id  UUID    REFERENCES hr.leave_requests(id)             ON DELETE SET NULL,
  period            TEXT,
  effective_date    DATE    NOT NULL,
  note              TEXT,
  created_by        UUID,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);


-- ===================================================================
-- 5. hr.leave_request_approvals — one row per approval level (§4.2)
--    org/tenant isolation + an approver policy (approver may SELECT/UPDATE
--    rows where approver_id = current user). Created via the service path when
--    a request is submitted; the approver acts on their own row.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.leave_request_approvals (
  id                UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  leave_request_id  UUID    NOT NULL REFERENCES hr.leave_requests(id)     ON DELETE CASCADE,
  org_id            UUID    NOT NULL REFERENCES entity.organizations(id)  ON DELETE RESTRICT,
  level             SMALLINT NOT NULL,
  approver_id       UUID    NOT NULL REFERENCES iam.users(id)             ON DELETE RESTRICT,
  action            TEXT    NOT NULL DEFAULT 'pending'
                              CHECK (action IN ('pending','approved','rejected')),
  acted_at          TIMESTAMPTZ,
  comment           TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT uq_leave_request_approvals_request_level UNIQUE (leave_request_id, level)
);


-- NOTE: entity.organizations.geo_lat / geo_lng (the geofence-centre columns
-- this module needs) now live directly in entity.organizations' CREATE TABLE
-- (msq-hrms's copy of 02_schema.sql) -- originally added here via ALTER
-- TABLE ... ADD COLUMN IF NOT EXISTS.


-- ===================================================================
-- 1. hr.attendance_rules — attendance capture rules (§4.3)
--    Tenant-wide default (org_id NULL), org row overrides — the same scoping
--    hr.hr_settings and hr.leave_policies use, so a tenant can configure every
--    org at once and any org can still diverge. UNIQUE on
--    (tenant_id, COALESCE(org_id, 0-uuid)) among non-deleted, so there is at
--    most one row per scope. Standard operational recipe + org/tenant RLS.
--    Readable by every app_user in the tenant (they need the rules before
--    punching, and the row that applies to them may be the tenant default);
--    writes are gated to hr_admin/org_admin at the app layer (same FOR ALL
--    app_user pattern as hr.holidays), with tenant-scope writes additionally
--    requiring a tenant_admin platform role.
--    Face-verification columns are created now but stay DORMANT (no enforcement
--    logic in this increment).
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.attendance_rules (
  id                       UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id                UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  -- NULL = the tenant-wide default, applying to every org without its own row.
  org_id                   UUID    REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  geofence_enabled         BOOLEAN NOT NULL DEFAULT TRUE,
  geofence_radius_meters   INT     NOT NULL DEFAULT 200 CHECK (geofence_radius_meters > 0),
  require_photo            BOOLEAN NOT NULL DEFAULT TRUE,
  require_geo              BOOLEAN NOT NULL DEFAULT TRUE,
  allow_wfh_checkin        BOOLEAN NOT NULL DEFAULT FALSE,
  -- ── Face-verification rules (DORMANT until the face-verification increment) ──
  require_face_match       BOOLEAN NOT NULL DEFAULT FALSE,
  face_match_threshold     NUMERIC(5,2) NOT NULL DEFAULT 85 CHECK (face_match_threshold BETWEEN 50 AND 100),
  face_match_action        TEXT    NOT NULL DEFAULT 'flag' CHECK (face_match_action IN ('flag','block')),
  -- Minimum days a member must wait before self-changing their reference photo.
  -- Enforced for self-service only; hr_admin/org_admin change it with no wait.
  photo_change_cooldown_days INT   NOT NULL DEFAULT 30 CONSTRAINT chk_attendance_rules_cooldown_nonneg CHECK (photo_change_cooldown_days >= 0),
  -- How long daily check-in/out selfies are retained before the cleanup job
  -- deletes them. Does NOT apply to the enrolled reference photo (avatar).
  image_retention_days       INT   NOT NULL DEFAULT 90 CONSTRAINT chk_attendance_rules_retention_pos CHECK (image_retention_days >= 1),
  -- ── Day-classification thresholds (org-level fallback) ──
  -- Precedence when classifying a day: the employee's assigned hr.shifts row
  -- wins; these are the org fallback for employees with NO shift assignment;
  -- the service's DEFAULT_THRESHOLDS constant is the last resort.
  min_half_day_minutes     SMALLINT NOT NULL DEFAULT 240 CONSTRAINT chk_attendance_rules_half_day_range CHECK (min_half_day_minutes BETWEEN 0 AND 1440),
  min_full_day_minutes     SMALLINT NOT NULL DEFAULT 480 CONSTRAINT chk_attendance_rules_full_day_range CHECK (min_full_day_minutes BETWEEN 0 AND 1440),
  -- How many levels of the reporting chain must approve a regularization, the
  -- same knob hr.leave_policies.approval_levels is for leave. The chain itself
  -- is resolved from iam.reporting_lines by the same resolveApprovers used for
  -- leave, so a correction request escalates up exactly the hierarchy a leave
  -- request would. Defaults to 1 (direct manager only).
  regularization_approval_levels SMALLINT NOT NULL DEFAULT 1
                             CONSTRAINT chk_attendance_rules_reg_levels CHECK (regularization_approval_levels >= 1),
  -- How many days back a member may file a regularization, counted in the ORG's
  -- timezone (entity.organizations.timezone), not UTC. 0 = today only. Enforced
  -- in hr-service's createRegularization, which also rejects any future date —
  -- correcting a day that has not happened yet is meaningless, and a work_date
  -- far in the past resolves an approver chain that may not have existed then.
  regularization_max_backdate_days SMALLINT NOT NULL DEFAULT 30
                             CONSTRAINT chk_attendance_rules_reg_backdate CHECK (regularization_max_backdate_days BETWEEN 0 AND 365),
  -- ── standard soft-delete / audit ──
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at  TIMESTAMPTZ,
  deleted_by  UUID,
  created_by  UUID,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_attendance_rules_active_deleted CHECK (NOT (is_active AND is_deleted)),
  -- A half-day floor above the full-day floor would make 'half_day' unreachable.
  CONSTRAINT chk_attendance_rules_day_threshold_order CHECK (min_half_day_minutes <= min_full_day_minutes)
);


-- ===================================================================
-- 2. hr.shifts — org-scoped shift definitions (§4.3)
--    Standard recipe + org/tenant RLS. Readable by all app_user; writes gated
--    to hr_admin/org_admin at the app layer.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.shifts (
  id                    UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id                UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  name                  TEXT    NOT NULL,
  start_time            TIME    NOT NULL,
  end_time              TIME    NOT NULL,
  grace_minutes         SMALLINT NOT NULL DEFAULT 10,
  min_half_day_minutes  SMALLINT NOT NULL DEFAULT 240,
  min_full_day_minutes  SMALLINT NOT NULL DEFAULT 480,
  is_night_shift        BOOLEAN NOT NULL DEFAULT FALSE,
  -- A split shift works 2+ separate slots in a day (see hr.shift_segments).
  -- start_time/end_time above stay the OUTER window the segments live inside.
  is_split              BOOLEAN NOT NULL DEFAULT FALSE,
  is_active             BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted            BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at            TIMESTAMPTZ,
  deleted_by            UUID,
  created_by            UUID,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_shifts_active_deleted CHECK (NOT (is_active AND is_deleted))
);


-- ===================================================================
-- 2b. hr.shift_segments — ordered in-day slots of a split shift
--     Standard recipe + org/tenant RLS. A split shift (hr.shifts.is_split)
--     declares 2+ segments, e.g. 09:00-13:00 and 17:00-21:00; the parent shift's
--     start_time/end_time remain the OUTER window they must nest inside.
--
--     Two rules are NOT expressible as table CHECKs and are enforced in the
--     service layer (attendance.repository createShift/updateShift + the Zod
--     superRefine in @hr/validation):
--       - every segment nests inside the parent shift's window (cross-table)
--       - segments do not overlap each other (cross-row)
--     The gist exclusion used by hr.shift_assignments does not transfer: these
--     are TIME columns, and a night-shift segment legitimately wraps midnight
--     (22:00-02:00), so an inverted range is valid rather than an error.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.shift_segments (
  id          UUID     PRIMARY KEY DEFAULT public.gen_uuidv7(),
  shift_id    UUID     NOT NULL REFERENCES hr.shifts(id)             ON DELETE CASCADE,
  org_id      UUID     NOT NULL REFERENCES entity.organizations(id)  ON DELETE RESTRICT,
  seq         SMALLINT NOT NULL,
  start_time  TIME     NOT NULL,
  end_time    TIME     NOT NULL,
  is_active   BOOLEAN  NOT NULL DEFAULT TRUE,
  is_deleted  BOOLEAN  NOT NULL DEFAULT FALSE,
  deleted_at  TIMESTAMPTZ,
  deleted_by  UUID,
  created_by  UUID,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_shift_segments_active_deleted CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT chk_shift_segments_seq_positive   CHECK (seq >= 1)
);


-- ===================================================================
-- 3. hr.shift_assignments — effective-dated user→shift mapping (§4.3)
--    Standard recipe + org/tenant RLS + a self-read policy (a user always sees
--    their own assignment). No overlapping assignments per user among non-deleted
--    rows (gist exclusion on user_id + daterange).
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.shift_assignments (
  id              UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  user_id         UUID    NOT NULL REFERENCES iam.users(id)            ON DELETE RESTRICT,
  org_id          UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  shift_id        UUID    NOT NULL REFERENCES hr.shifts(id)            ON DELETE RESTRICT,
  effective_from  DATE    NOT NULL,
  effective_to    DATE,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at      TIMESTAMPTZ,
  deleted_by      UUID,
  created_by      UUID,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_shift_assignments_active_deleted CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT chk_shift_assignments_date_order     CHECK (effective_to IS NULL OR effective_to >= effective_from),
  -- No two non-deleted assignments for the same user may cover overlapping dates.
  CONSTRAINT excl_shift_assignments_no_overlap
    EXCLUDE USING gist (
      user_id WITH =,
      daterange(effective_from, COALESCE(effective_to, 'infinity'), '[]') WITH &&
    ) WHERE (NOT is_deleted)
);


-- ===================================================================
-- 3b. hr.attendance_geo_exceptions — per-employee geofence exemptions (§4.3)
--     The geofence is a single point (entity.organizations.geo_lat/lng) plus a
--     radius, which two real situations do not fit: someone whose role rotates
--     across locations, and someone approved to work from home for a stretch.
--     The only prior escape hatch was attendance_rules.allow_wfh_checkin, which
--     is org-wide AND self-declared -- switching it on for three field staff
--     hands the whole org a bypass checkbox. This table names the people
--     instead, with dates and a reason.
--     Same effective-dated shape as hr.shift_assignments, including the gist
--     no-overlap exclusion; org/tenant RLS + a self-read policy (a user must be
--     able to see their own exemption before punching).
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.attendance_geo_exceptions (
  id              UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  user_id         UUID    NOT NULL REFERENCES iam.users(id)            ON DELETE RESTRICT,
  org_id          UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  -- remote_role: rotating/field role, tied to no location (usually open-ended).
  -- wfh:         an approved work-from-home stretch (usually date-bounded).
  -- Both skip the fence identically; the type is what the UI and reports read,
  -- so field work never gets counted as working from home.
  exception_type  TEXT    NOT NULL CHECK (exception_type IN ('remote_role','wfh')),
  effective_from  DATE    NOT NULL,
  effective_to    DATE,
  reason          TEXT    NOT NULL,
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted      BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at      TIMESTAMPTZ,
  deleted_by      UUID,
  created_by      UUID,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_geo_exceptions_active_deleted CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT chk_geo_exceptions_date_order     CHECK (effective_to IS NULL OR effective_to >= effective_from),
  CONSTRAINT chk_geo_exceptions_reason         CHECK (length(btrim(reason)) >= 3),
  -- Scoped by type, unlike shift_assignments: a field employee may ALSO be given
  -- a work-from-home stretch without the two rows colliding. Two overlapping
  -- rows of the SAME type are always a data-entry mistake.
  CONSTRAINT excl_geo_exceptions_no_overlap
    EXCLUDE USING gist (
      user_id WITH =,
      org_id WITH =,
      exception_type WITH =,
      daterange(effective_from, COALESCE(effective_to, 'infinity'), '[]') WITH &&
    ) WHERE (NOT is_deleted)
);


-- ===================================================================
-- 4. hr.attendance_events — append-only raw punches (§4.3)
--    Lockdown mirrors hr.leave_ledger: app_user SELECT + INSERT own rows only,
--    tenant_admin SELECT tenant scope, NO UPDATE/DELETE for non-service. Manager
--    / subtree reads happen via the service path (never a broad app_user policy).
--    Corrections go through regularization, never row edits.
--    Face-result columns are created now but stay DORMANT.
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.attendance_events (
  id                   UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  user_id              UUID    NOT NULL REFERENCES iam.users(id)            ON DELETE RESTRICT,
  org_id               UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  event_type           TEXT    NOT NULL CHECK (event_type IN ('check_in','check_out')),
  occurred_at          TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  source               TEXT    NOT NULL CHECK (source IN ('web','mobile','biometric','api')),
  geo_lat              NUMERIC(9,6),
  geo_lng              NUMERIC(9,6),
  distance_from_org_m  NUMERIC(10,2),
  is_within_geofence   BOOLEAN,
  is_wfh               BOOLEAN NOT NULL DEFAULT FALSE,
  -- Which hr.attendance_geo_exceptions row let this punch through the fence.
  -- NULL = none: either an ordinary in-fence punch, or the org-wide
  -- self-declared WFH bypass. Kept separate from is_wfh, which stays the plain
  -- fact "this punch was from home" -- a 'remote_role' punch is out of the fence
  -- but is NOT working from home, and reports must not conflate the two.
  geo_exception_type   TEXT    CHECK (geo_exception_type IN ('remote_role','wfh')),
  photo_url            TEXT,
  -- ── Face-verification results (DORMANT until the face-verification increment) ──
  face_match_score     NUMERIC(5,2),
  face_match_passed    BOOLEAN,
  face_review_status   TEXT    CHECK (face_review_status IN ('pending','cleared','rejected')),
  -- TRUE when this punch fell outside every declared hr.shift_segments slot of
  -- the employee's shift. The punch is still accepted and its minutes still
  -- count; the flag exists so the day surfaces for review. NULL = there was no
  -- shift (or no segments) to judge against — the normal non-split case.
  is_off_segment       BOOLEAN,
  ip                   TEXT,
  device_info          JSONB,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);


-- ===================================================================
-- 5. hr.attendance_days — one resolved row per user per date (§4.3)
--    Upserted by the service path (live punch) and the nightly resolution job.
--    RLS: app_user SELECT own rows; tenant_admin SELECT tenant scope; writes are
--    service-only (org-wide / team reads go through the service path after an
--    authority check, exactly like the leave team queue).
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.attendance_days (
  id                 UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  user_id            UUID    NOT NULL REFERENCES iam.users(id)               ON DELETE RESTRICT,
  org_id             UUID    NOT NULL REFERENCES entity.organizations(id)    ON DELETE RESTRICT,
  work_date          DATE    NOT NULL,
  first_in           TIMESTAMPTZ,
  last_out           TIMESTAMPTZ,
  worked_minutes     INT,
  status_id          UUID    NOT NULL REFERENCES hr.attendance_statuses(id)  ON DELETE RESTRICT,
  is_late            BOOLEAN NOT NULL DEFAULT FALSE,
  is_early_exit      BOOLEAN NOT NULL DEFAULT FALSE,
  -- Any punch of the day landed outside the shift's declared segments.
  has_off_window_punch BOOLEAN NOT NULL DEFAULT FALSE,
  -- A check-in of the day was never closed by a check-out. That session
  -- contributes ZERO minutes, so the day is short until it is regularized.
  has_open_session     BOOLEAN NOT NULL DEFAULT FALSE,
  -- A punch of the day failed (or could not complete) face verification and is
  -- awaiting review. Those minutes are WITHHELD until a reviewer clears it, so
  -- this flag is what explains an otherwise mysteriously short day.
  has_pending_face_review BOOLEAN NOT NULL DEFAULT FALSE,
  leave_request_id   UUID    REFERENCES hr.leave_requests(id)                ON DELETE SET NULL,
  resolved_at        TIMESTAMPTZ,
  resolution_source  TEXT    CHECK (resolution_source IN ('events','leave','holiday','weekly_off','regularization','job')),
  created_at         TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT uq_attendance_days_user_date UNIQUE (user_id, work_date)
);


-- ===================================================================
-- 6. hr.attendance_regularizations — correction requests (§4.3)
--    Standard recipe + org/tenant RLS + a self policy (a user always sees and
--    inserts their own). One open regularization per (user, work_date): partial
--    unique index WHERE status='pending' AND NOT is_deleted. Approvers act via
--    the service path (hr.can_approve authority).
-- ===================================================================
CREATE TABLE IF NOT EXISTS hr.attendance_regularizations (
  id                  UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  user_id             UUID    NOT NULL REFERENCES iam.users(id)               ON DELETE RESTRICT,
  org_id              UUID    NOT NULL REFERENCES entity.organizations(id)    ON DELETE RESTRICT,
  work_date           DATE    NOT NULL,
  requested_status_id UUID    REFERENCES hr.attendance_statuses(id)           ON DELETE RESTRICT,
  requested_in        TIMESTAMPTZ,
  requested_out       TIMESTAMPTZ,
  reason              TEXT    NOT NULL,
  status              TEXT    NOT NULL DEFAULT 'pending'
                              CONSTRAINT chk_attendance_regularizations_status
                              CHECK (status IN ('pending','approved','rejected','cancelled')),
  approver_id         UUID    REFERENCES iam.users(id)                        ON DELETE SET NULL,
  acted_at            TIMESTAMPTZ,
  approver_comment    TEXT,
  is_active           BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted          BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at          TIMESTAMPTZ,
  deleted_by          UUID,
  created_by          UUID,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_attendance_regularizations_active_deleted CHECK (NOT (is_active AND is_deleted))
);

-- ── hr.attendance_regularization_approvals ────────────────────────
-- One row per approval level, exactly like hr.leave_request_approvals. Written
-- when the request is submitted, from the chain resolveApprovers walks up
-- iam.reporting_lines — so a correction request escalates up the same hierarchy
-- a leave request does, for however many levels
-- hr.attendance_rules.regularization_approval_levels says.
--
-- The approver acts on their own row (see the approver_policy in 08_rls.sql);
-- hr_admin / org_admin / tenant_admin can act at any level without being
-- assigned one, via hr.can_approve.
--
-- attendance_regularizations.approver_id / acted_at / approver_comment remain as
-- a denormalized record of the FINAL decision, so existing list screens and the
-- payload shape did not change.
CREATE TABLE IF NOT EXISTS hr.attendance_regularization_approvals (
  id                UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  regularization_id UUID    NOT NULL REFERENCES hr.attendance_regularizations(id) ON DELETE CASCADE,
  org_id            UUID    NOT NULL REFERENCES entity.organizations(id)  ON DELETE RESTRICT,
  level             SMALLINT NOT NULL,
  approver_id       UUID    NOT NULL REFERENCES iam.users(id)             ON DELETE RESTRICT,
  action            TEXT    NOT NULL DEFAULT 'pending'
                              CHECK (action IN ('pending','approved','rejected')),
  acted_at          TIMESTAMPTZ,
  comment           TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT uq_reg_approvals_request_level UNIQUE (regularization_id, level)
);

-- NOTE: the reporting hierarchy used to live here as hr.reporting_lines. It is
-- now iam.reporting_lines (02_tables_core.sql) — a platform-wide concern shared
-- by LMS lead assignment, HR approvals and Tasks team scope, and therefore not
-- ownable by a product schema that 07_grants.sql walls off from the others.


-- ===================================================================
-- CRM Monorepo — Tasks / To-Do (Phase 3, DB layer)
-- Adds the complete task.* model:
--   Global lookups task.task_statuses / task.task_priorities (lms.lead_stage
--   shape, no RLS), org-scoped task.task_lists, task.tasks (+ append-only
--   task.task_status_log via trigger + completed_at consistency trigger),
--   append-only task.task_comments, and the dashboard views
--   (task.vw_my_tasks / task.vw_team_tasks).
-- Prerequisite: 01_init-db.sql + 01_init-lookup-data.sql + 10_init-hr-task-schemas.sql
--               (task schema, task_svc login role, schema USAGE + default
--                privileges for app_user/tenant_admin/root_service on the task schema).
-- Idempotent: safe to re-run (IF NOT EXISTS / ON CONFLICT DO NOTHING /
--             guarded DO blocks / DROP+CREATE for triggers & policies).
-- Style, guard patterns, trigger recipe and RLS mirror db_scripts/10, 11 and 13.
-- Operational tables use the marketing.ad_campaigns recipe; the append-only
-- task_status_log / task_comments logs mirror hr.leave_request_status_log's lockdown.
--
-- VISIBILITY NOTE (documented once, enforced in the app layer — see
-- Architecture.md "Tasks"): task_lists carry a `visibility` of private/team/org.
--   * RLS keeps org isolation for every task.* table PLUS a private-list rule on
--     task_lists (a private list is visible ONLY to its owner, even inside the org).
--   * `team` visibility (a team list is visible to the owner's management subtree)
--     is NOT expressible in a single-row RLS predicate, so it is enforced in the
--     tasks-service repository via iam.vw_user_team_members.
--   * task.tasks RLS is plain org/tenant isolation. A task's effective visibility
--     derives from its list's visibility; rather than a correlated join policy on
--     every task read, the tasks-service applies the private/team/own filter in the
--     query (own tasks — created_by/assignee — are always visible). This keeps the
--     hot read path simple; the alternative (a join RLS policy on task.tasks) was
--     rejected for cost/complexity. See Architecture.md for the rationale.
-- ===================================================================


-- ===================================================================
-- 1. GLOBAL LOOKUP TABLES  (UUID PKs, same shape as lms.lead_stage — no RLS)
--    Managed globally (admin-service /lookups slugs); readable by every subject
--    role. task schema USAGE + default SELECT privileges already granted in 10.
-- ===================================================================

-- ── task.task_statuses ─────────────────────────────────────────────
-- is_terminal marks statuses that close a task (done, cancelled). The
-- completed_at consistency trigger keys specifically off the 'done' status.
-- task.task_statuses / task.task_priorities are tenant-scoped (historically
-- added via 22_tenant-scope-lookups.sql ALTER; folded directly into the
-- CREATE TABLE here). No un-scoped seed INSERT: per-tenant default rows are
-- provisioned by entity.seed_tenant_defaults() (05_catalogs.sql) at
-- tenant-creation time, not at DDL time (no tenant exists yet when this
-- script runs).
CREATE TABLE IF NOT EXISTS task.task_statuses (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  is_terminal BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order  INT     NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_task_statuses_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS task.task_priorities (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  sort_order  INT     NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_task_priorities_tenant_name UNIQUE (tenant_id, name)
);


-- ===================================================================
-- 2. task.task_lists — org-scoped named lists (§4.5)
--    Standard operational recipe + org/tenant RLS + an owner-private rule.
--    `visibility`: private (owner only) | team (owner's subtree, app layer) |
--    org (whole org). Writes gated in the service layer.
-- ===================================================================
CREATE TABLE IF NOT EXISTS task.task_lists (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id      UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  name        TEXT    NOT NULL,
  description TEXT,
  owner_id    UUID    NOT NULL REFERENCES iam.users(id) ON DELETE RESTRICT,
  visibility  TEXT    NOT NULL DEFAULT 'private'
                      CHECK (visibility IN ('private','team','org')),
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at  TIMESTAMPTZ,
  deleted_by  UUID,
  created_by  UUID,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_task_lists_active_deleted CHECK (NOT (is_active AND is_deleted))
);


-- ===================================================================
-- 3. task.tasks — the core task entity (§4.5)
--    Standard operational recipe + org/tenant RLS. list_id ON DELETE SET NULL
--    (deleting a list detaches, never cascades, its tasks). parent_task_id is a
--    self-FK for subtasks. related_entity_* is a polymorphic soft link (a task
--    "about" a lead / leave request) with no cross-schema hard FK.
-- ===================================================================
CREATE TABLE IF NOT EXISTS task.tasks (
  id                   UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id               UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  list_id              UUID    REFERENCES task.task_lists(id) ON DELETE SET NULL,
  title                TEXT    NOT NULL,
  description          TEXT,
  assignee_id          UUID    REFERENCES iam.users(id) ON DELETE SET NULL,
  due_at               TIMESTAMPTZ,
  priority_id          UUID    REFERENCES task.task_priorities(id) ON DELETE RESTRICT,
  status_id            UUID    NOT NULL REFERENCES task.task_statuses(id) ON DELETE RESTRICT,
  parent_task_id       UUID    REFERENCES task.tasks(id) ON DELETE SET NULL,
  related_entity_type  TEXT,
  related_entity_id    UUID,
  tags                 TEXT[]  NOT NULL DEFAULT '{}',
  completed_at         TIMESTAMPTZ,
  -- RFC 5545 RRULE column only; recurrence expansion is a later increment.
  recurrence_rule      TEXT,
  is_active            BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
  deleted_at           TIMESTAMPTZ,
  deleted_by           UUID,
  created_by           UUID,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT chk_tasks_active_deleted   CHECK (NOT (is_active AND is_deleted)),
  CONSTRAINT chk_tasks_not_self_parent  CHECK (parent_task_id IS NULL OR parent_task_id <> id),
  -- related_entity_type and _id are set together or not at all.
  CONSTRAINT chk_tasks_related_entity
    CHECK ((related_entity_type IS NULL) = (related_entity_id IS NULL))
);


-- ===================================================================
-- 4. task.task_status_log — append-only (mirrors hr.leave_request_status_log)
--    SELECT-only for app_user (org scope) + tenant_admin (tenant scope);
--    INSERT only via the SECURITY DEFINER trigger above.
-- ===================================================================
CREATE TABLE IF NOT EXISTS task.task_status_log (
  id            UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id        UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  task_id       UUID    NOT NULL REFERENCES task.tasks(id)           ON DELETE CASCADE,
  changed_by_id UUID    REFERENCES iam.users(id)                     ON DELETE SET NULL,
  old_status_id UUID    REFERENCES task.task_statuses(id)            ON DELETE RESTRICT,
  new_status_id UUID    NOT NULL REFERENCES task.task_statuses(id)   ON DELETE RESTRICT,
  note          TEXT,
  changed_at    TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);


-- ===================================================================
-- 5. task.task_comments — append-only comment thread (§4.5)
--    app_user SELECT + INSERT (own author rows); NO UPDATE/DELETE for non-service
--    (author-delete can come in a later increment). RLS org/tenant isolation.
-- ===================================================================
CREATE TABLE IF NOT EXISTS task.task_comments (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  org_id      UUID    NOT NULL REFERENCES entity.organizations(id) ON DELETE RESTRICT,
  task_id     UUID    NOT NULL REFERENCES task.tasks(id)           ON DELETE CASCADE,
  user_id     UUID    NOT NULL REFERENCES iam.users(id)            ON DELETE RESTRICT,
  body        TEXT    NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);


-- ===================================================================
-- PER-PRODUCT ROLE CATALOGS  (global reference data, no RLS — same
-- management model as hr.employment_types / lms.lead_stage). Each product
-- owns its own rank scale; ranks are only comparable WITHIN a product.
-- ===================================================================

-- lms.roles / hr.roles / task.roles are tenant-scoped (historically added
-- via 22_tenant-scope-lookups.sql ALTER; folded directly into the CREATE
-- TABLE here). No un-scoped seed INSERT: per-tenant default rows are
-- provisioned by entity.seed_tenant_defaults() (05_catalogs.sql) at
-- tenant-creation time, not at DDL time (no tenant exists yet when this
-- script runs).
CREATE TABLE IF NOT EXISTS lms.roles (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,   -- machine key, stable
  label       TEXT    NOT NULL,
  description TEXT,
  rank        INT     NOT NULL DEFAULT 0
                      CONSTRAINT chk_lms_roles_rank CHECK (rank >= 0 AND rank <= 100),
  sort_order  INT     NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_lms_roles_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS hr.roles (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  rank        INT     NOT NULL DEFAULT 0
                      CONSTRAINT chk_hr_roles_rank CHECK (rank >= 0 AND rank <= 100),
  sort_order  INT     NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_hr_roles_tenant_name UNIQUE (tenant_id, name)
);

CREATE TABLE IF NOT EXISTS task.roles (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  name        TEXT    NOT NULL,
  label       TEXT    NOT NULL,
  description TEXT,
  rank        INT     NOT NULL DEFAULT 0
                      CONSTRAINT chk_task_roles_rank CHECK (rank >= 0 AND rank <= 100),
  sort_order  INT     NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_task_roles_tenant_name UNIQUE (tenant_id, name)
);


-- ===================================================================
-- PER-PRODUCT MEMBER_ROLES  (the (user, product, role) grant).
-- Org-grained (preserves multi-org users), tenant-isolated via RLS.
-- Shape and grant model mirror iam.user_org_mapping.
-- ===================================================================

-- ── lms.member_roles ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lms.member_roles (
  user_id    UUID        NOT NULL REFERENCES iam.users(id)            ON DELETE CASCADE,
  org_id     UUID        NOT NULL REFERENCES entity.organizations(id) ON DELETE CASCADE,
  tenant_id  UUID        NOT NULL REFERENCES entity.tenants(id)       ON DELETE CASCADE,
  role_id    UUID        NOT NULL REFERENCES lms.roles(id)            ON DELETE RESTRICT,
  is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
  granted_by UUID        REFERENCES iam.users(id)                     ON DELETE SET NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  PRIMARY KEY (user_id, org_id)
);

-- ── hr.member_roles ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS hr.member_roles (
  user_id    UUID        NOT NULL REFERENCES iam.users(id)            ON DELETE CASCADE,
  org_id     UUID        NOT NULL REFERENCES entity.organizations(id) ON DELETE CASCADE,
  tenant_id  UUID        NOT NULL REFERENCES entity.tenants(id)       ON DELETE CASCADE,
  role_id    UUID        NOT NULL REFERENCES hr.roles(id)             ON DELETE RESTRICT,
  is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
  granted_by UUID        REFERENCES iam.users(id)                     ON DELETE SET NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  PRIMARY KEY (user_id, org_id)
);

-- ── task.member_roles ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS task.member_roles (
  user_id    UUID        NOT NULL REFERENCES iam.users(id)            ON DELETE CASCADE,
  org_id     UUID        NOT NULL REFERENCES entity.organizations(id) ON DELETE CASCADE,
  tenant_id  UUID        NOT NULL REFERENCES entity.tenants(id)       ON DELETE CASCADE,
  role_id    UUID        NOT NULL REFERENCES task.roles(id)           ON DELETE RESTRICT,
  is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
  granted_by UUID        REFERENCES iam.users(id)                     ON DELETE SET NULL,
  granted_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  PRIMARY KEY (user_id, org_id)
);

-- ═══════════════════════════════════════════════════════════════════
-- 1. entity.catalog_defaults — immutable, versioned default rows
--    One table for every catalog. The core lookup shape (name/label/
--    description/sort_order/is_active) is shared; the few per-catalog
--    extras live in dedicated NULLABLE columns (is_terminal → task
--    statuses, is_paid → leave types, rank → roles). Never UPDATE an
--    existing (catalog_key, version) row set — ship a new version.
-- ═══════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS entity.catalog_defaults (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  catalog_key TEXT    NOT NULL,          -- schema-qualified target, e.g. 'task.task_statuses'
  product     TEXT    NOT NULL,          -- owning product (lms|leave|attendance|tasks)
  version     INT     NOT NULL,          -- catalog version this row belongs to
  name        TEXT    NOT NULL,          -- machine key (stable) copied verbatim into the tenant row
  label       TEXT    NOT NULL,
  description TEXT,
  sort_order  INT     NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE,
  is_terminal BOOLEAN,                   -- task.task_statuses only
  is_paid     BOOLEAN,                   -- hr.leave_types only
  rank        INT,                       -- *.roles only
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  CONSTRAINT uq_catalog_defaults_key_version_name UNIQUE (catalog_key, version, name)
);


-- ═══════════════════════════════════════════════════════════════════
-- 2. entity.catalog_versions — the "current" version + module gating
--    per catalog. Editing a catalog for FUTURE tenants = add rows to
--    catalog_defaults at version N+1 and bump current_version here.
-- ═══════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS entity.catalog_versions (
  catalog_key     TEXT    PRIMARY KEY,       -- schema-qualified target table
  product         TEXT    NOT NULL,
  modules         TEXT[]  NOT NULL,          -- seed if the tenant has ANY of these active modules
  current_version INT     NOT NULL,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP()
);


-- ═══════════════════════════════════════════════════════════════════
-- 3. entity.tenant_catalog_versions — per-tenant provisioning record.
--    Tenant-scoped: RLS mirrors entity.tenant_modules (SELECT-only for
--    subject roles; only root_service writes, via the seeder functions).
-- ═══════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS entity.tenant_catalog_versions (
  id          UUID    PRIMARY KEY DEFAULT public.gen_uuidv7(),
  tenant_id   UUID    NOT NULL REFERENCES entity.tenants(id) ON DELETE CASCADE,
  catalog_key TEXT    NOT NULL,
  version     INT     NOT NULL,
  seeded_at   TIMESTAMPTZ NOT NULL DEFAULT CLOCK_TIMESTAMP(),
  reset_at    TIMESTAMPTZ,
  CONSTRAINT uq_tenant_catalog_versions_tenant_key UNIQUE (tenant_id, catalog_key)
);

COMMIT;
