-- ===================================================================
-- 04_functions_triggers.sql
--
-- Business-rule, resolver and audit functions, the tenant provisioning
-- functions, and every trigger. plpgsql bodies are late-bound so table
-- order does not matter here, but the tables must exist for CREATE TRIGGER.
--
-- Generated by the db_scripts consolidation. Fresh-install only:
-- there is no in-place upgrade path, no ALTER-after-the-fact section,
-- and no _migrations/ folder. Schema changes are made in the
-- CREATE statement itself and the database is rebuilt.
-- ===================================================================

BEGIN;

DROP TRIGGER IF EXISTS trg_tenants_updated_at   ON entity.tenants;
CREATE TRIGGER trg_tenants_updated_at
  BEFORE UPDATE ON entity.tenants FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_tenants_soft_delete  ON entity.tenants;
CREATE TRIGGER trg_tenants_soft_delete
  BEFORE DELETE ON entity.tenants FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_organizations_updated_at  ON entity.organizations;
CREATE TRIGGER trg_organizations_updated_at
  BEFORE UPDATE ON entity.organizations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_organizations_soft_delete ON entity.organizations;
CREATE TRIGGER trg_organizations_soft_delete
  BEFORE DELETE ON entity.organizations FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_iam_departments_updated_at     ON iam.departments;
CREATE TRIGGER trg_iam_departments_updated_at
  BEFORE UPDATE ON iam.departments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS trg_iam_departments_soft_delete    ON iam.departments;
CREATE TRIGGER trg_iam_departments_soft_delete
  BEFORE DELETE ON iam.departments FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();
DROP TRIGGER IF EXISTS trg_iam_departments_set_created_by ON iam.departments;
CREATE TRIGGER trg_iam_departments_set_created_by
  BEFORE INSERT ON iam.departments FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_iam_capabilities_updated_at ON iam.capabilities;
CREATE TRIGGER trg_iam_capabilities_updated_at
  BEFORE UPDATE ON iam.capabilities FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_iam_role_capabilities_updated_at ON iam.role_capabilities;
CREATE TRIGGER trg_iam_role_capabilities_updated_at
  BEFORE UPDATE ON iam.role_capabilities FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
DROP TRIGGER IF EXISTS trg_iam_role_capabilities_set_created_by ON iam.role_capabilities;
CREATE TRIGGER trg_iam_role_capabilities_set_created_by
  BEFORE INSERT ON iam.role_capabilities FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

-- ── CACHE INVALIDATION (Tier C3) ──────────────────────────────────
-- Services load the matrix once at startup and hold it in memory; this is what
-- tells them to drop it. STATEMENT-level on purpose: a bulk re-grant fires one
-- notification, not one per row. The payload names the changed table only —
-- listeners invalidate everything and reload lazily, which is cheap (a few
-- hundred rows) and immune to getting the affected-tenant set wrong.
CREATE OR REPLACE FUNCTION iam.fn_notify_capability_change()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_notify('rbac_capabilities_changed',
    json_build_object('table', TG_TABLE_NAME, 'op', TG_OP, 'ts', EXTRACT(EPOCH FROM CLOCK_TIMESTAMP()))::text);
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS trg_notify_capability_change ON iam.role_capabilities;
CREATE TRIGGER trg_notify_capability_change
  AFTER INSERT OR UPDATE OR DELETE ON iam.role_capabilities
  FOR EACH STATEMENT EXECUTE FUNCTION iam.fn_notify_capability_change();
DROP TRIGGER IF EXISTS trg_notify_capability_change ON iam.capabilities;
CREATE TRIGGER trg_notify_capability_change
  AFTER INSERT OR UPDATE OR DELETE ON iam.capabilities
  FOR EACH STATEMENT EXECUTE FUNCTION iam.fn_notify_capability_change();
-- A role rename / re-rank changes what the matrix resolves to, so it invalidates too.
DROP TRIGGER IF EXISTS trg_notify_capability_change ON iam.user_roles;
CREATE TRIGGER trg_notify_capability_change
  AFTER INSERT OR UPDATE OR DELETE ON iam.user_roles
  FOR EACH STATEMENT EXECUTE FUNCTION iam.fn_notify_capability_change();

DROP TRIGGER IF EXISTS trg_users_updated_at       ON iam.users;
CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON iam.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_users_soft_delete      ON iam.users;
CREATE TRIGGER trg_users_soft_delete
  BEFORE DELETE ON iam.users FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

-- platform_role is a denormalisation of role_id, not an independently-set
-- column. Every writer that forgot to set it (seed script 08, identity-service's
-- user create/update) left it NULL, and the auth path reads NULL as 'member' —
-- so a super_admin silently authenticated with member rank and every
-- platform-tier gate (lookup-admin's whole surface) returned 403. Deriving it
-- here makes that impossible: the column is now maintained by the database, and
-- callers may only override it with an explicit non-NULL value.
CREATE OR REPLACE FUNCTION iam.set_user_platform_role()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_derived TEXT;
BEGIN
  IF NEW.role_id IS NULL THEN
    NEW.platform_role := COALESCE(NEW.platform_role, 'member');
    RETURN NEW;
  END IF;

  SELECT CASE ur.name
           WHEN 'super_admin'  THEN 'super_admin'
           WHEN 'tenant_admin' THEN 'tenant_admin'
           WHEN 'org_admin'    THEN 'org_admin'
           ELSE 'member'
         END
    INTO v_derived
  FROM iam.user_roles ur WHERE ur.id = NEW.role_id;

  -- On INSERT an explicit value wins (lets an operator pin a platform tier that
  -- the role name does not imply); on a role_id change the derived value wins,
  -- otherwise a demotion would leave the old tier behind.
  IF TG_OP = 'UPDATE' AND NEW.role_id IS DISTINCT FROM OLD.role_id THEN
    NEW.platform_role := COALESCE(v_derived, 'member');
  ELSE
    NEW.platform_role := COALESCE(NEW.platform_role, v_derived, 'member');
  END IF;

  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_02_users_platform_role ON iam.users;
CREATE TRIGGER trg_02_users_platform_role
  BEFORE INSERT OR UPDATE OF role_id, platform_role ON iam.users
  FOR EACH ROW EXECUTE FUNCTION iam.set_user_platform_role();

DROP TRIGGER IF EXISTS trg_00_users_set_org_id    ON iam.users;
CREATE TRIGGER trg_00_users_set_org_id
  BEFORE INSERT ON iam.users FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_users_set_created_by ON iam.users;
CREATE TRIGGER trg_01_users_set_created_by
  BEFORE INSERT ON iam.users FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_user_org_mapping_updated_at ON iam.user_org_mapping;
CREATE TRIGGER trg_user_org_mapping_updated_at
  BEFORE UPDATE ON iam.user_org_mapping
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── RLS HELPER FUNCTIONS (SECURITY DEFINER) ───────────────────────
-- These bypass RLS on iam.user_org_mapping so they can be used safely
-- inside RLS policies on OTHER tables without recursive infinite loops.

DROP FUNCTION IF EXISTS iam.fn_user_active_orgs(UUID) CASCADE;
CREATE FUNCTION iam.fn_user_active_orgs(p_user_id UUID)
RETURNS UUID[] LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT ARRAY(SELECT org_id FROM iam.user_org_mapping WHERE user_id = p_user_id AND is_active)
$$;

DROP FUNCTION IF EXISTS iam.fn_org_active_users(UUID) CASCADE;
CREATE FUNCTION iam.fn_org_active_users(p_org_id UUID)
RETURNS UUID[] LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT ARRAY(SELECT user_id FROM iam.user_org_mapping WHERE org_id = p_org_id AND is_active)
$$;

CREATE OR REPLACE FUNCTION iam.fn_user_org_rank(p_user_id UUID, p_org_id UUID)
RETURNS INT LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE v_rank INT;
BEGIN
  SELECT ur.rank INTO v_rank
  FROM iam.user_org_mapping uom
  JOIN iam.user_roles ur ON ur.id = uom.role_id
  WHERE uom.user_id = p_user_id AND uom.org_id = p_org_id AND uom.is_active;
  RETURN COALESCE(v_rank, -1);
END; $$;

DROP TRIGGER IF EXISTS trg_ad_campaigns_updated_at    ON marketing.ad_campaigns;
CREATE TRIGGER trg_ad_campaigns_updated_at
  BEFORE UPDATE ON marketing.ad_campaigns FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_ad_campaigns_soft_delete   ON marketing.ad_campaigns;
CREATE TRIGGER trg_ad_campaigns_soft_delete
  BEFORE DELETE ON marketing.ad_campaigns FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_ad_campaigns_set_org_id ON marketing.ad_campaigns;
CREATE TRIGGER trg_00_ad_campaigns_set_org_id
  BEFORE INSERT ON marketing.ad_campaigns FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_ad_campaigns_set_created_by ON marketing.ad_campaigns;
CREATE TRIGGER trg_01_ad_campaigns_set_created_by
  BEFORE INSERT ON marketing.ad_campaigns FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_marketing_leads_updated_at     ON lms.marketing_leads;
CREATE TRIGGER trg_marketing_leads_updated_at
  BEFORE UPDATE ON lms.marketing_leads FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_marketing_leads_soft_delete    ON lms.marketing_leads;
CREATE TRIGGER trg_marketing_leads_soft_delete
  BEFORE DELETE ON lms.marketing_leads FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_marketing_leads_set_org_id  ON lms.marketing_leads;
CREATE TRIGGER trg_00_marketing_leads_set_org_id
  BEFORE INSERT ON lms.marketing_leads FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_marketing_leads_set_created_by ON lms.marketing_leads;
CREATE TRIGGER trg_01_marketing_leads_set_created_by
  BEFORE INSERT ON lms.marketing_leads FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_lead_links_updated_at ON lms.lead_links;
CREATE TRIGGER trg_lead_links_updated_at
  BEFORE UPDATE ON lms.lead_links FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_api_clients_updated_at ON iam.api_clients;
CREATE TRIGGER trg_api_clients_updated_at
  BEFORE UPDATE ON iam.api_clients FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_lead_interactions_soft_delete        ON lms.lead_interactions;
CREATE TRIGGER trg_lead_interactions_soft_delete
  BEFORE DELETE ON lms.lead_interactions FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_lead_interactions_set_org_id      ON lms.lead_interactions;
CREATE TRIGGER trg_00_lead_interactions_set_org_id
  BEFORE INSERT ON lms.lead_interactions FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_lead_interactions_set_created_by  ON lms.lead_interactions;
CREATE TRIGGER trg_01_lead_interactions_set_created_by
  BEFORE INSERT ON lms.lead_interactions FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_lead_follow_ups_updated_at        ON lms.lead_follow_ups;
CREATE TRIGGER trg_lead_follow_ups_updated_at
  BEFORE UPDATE ON lms.lead_follow_ups FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_lead_follow_ups_soft_delete       ON lms.lead_follow_ups;
CREATE TRIGGER trg_lead_follow_ups_soft_delete
  BEFORE DELETE ON lms.lead_follow_ups FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_lead_follow_ups_set_org_id     ON lms.lead_follow_ups;
CREATE TRIGGER trg_00_lead_follow_ups_set_org_id
  BEFORE INSERT ON lms.lead_follow_ups FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_lead_follow_ups_set_created_by ON lms.lead_follow_ups;
CREATE TRIGGER trg_01_lead_follow_ups_set_created_by
  BEFORE INSERT ON lms.lead_follow_ups FOR EACH ROW EXECUTE FUNCTION public.set_created_by();
DROP FUNCTION IF EXISTS audit.fn_detect_password_spray(INT, INT);

CREATE OR REPLACE FUNCTION audit.fn_detect_password_spray(
  p_window_minutes        INT DEFAULT 15,
  p_min_distinct_accounts INT DEFAULT 10
)
RETURNS TABLE (
  org_id                 UUID,
  distinct_accounts      BIGINT,
  total_failures         BIGINT,
  failures_per_account   NUMERIC,
  first_seen             TIMESTAMPTZ,
  last_seen              TIMESTAMPTZ,
  sample_targets         TEXT[]
)
LANGUAGE sql STABLE AS $spray$
  SELECT
    a.org_id,
    COUNT(DISTINCT COALESCE(a.meta->>'identifier', a.meta->>'email'))  AS distinct_accounts,
    COUNT(*)                                                           AS total_failures,
    ROUND(COUNT(*)::numeric
          / NULLIF(COUNT(DISTINCT COALESCE(a.meta->>'identifier',
                                           a.meta->>'email')), 0), 2)  AS failures_per_account,
    MIN(a.created_at)                                                  AS first_seen,
    MAX(a.created_at)                                                  AS last_seen,
    (ARRAY_AGG(DISTINCT COALESCE(a.meta->>'identifier',
                                 a.meta->>'email')))[1:5]              AS sample_targets
  FROM audit.activities a
  WHERE a.action_type = 'login_failure'
    AND a.created_at >= CLOCK_TIMESTAMP() - make_interval(mins => p_window_minutes)
    AND COALESCE(a.meta->>'identifier', a.meta->>'email') IS NOT NULL
  GROUP BY a.org_id
  HAVING COUNT(DISTINCT COALESCE(a.meta->>'identifier',
                                 a.meta->>'email')) >= p_min_distinct_accounts
  ORDER BY COUNT(DISTINCT COALESCE(a.meta->>'identifier',
                                   a.meta->>'email')) DESC;
$spray$;

COMMENT ON FUNCTION audit.fn_detect_password_spray(INT, INT) IS
  'Password-spray detector: orgs where many DISTINCT accounts failed login in a short window. Low failures_per_account (~1-2) with high distinct_accounts is the spray signature; a high ratio is ordinary brute force, already handled by account lockout.';

DROP TRIGGER IF EXISTS trg_message_templates_updated_at ON comms.message_templates;
CREATE TRIGGER trg_message_templates_updated_at
  BEFORE UPDATE ON comms.message_templates
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_message_templates_soft_delete ON comms.message_templates;
CREATE TRIGGER trg_message_templates_soft_delete
  BEFORE DELETE ON comms.message_templates
  FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();


-- ===================================================================
-- BUSINESS RULE TRIGGER FUNCTIONS
-- ===================================================================

-- Enforces outcome_id ↔ stage_id consistency on lms.marketing_leads.
-- On stage change: auto-nulls outcome when new stage has no outcomes or
--   supplied outcome doesn't match the new stage.
-- Validates requires_comment when outcome.requires_comment = TRUE.
CREATE OR REPLACE FUNCTION lms.check_lead_stage_outcome()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_outcome_stage_id  UUID;
  v_outcome_count     INT;
  v_requires_comment  BOOLEAN;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.stage_id IS DISTINCT FROM OLD.stage_id THEN
    SELECT COUNT(*) INTO v_outcome_count
    FROM lms.lead_stage_outcome WHERE stage_id = NEW.stage_id;

    IF v_outcome_count = 0 THEN
      NEW.outcome_id      := NULL;
      NEW.outcome_comment := NULL;
    ELSIF NEW.outcome_id IS NOT NULL THEN
      IF NOT EXISTS (
        SELECT 1 FROM lms.lead_stage_outcome
        WHERE id = NEW.outcome_id AND stage_id = NEW.stage_id
      ) THEN
        NEW.outcome_id      := NULL;
        NEW.outcome_comment := NULL;
      END IF;
    END IF;
  ELSIF NEW.outcome_id IS NOT NULL THEN
    SELECT stage_id INTO v_outcome_stage_id
    FROM lms.lead_stage_outcome WHERE id = NEW.outcome_id;

    IF v_outcome_stage_id IS DISTINCT FROM NEW.stage_id THEN
      RAISE EXCEPTION
        'outcome_id % does not belong to stage_id %. Cross-stage outcome selection is not allowed.',
        NEW.outcome_id, NEW.stage_id;
    END IF;
  END IF;

  IF NEW.outcome_id IS NOT NULL THEN
    SELECT requires_comment INTO v_requires_comment
    FROM lms.lead_stage_outcome WHERE id = NEW.outcome_id;

    IF v_requires_comment AND (NEW.outcome_comment IS NULL OR NEW.outcome_comment = '') THEN
      RAISE EXCEPTION
        'outcome_comment is required for this outcome (requires_comment = TRUE). Please provide a comment describing the reason.';
    END IF;
  ELSE
    NEW.outcome_comment := NULL;
  END IF;

  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_lead_stage_outcome_check ON lms.marketing_leads;
CREATE TRIGGER trg_lead_stage_outcome_check
  BEFORE INSERT OR UPDATE OF stage_id, outcome_id, outcome_comment ON lms.marketing_leads
  FOR EACH ROW EXECUTE FUNCTION lms.check_lead_stage_outcome();

-- Enforces completed_at ↔ status='completed' invariant on follow-ups.
CREATE OR REPLACE FUNCTION lms.check_follow_up_completion()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_status TEXT;
BEGIN
  SELECT name INTO v_status FROM lms.follow_up_statuses WHERE id = NEW.status_id;
  IF v_status = 'completed' AND NEW.completed_at IS NULL THEN
    RAISE EXCEPTION 'completed_at must be set when follow_up status is ''completed''.';
  END IF;
  IF v_status <> 'completed' AND NEW.completed_at IS NOT NULL THEN
    RAISE EXCEPTION 'completed_at must be NULL when follow_up status is ''%'' (not ''completed'').', v_status;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_follow_up_completion_check ON lms.lead_follow_ups;
CREATE TRIGGER trg_follow_up_completion_check
  BEFORE INSERT OR UPDATE OF status_id, completed_at ON lms.lead_follow_ups
  FOR EACH ROW EXECUTE FUNCTION lms.check_follow_up_completion();

-- ── UPDATED FK SCOPE CHECKS ───────────────────────────────────────
-- Now validate via iam.fn_actor_can_act_in_org so multi-org iam.users (whose home
-- org_id differs from the working org) are not incorrectly rejected, and platform/
-- tenant admins acting cross-org (Issue #3) are accepted rather than 500-ing.

CREATE OR REPLACE FUNCTION lms.check_lead_fk_org_scope()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.campaign_id IS NOT NULL THEN
    PERFORM 1 FROM marketing.ad_campaigns
    WHERE id = NEW.campaign_id AND org_id = NEW.org_id AND NOT is_deleted;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'campaign_id % does not belong to org % or has been deleted.',
        NEW.campaign_id, NEW.org_id;
    END IF;
  END IF;
  IF NEW.assigned_user_id IS NOT NULL THEN
    IF NOT iam.fn_actor_can_act_in_org(NEW.assigned_user_id, NEW.org_id) THEN
      RAISE EXCEPTION 'assigned_user_id % has no active mapping to org % or has been deleted.',
        NEW.assigned_user_id, NEW.org_id;
    END IF;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_marketing_leads_fk_scope ON lms.marketing_leads;
CREATE TRIGGER trg_marketing_leads_fk_scope
  BEFORE INSERT OR UPDATE OF org_id, campaign_id, assigned_user_id ON lms.marketing_leads
  FOR EACH ROW EXECUTE FUNCTION lms.check_lead_fk_org_scope();

CREATE OR REPLACE FUNCTION lms.check_interaction_fk_org_scope()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM 1 FROM lms.marketing_leads
  WHERE id = NEW.lead_id AND org_id = NEW.org_id AND NOT is_deleted;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'lead_id % does not belong to org % or has been deleted.',
      NEW.lead_id, NEW.org_id;
  END IF;
  IF NOT iam.fn_actor_can_act_in_org(NEW.user_id, NEW.org_id) THEN
    RAISE EXCEPTION 'user_id % has no active mapping to org % or has been deleted.',
      NEW.user_id, NEW.org_id;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_lead_interactions_fk_scope ON lms.lead_interactions;
CREATE TRIGGER trg_lead_interactions_fk_scope
  BEFORE INSERT OR UPDATE OF org_id, lead_id, user_id ON lms.lead_interactions
  FOR EACH ROW EXECUTE FUNCTION lms.check_interaction_fk_org_scope();

CREATE OR REPLACE FUNCTION lms.check_follow_up_fk_org_scope()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM 1 FROM lms.marketing_leads
  WHERE id = NEW.lead_id AND org_id = NEW.org_id AND NOT is_deleted;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'lead_id % does not belong to org % or has been deleted.',
      NEW.lead_id, NEW.org_id;
  END IF;
  IF NOT iam.fn_actor_can_act_in_org(NEW.assigned_user_id, NEW.org_id) THEN
    RAISE EXCEPTION 'assigned_user_id % has no active mapping to org % or has been deleted.',
      NEW.assigned_user_id, NEW.org_id;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_lead_follow_ups_fk_scope ON lms.lead_follow_ups;
CREATE TRIGGER trg_lead_follow_ups_fk_scope
  BEFORE INSERT OR UPDATE OF org_id, lead_id, assigned_user_id ON lms.lead_follow_ups
  FOR EACH ROW EXECUTE FUNCTION lms.check_follow_up_fk_org_scope();

-- Set lms.lead_follow_ups.status_id to 'pending' on INSERT when not supplied.
CREATE OR REPLACE FUNCTION lms.set_default_follow_up_status()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.status_id IS NULL THEN
    SELECT id INTO NEW.status_id FROM lms.follow_up_statuses WHERE name = 'pending' LIMIT 1;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_lead_follow_ups_default_status ON lms.lead_follow_ups;
CREATE TRIGGER trg_lead_follow_ups_default_status
  BEFORE INSERT ON lms.lead_follow_ups FOR EACH ROW EXECUTE FUNCTION lms.set_default_follow_up_status();

-- Auto-transition status when completed_at is set or cleared.
CREATE OR REPLACE FUNCTION lms.sync_follow_up_status()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.completed_at IS NOT NULL AND OLD.completed_at IS NULL THEN
    SELECT id INTO NEW.status_id FROM lms.follow_up_statuses WHERE name = 'completed' LIMIT 1;
  ELSIF NEW.completed_at IS NULL AND OLD.completed_at IS NOT NULL THEN
    SELECT id INTO NEW.status_id FROM lms.follow_up_statuses WHERE name = 'pending' LIMIT 1;
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_lead_follow_ups_sync_status ON lms.lead_follow_ups;
CREATE TRIGGER trg_lead_follow_ups_sync_status
  BEFORE UPDATE OF completed_at ON lms.lead_follow_ups
  FOR EACH ROW EXECUTE FUNCTION lms.sync_follow_up_status();

-- ===================================================================
-- USER HIERARCHY FUNCTIONS & TRIGGERS
-- ===================================================================

-- Prevents circular manager_id chains (cycle detection).
CREATE OR REPLACE FUNCTION iam.check_user_hierarchy_no_cycle()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_cursor  UUID;
  v_visited UUID[] := ARRAY[NEW.id];
BEGIN
  IF NEW.manager_id IS NULL THEN RETURN NEW; END IF;
  v_cursor := NEW.manager_id;
  LOOP
    IF v_cursor = ANY(v_visited) THEN
      RAISE EXCEPTION
        'Circular reporting chain detected: setting manager_id = % on user % would create a cycle. Chain visited: %',
        NEW.manager_id, NEW.id, v_visited;
    END IF;
    v_visited := v_visited || v_cursor;
    SELECT manager_id INTO v_cursor FROM iam.users WHERE id = v_cursor;
    EXIT WHEN v_cursor IS NULL;
  END LOOP;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_user_hierarchy_no_cycle ON iam.users;
CREATE TRIGGER trg_user_hierarchy_no_cycle
  BEFORE INSERT OR UPDATE OF manager_id ON iam.users
  FOR EACH ROW EXECUTE FUNCTION iam.check_user_hierarchy_no_cycle();

-- Write to lms.lead_assignment_log whenever assigned_user_id changes.
-- SECURITY DEFINER: app_user has only SELECT on lms.lead_assignment_log.
CREATE OR REPLACE FUNCTION lms.log_lead_assignment()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_actor  UUID;
  v_action TEXT;
BEGIN
  IF NEW.assigned_user_id IS NOT DISTINCT FROM OLD.assigned_user_id THEN RETURN NEW; END IF;
  BEGIN
    v_actor := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_actor := NULL; END;
  v_action := CASE
    WHEN OLD.assigned_user_id IS NULL AND NEW.assigned_user_id IS NOT NULL THEN 'initial'
    WHEN OLD.assigned_user_id IS NOT NULL AND NEW.assigned_user_id IS NULL  THEN 'unassigned'
    WHEN v_actor = NEW.assigned_user_id                                      THEN 'self_assigned'
    ELSE 'reassigned'
  END;
  INSERT INTO lms.lead_assignment_log
    (org_id, lead_id, assigned_by_id, assigned_to_id, action, previous_assignee_id)
  VALUES
    (NEW.org_id, NEW.id, v_actor, NEW.assigned_user_id, v_action, OLD.assigned_user_id);
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_lead_assignment_log ON lms.marketing_leads;
CREATE TRIGGER trg_lead_assignment_log
  AFTER UPDATE OF assigned_user_id ON lms.marketing_leads
  FOR EACH ROW EXECUTE FUNCTION lms.log_lead_assignment();

-- ── UPDATED iam.can_assign_to ─────────────────────────────────────────
-- Looks up role via iam.user_org_mapping instead of iam.users.org_id so that
-- multi-org iam.users are evaluated for the org they are currently working in.
CREATE OR REPLACE FUNCTION iam.can_assign_to(
  p_org_id         UUID,
  p_acting_user_id UUID,
  p_target_user_id UUID
) RETURNS BOOLEAN LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE
  v_role     TEXT;
  v_in_scope BOOLEAN;
BEGIN
  IF p_acting_user_id = p_target_user_id THEN RETURN TRUE; END IF;

  SELECT ur.name INTO v_role
  FROM iam.user_org_mapping uom
  JOIN iam.user_roles ur ON ur.id = uom.role_id
  JOIN iam.users      u  ON u.id  = uom.user_id
  WHERE uom.user_id = p_acting_user_id
    AND uom.org_id  = p_org_id
    AND uom.is_active
    AND u.is_active AND NOT u.is_deleted;

  IF v_role IS NULL THEN RETURN FALSE; END IF;
  IF v_role IN ('super_admin','tenant_admin','org_admin') THEN RETURN TRUE; END IF;

  IF v_role IN ('org_manager','org_sr_manager','senior_sales_executive') THEN
    SELECT COUNT(*) > 0 INTO v_in_scope
    FROM iam.vw_user_team_members
    WHERE manager_id = p_acting_user_id
      AND member_id  = p_target_user_id
      AND org_id     = p_org_id;
    RETURN COALESCE(v_in_scope, FALSE);
  END IF;

  RETURN FALSE;
END; $$;

-- Audit trigger for lms.marketing_leads (field-level diff on UPDATE, snapshot on DELETE).
-- SECURITY DEFINER: app_user has no INSERT on audit.marketing_leads_history.
CREATE OR REPLACE FUNCTION audit.audit_marketing_leads_changes()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  k_skip CONSTANT TEXT[] := ARRAY['updated_at','created_at','id','deleted_at','deleted_by'];
  v_diff       JSONB := '{}';
  v_old_json   JSONB;
  v_new_json   JSONB;
  v_key        TEXT;
  v_old_val    JSONB;
  v_new_val    JSONB;
  v_changed_by UUID;
BEGIN
  BEGIN
    v_changed_by := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_changed_by := NULL; END;

  IF TG_OP = 'UPDATE' THEN
    v_old_json := to_jsonb(OLD);
    v_new_json := to_jsonb(NEW);
    FOR v_key, v_new_val IN SELECT key, value FROM jsonb_each(v_new_json) LOOP
      CONTINUE WHEN v_key = ANY(k_skip);
      v_old_val := v_old_json -> v_key;
      IF v_new_val IS DISTINCT FROM v_old_val THEN
        v_diff := v_diff || jsonb_build_object(v_key, jsonb_build_object('old', v_old_val, 'new', v_new_val));
      END IF;
    END LOOP;
    IF v_diff = '{}'::jsonb THEN RETURN NEW; END IF;
    INSERT INTO audit.marketing_leads_history (lead_id, changed_by_user_id, operation, changed_fields)
    VALUES (NEW.id, v_changed_by, 'U', v_diff);
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO audit.marketing_leads_history (lead_id, changed_by_user_id, operation, changed_fields)
    VALUES (OLD.id, v_changed_by, 'D', to_jsonb(OLD));
    RETURN OLD;
  END IF;
  RETURN NULL;
END; $$;

DROP TRIGGER IF EXISTS trg_marketing_leads_audit ON lms.marketing_leads;
CREATE TRIGGER trg_marketing_leads_audit
  AFTER UPDATE OR DELETE ON lms.marketing_leads
  FOR EACH ROW EXECUTE FUNCTION audit.audit_marketing_leads_changes();

-- ── AUDIT_LOG trigger function (canonical record_id/changed_by columns only;
--    row_id/actor_id alias columns never created — see audit.audit_log above) ──
CREATE OR REPLACE FUNCTION audit.audit_row_changes() RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_old_json  JSONB;
  v_diff      JSONB := '{}';
  v_key       TEXT;
  v_old_val   JSONB;
  v_new_val   JSONB;
  v_record_id UUID;
  v_org_id    UUID;
  v_changed_by UUID;
BEGIN
  v_changed_by := NULLIF(current_setting('app.current_user_id', true), '')::uuid;

  IF TG_OP = 'UPDATE' THEN
    v_old_json := to_jsonb(OLD);
    FOR v_key IN SELECT key FROM jsonb_each(to_jsonb(NEW)) LOOP
      v_old_val := v_old_json -> v_key;
      v_new_val := to_jsonb(NEW) -> v_key;
      IF v_new_val IS DISTINCT FROM v_old_val THEN
        v_diff := v_diff || jsonb_build_object(v_key, jsonb_build_object('old', v_old_val, 'new', v_new_val));
      END IF;
    END LOOP;
    IF v_diff = '{}'::jsonb THEN RETURN NEW; END IF;
    v_record_id := (to_jsonb(NEW) ->> 'id')::uuid;
    v_org_id    := NULLIF(to_jsonb(NEW) ->> 'org_id', '')::uuid;
    INSERT INTO audit.audit_log (table_name, operation, record_id, org_id, changed_by, changed_fields, old_data, new_data)
    VALUES (TG_TABLE_NAME, 'U', v_record_id, v_org_id, v_changed_by, v_diff, v_old_json, to_jsonb(NEW));
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    v_old_json  := to_jsonb(OLD);
    v_record_id := (v_old_json ->> 'id')::uuid;
    v_org_id    := NULLIF(v_old_json ->> 'org_id', '')::uuid;
    INSERT INTO audit.audit_log (table_name, operation, record_id, org_id, changed_by, changed_fields, old_data)
    VALUES (TG_TABLE_NAME, 'D', v_record_id, v_org_id, v_changed_by, v_old_json, v_old_json);
    RETURN OLD;
  END IF;
  RETURN NULL;
END; $$;

DROP TRIGGER IF EXISTS trg_users_audit           ON iam.users;
CREATE TRIGGER trg_users_audit
  AFTER UPDATE OR DELETE ON iam.users FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_ad_campaigns_audit    ON marketing.ad_campaigns;
CREATE TRIGGER trg_ad_campaigns_audit
  AFTER UPDATE OR DELETE ON marketing.ad_campaigns FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_lead_interactions_audit ON lms.lead_interactions;
CREATE TRIGGER trg_lead_interactions_audit
  AFTER UPDATE OR DELETE ON lms.lead_interactions FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_lead_follow_ups_audit ON lms.lead_follow_ups;
CREATE TRIGGER trg_lead_follow_ups_audit
  AFTER UPDATE OR DELETE ON lms.lead_follow_ups FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

-- Lead stage transition log.
-- SECURITY DEFINER: app_user has no INSERT on lms.lead_status_log.
-- transition_note is read from app.lead_transition_note session GUC set by the API.
CREATE OR REPLACE FUNCTION lms.log_lead_stage_change()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_changed_by UUID;
  v_note       TEXT;
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF NEW.stage_id IS NOT DISTINCT FROM OLD.stage_id
       AND NEW.outcome_id IS NOT DISTINCT FROM OLD.outcome_id THEN
      RETURN NEW;
    END IF;
  END IF;
  BEGIN
    v_changed_by := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_changed_by := NULL; END;
  BEGIN
    v_note := NULLIF(current_setting('app.lead_transition_note', true), '');
  EXCEPTION WHEN OTHERS THEN v_note := NULL; END;

  INSERT INTO lms.lead_status_log (
    org_id, lead_id,
    old_stage_id, new_stage_id,
    old_outcome_id, new_outcome_id,
    assigned_user_id, changed_by_id, transition_note
  ) VALUES (
    NEW.org_id, NEW.id,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.stage_id END,
    NEW.stage_id,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.outcome_id END,
    NEW.outcome_id,
    NEW.assigned_user_id,
    v_changed_by,
    v_note
  );
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_lead_status_log  ON lms.marketing_leads;
DROP TRIGGER IF EXISTS trg_lead_stage_log   ON lms.marketing_leads;
CREATE TRIGGER trg_lead_stage_log
  AFTER INSERT OR UPDATE OF stage_id, outcome_id ON lms.marketing_leads
  FOR EACH ROW EXECUTE FUNCTION lms.log_lead_stage_change();

-- Production password rotation — run via psql with -v vars set:
--   psql ... -v LEAD_SVC_PWD=xxx -v TENANT_DASH_PWD=xxx -v ROOT_SVC_PWD=xxx ...
-- Maps to .env: DATABASE_URL / DATABASE_URL_TENANT / DATABASE_URL_SERVICE
-- ALTER ROLE lead_svc        WITH PASSWORD :'LEAD_SVC_PWD';       -- → DATABASE_URL
-- ALTER ROLE tenant_dash_svc WITH PASSWORD :'TENANT_DASH_PWD';    -- → DATABASE_URL_TENANT
-- ALTER ROLE root_service     WITH PASSWORD :'ROOT_SVC_PWD';        -- → DATABASE_URL_SERVICE
-- ALTER ROLE campaign_svc    WITH PASSWORD :'CAMPAIGN_SVC_PWD';
-- ALTER ROLE user_mgmt_svc   WITH PASSWORD :'USER_MGMT_PWD';
-- ALTER ROLE notif_svc       WITH PASSWORD :'NOTIF_SVC_PWD';
-- ALTER ROLE intake_svc      WITH PASSWORD :'INTAKE_SVC_PWD';
-- ALTER ROLE analytics_svc   WITH PASSWORD :'ANALYTICS_SVC_PWD';

-- ===================================================================
-- v1.1: MULTI-ORG RLS FIX (auto-grant triggers + updated FK checks)
-- ===================================================================

-- ── AUTO-GRANT TRIGGER 1 ──────────────────────────────────────────
-- New org added to a tenant → all existing tenant_admins in that
-- tenant automatically receive a row for the new org.
CREATE OR REPLACE FUNCTION iam.auto_grant_tenant_admins_on_new_org()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  INSERT INTO iam.user_org_mapping (user_id, org_id, role_id, is_active, granted_by)
  SELECT uom.user_id, NEW.id, uom.role_id, TRUE, NULL
  FROM iam.user_org_mapping uom
  JOIN entity.organizations    o  ON o.id  = uom.org_id
  JOIN iam.user_roles       ur ON ur.id = uom.role_id
  WHERE o.tenant_id = NEW.tenant_id
    AND ur.name     = 'tenant_admin'
    AND uom.is_active
  ON CONFLICT (user_id, org_id) DO NOTHING;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_auto_grant_tenant_admins_on_new_org ON entity.organizations;
CREATE TRIGGER trg_auto_grant_tenant_admins_on_new_org
  AFTER INSERT ON entity.organizations
  FOR EACH ROW EXECUTE FUNCTION iam.auto_grant_tenant_admins_on_new_org();

-- ── AUTO-GRANT TRIGGER 2 ──────────────────────────────────────────
-- User first granted tenant_admin in any org → they automatically
-- receive rows for all other existing orgs in the same tenant.
-- pg_trigger_depth() guard prevents recursive re-firing when this
-- function's own INSERTs trigger the same event.
CREATE OR REPLACE FUNCTION iam.auto_grant_all_orgs_on_tenant_admin()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE v_tenant_id UUID;
BEGIN
  IF pg_trigger_depth() > 1 THEN RETURN NEW; END IF;

  IF NOT EXISTS (
    SELECT 1 FROM iam.user_roles WHERE id = NEW.role_id AND name = 'tenant_admin'
  ) THEN RETURN NEW; END IF;

  SELECT tenant_id INTO v_tenant_id FROM entity.organizations WHERE id = NEW.org_id;

  INSERT INTO iam.user_org_mapping (user_id, org_id, role_id, is_active, granted_by)
  SELECT NEW.user_id, o.id, NEW.role_id, TRUE, NEW.granted_by
  FROM entity.organizations o
  WHERE o.tenant_id = v_tenant_id
    AND o.id       <> NEW.org_id
    AND NOT o.is_deleted
  ON CONFLICT (user_id, org_id) DO NOTHING;

  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_auto_grant_all_orgs_on_tenant_admin ON iam.user_org_mapping;
CREATE TRIGGER trg_auto_grant_all_orgs_on_tenant_admin
  AFTER INSERT ON iam.user_org_mapping
  FOR EACH ROW EXECUTE FUNCTION iam.auto_grant_all_orgs_on_tenant_admin();

-- ── Cross-org action authority (Issue #3) ─────────────────────────────
-- Whether p_user_id may legitimately be recorded as the acting/assigned user
-- for a write in p_org_id. Returns TRUE when the user holds an active mapping to
-- the org (the normal path — the active org a shared user has switched into) OR
-- is a platform/tenant admin who acts across orgs WITHOUT a per-org mapping:
--   • super_admin  — platform scope, any org
--   • tenant_admin — any org within their own tenant
-- This is what lets the FK-org-scope triggers accept a super_admin/tenant_admin
-- write on a cross-org (e.g. unassigned) lead instead of raising — everyone else
-- still requires the mapping, so the check stays fail-closed. SECURITY DEFINER so
-- it can read iam/entity regardless of the caller's RLS context.
CREATE OR REPLACE FUNCTION iam.fn_actor_can_act_in_org(p_user_id UUID, p_org_id UUID)
RETURNS BOOLEAN LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE
  v_role TEXT;
BEGIN
  IF p_user_id IS NULL OR p_org_id IS NULL THEN
    RETURN FALSE;
  END IF;

  -- (1) Normal path: an active mapping to the org.
  PERFORM 1
  FROM iam.user_org_mapping uom
  JOIN iam.users u ON u.id = uom.user_id
  WHERE uom.user_id = p_user_id
    AND uom.org_id  = p_org_id
    AND uom.is_active
    AND u.is_active AND NOT u.is_deleted;
  IF FOUND THEN
    RETURN TRUE;
  END IF;

  -- (2) Platform/tenant admins act across orgs without a per-org mapping.
  --     Their GLOBAL role lives on iam.users.role_id (super_admin/tenant_admin
  --     are seeded that way; see 08_seed_tenants_orgs_users.sql).
  SELECT ur.name INTO v_role
  FROM iam.users u
  JOIN iam.user_roles ur ON ur.id = u.role_id
  WHERE u.id = p_user_id AND u.is_active AND NOT u.is_deleted;

  IF v_role = 'super_admin' THEN
    RETURN TRUE;                       -- platform scope: any org
  END IF;

  IF v_role = 'tenant_admin' THEN      -- tenant scope: any org in their tenant
    RETURN (
      SELECT o_target.tenant_id
      FROM entity.organizations o_target
      WHERE o_target.id = p_org_id AND NOT o_target.is_deleted
    ) = (
      SELECT o_home.tenant_id
      FROM iam.users u2
      JOIN entity.organizations o_home ON o_home.id = u2.org_id
      WHERE u2.id = p_user_id
    );
  END IF;

  RETURN FALSE;
END; $$;

-- Tier C: the single authoritative role resolver. Returns the acting user's role
-- NAME, RANK and DEPARTMENT for an org, straight from the unified iam ladder —
-- this is what every product service now calls instead of its own
-- <product>.member_roles lookup, so page guards and services can no longer
-- disagree. SECURITY DEFINER so it bypasses RLS on iam.user_roles /
-- iam.departments (same rationale as fn_user_org_rank above).
-- rank -1 / NULL role means "no active role in this org".
CREATE OR REPLACE FUNCTION iam.fn_user_org_role(p_user_id UUID, p_org_id UUID)
RETURNS TABLE (role TEXT, rank INT, department TEXT)
LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
BEGIN
  RETURN QUERY
  SELECT ur.name::TEXT, ur.rank, d.name::TEXT
  FROM iam.user_org_mapping uom
  JOIN iam.user_roles ur      ON ur.id = uom.role_id
  LEFT JOIN iam.departments d ON d.id = ur.department_id AND NOT d.is_deleted
  WHERE uom.user_id = p_user_id AND uom.org_id = p_org_id AND uom.is_active
  LIMIT 1;

  IF NOT FOUND THEN
    RETURN QUERY SELECT NULL::TEXT, -1, NULL::TEXT;
  END IF;
END; $$;

-- Tier C3 — the effective capability matrix for one tenant, already resolved.
-- Walks the capability TREE and returns every node with a definite boolean, so a
-- caller never re-implements either rule:
--
--   precedence   tenant override > platform default > deny
--   inheritance  an ancestor that resolves FALSE prunes its whole subtree;
--                tool/page/tab additionally INHERIT the nearest ancestor grant,
--                while operation/scope always require their own explicit grant.
--
-- The asymmetry is deliberate. Nav can cascade because the operations beneath it
-- fail closed independently, so a newly added page can never grant new powers.
--
-- Effective SCOPE is not computed here: callers take the granted scope child with
-- the highest sort_order, which keeps this function a pure per-node answer.
--
-- SECURITY DEFINER for the same reason as fn_user_org_role: services read this on
-- a bare connection with no session GUCs and must not be subject to RLS while
-- doing so. The tenant is an explicit argument, taken from the verified auth context.
-- Signature changed in the tree rewrite (a `kind` column was added), and
-- CREATE OR REPLACE cannot change a function's return type — hence the DROP.
DROP FUNCTION IF EXISTS iam.fn_role_capability_matrix(UUID);
CREATE FUNCTION iam.fn_role_capability_matrix(p_tenant_id UUID)
RETURNS TABLE (role_name TEXT, capability_key TEXT, kind TEXT, parent_key TEXT, sort_order INT, granted BOOLEAN)
LANGUAGE sql STABLE SECURITY DEFINER AS $$
  WITH RECURSIVE grant_resolved AS (
    SELECT DISTINCT ON (rc.role_id, rc.capability_id)
           rc.role_id, rc.capability_id, rc.is_granted
    FROM iam.role_capabilities rc
    WHERE rc.tenant_id IS NULL OR rc.tenant_id = p_tenant_id
    ORDER BY rc.role_id, rc.capability_id, (rc.tenant_id IS NOT NULL) DESC
  ),
  walk AS (
    -- Roots are the tools. A tool is on only if explicitly granted.
    SELECT r.id AS role_id, r.name::TEXT AS role_name, c.key, c.kind, c.parent_key, c.sort_order,
           COALESCE(g.is_granted, FALSE) AS granted,
           COALESCE(g.is_granted, FALSE) AS nav_inherited
    FROM iam.user_roles r
    CROSS JOIN iam.capabilities c
    LEFT JOIN grant_resolved g ON g.role_id = r.id AND g.capability_id = c.id
    WHERE c.parent_key IS NULL AND c.is_active AND r.is_active
      AND (r.tenant_id IS NULL OR r.tenant_id = p_tenant_id)

    UNION ALL

    SELECT w.role_id, w.role_name, c.key, c.kind, c.parent_key, c.sort_order,
           CASE
             WHEN NOT w.granted THEN FALSE
             WHEN c.kind IN ('page','tab') THEN COALESCE(g.is_granted, w.nav_inherited)
             ELSE COALESCE(g.is_granted, FALSE)
           END,
           CASE WHEN c.kind IN ('page','tab')
                THEN COALESCE(g.is_granted, w.nav_inherited)
                ELSE w.nav_inherited END
    FROM walk w
    JOIN iam.capabilities c ON c.parent_key = w.key AND c.is_active
    LEFT JOIN grant_resolved g ON g.role_id = w.role_id AND g.capability_id = c.id
  )
  SELECT role_name, key::TEXT, kind::TEXT, parent_key::TEXT, sort_order, granted FROM walk;
$$;

-- Cleanup job: delete entries whose tokens have already expired
CREATE OR REPLACE FUNCTION iam.purge_expired_token_blocklist() RETURNS void
LANGUAGE sql SECURITY DEFINER AS $$
  DELETE FROM iam.token_blocklist WHERE expires_at < NOW();
$$;

DROP TRIGGER IF EXISTS trg_meta_forms_updated_at ON ext.meta_forms;
CREATE TRIGGER trg_meta_forms_updated_at
  BEFORE UPDATE ON ext.meta_forms FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_meta_capi_event_types_updated_at ON ext.meta_capi_event_types;
CREATE TRIGGER trg_meta_capi_event_types_updated_at
  BEFORE UPDATE ON ext.meta_capi_event_types FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_lead_stage_capi_event_map_updated_at ON ext.lead_stage_capi_event_map;
CREATE TRIGGER trg_lead_stage_capi_event_map_updated_at
  BEFORE UPDATE ON ext.lead_stage_capi_event_map FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_tenant_modules_updated_at ON entity.tenant_modules;
CREATE TRIGGER trg_tenant_modules_updated_at
  BEFORE UPDATE ON entity.tenant_modules FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_designations_updated_at        ON hr.designations;
CREATE TRIGGER trg_designations_updated_at
  BEFORE UPDATE ON hr.designations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_designations_soft_delete       ON hr.designations;
CREATE TRIGGER trg_designations_soft_delete
  BEFORE DELETE ON hr.designations FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_designations_set_org_id     ON hr.designations;
CREATE TRIGGER trg_00_designations_set_org_id
  BEFORE INSERT ON hr.designations FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_designations_set_created_by ON hr.designations;
CREATE TRIGGER trg_01_designations_set_created_by
  BEFORE INSERT ON hr.designations FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_designations_audit             ON hr.designations;
CREATE TRIGGER trg_designations_audit
  AFTER UPDATE OR DELETE ON hr.designations FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

-- Resolve tenant_id from the row's org_id, keeping the two consistent.
-- Runs after set_org_id (trg_00) has populated org_id from the GUC.
CREATE OR REPLACE FUNCTION hr.set_employee_profile_tenant_id()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_tenant UUID;
BEGIN
  SELECT tenant_id INTO v_tenant FROM entity.organizations WHERE id = NEW.org_id;
  IF v_tenant IS NULL THEN
    RAISE EXCEPTION 'employee_profiles: cannot resolve tenant_id for org_id %', NEW.org_id;
  END IF;
  NEW.tenant_id := v_tenant;
  RETURN NEW;
END; $$;

-- Soft-delete keyed on user_id (public.soft_delete_row assumes an `id`
-- column, which this table does not have). Mirrors its behavior otherwise.
CREATE OR REPLACE FUNCTION hr.soft_delete_employee_profile()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_user_id UUID;
BEGIN
  IF current_user = 'root_service' THEN RETURN OLD; END IF;
  BEGIN
    v_user_id := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_user_id := NULL; END;
  UPDATE hr.employee_profiles
     SET is_active = FALSE, is_deleted = TRUE, deleted_at = CLOCK_TIMESTAMP(), deleted_by = v_user_id
   WHERE user_id = OLD.user_id;
  RETURN NULL;
END; $$;

DROP TRIGGER IF EXISTS trg_employee_profiles_updated_at         ON hr.employee_profiles;
CREATE TRIGGER trg_employee_profiles_updated_at
  BEFORE UPDATE ON hr.employee_profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_employee_profiles_soft_delete        ON hr.employee_profiles;
CREATE TRIGGER trg_employee_profiles_soft_delete
  BEFORE DELETE ON hr.employee_profiles FOR EACH ROW EXECUTE FUNCTION hr.soft_delete_employee_profile();

DROP TRIGGER IF EXISTS trg_00_employee_profiles_set_org_id      ON hr.employee_profiles;
CREATE TRIGGER trg_00_employee_profiles_set_org_id
  BEFORE INSERT ON hr.employee_profiles FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_employee_profiles_set_created_by  ON hr.employee_profiles;
CREATE TRIGGER trg_01_employee_profiles_set_created_by
  BEFORE INSERT ON hr.employee_profiles FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_02_employee_profiles_set_tenant_id   ON hr.employee_profiles;
CREATE TRIGGER trg_02_employee_profiles_set_tenant_id
  BEFORE INSERT OR UPDATE ON hr.employee_profiles FOR EACH ROW EXECUTE FUNCTION hr.set_employee_profile_tenant_id();

DROP TRIGGER IF EXISTS trg_employee_profiles_audit              ON hr.employee_profiles;
CREATE TRIGGER trg_employee_profiles_audit
  AFTER UPDATE OR DELETE ON hr.employee_profiles FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_holiday_calendars_updated_at        ON hr.holiday_calendars;
CREATE TRIGGER trg_holiday_calendars_updated_at
  BEFORE UPDATE ON hr.holiday_calendars FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_holiday_calendars_soft_delete       ON hr.holiday_calendars;
CREATE TRIGGER trg_holiday_calendars_soft_delete
  BEFORE DELETE ON hr.holiday_calendars FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_holiday_calendars_set_org_id     ON hr.holiday_calendars;
CREATE TRIGGER trg_00_holiday_calendars_set_org_id
  BEFORE INSERT ON hr.holiday_calendars FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_holiday_calendars_set_created_by ON hr.holiday_calendars;
CREATE TRIGGER trg_01_holiday_calendars_set_created_by
  BEFORE INSERT ON hr.holiday_calendars FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_holiday_calendars_audit             ON hr.holiday_calendars;
CREATE TRIGGER trg_holiday_calendars_audit
  AFTER UPDATE OR DELETE ON hr.holiday_calendars FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_holidays_updated_at        ON hr.holidays;
CREATE TRIGGER trg_holidays_updated_at
  BEFORE UPDATE ON hr.holidays FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_holidays_soft_delete       ON hr.holidays;
CREATE TRIGGER trg_holidays_soft_delete
  BEFORE DELETE ON hr.holidays FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_holidays_set_org_id     ON hr.holidays;
CREATE TRIGGER trg_00_holidays_set_org_id
  BEFORE INSERT ON hr.holidays FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_holidays_set_created_by ON hr.holidays;
CREATE TRIGGER trg_01_holidays_set_created_by
  BEFORE INSERT ON hr.holidays FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_holidays_audit             ON hr.holidays;
CREATE TRIGGER trg_holidays_audit
  AFTER UPDATE OR DELETE ON hr.holidays FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_leave_policies_updated_at        ON hr.leave_policies;
CREATE TRIGGER trg_leave_policies_updated_at
  BEFORE UPDATE ON hr.leave_policies FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_leave_policies_soft_delete       ON hr.leave_policies;
CREATE TRIGGER trg_leave_policies_soft_delete
  BEFORE DELETE ON hr.leave_policies FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_01_leave_policies_set_created_by  ON hr.leave_policies;
CREATE TRIGGER trg_01_leave_policies_set_created_by
  BEFORE INSERT ON hr.leave_policies FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_leave_policies_audit             ON hr.leave_policies;
CREATE TRIGGER trg_leave_policies_audit
  AFTER UPDATE OR DELETE ON hr.leave_policies FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_hr_settings_updated_at ON hr.hr_settings;
CREATE TRIGGER trg_hr_settings_updated_at
  BEFORE UPDATE ON hr.hr_settings FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Maintain is_open from the resolved status name (pending/approved => TRUE).
CREATE OR REPLACE FUNCTION hr.set_leave_request_is_open()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_status TEXT;
BEGIN
  SELECT name INTO v_status FROM hr.leave_request_statuses WHERE id = NEW.status_id;
  NEW.is_open := (v_status IN ('pending','approved'));
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_00_leave_requests_set_org_id      ON hr.leave_requests;
CREATE TRIGGER trg_00_leave_requests_set_org_id
  BEFORE INSERT ON hr.leave_requests FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_leave_requests_set_created_by  ON hr.leave_requests;
CREATE TRIGGER trg_01_leave_requests_set_created_by
  BEFORE INSERT ON hr.leave_requests FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_02_leave_requests_set_is_open     ON hr.leave_requests;
CREATE TRIGGER trg_02_leave_requests_set_is_open
  BEFORE INSERT OR UPDATE OF status_id ON hr.leave_requests
  FOR EACH ROW EXECUTE FUNCTION hr.set_leave_request_is_open();

DROP TRIGGER IF EXISTS trg_leave_requests_updated_at         ON hr.leave_requests;
CREATE TRIGGER trg_leave_requests_updated_at
  BEFORE UPDATE ON hr.leave_requests FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_leave_requests_soft_delete        ON hr.leave_requests;
CREATE TRIGGER trg_leave_requests_soft_delete
  BEFORE DELETE ON hr.leave_requests FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_leave_requests_audit              ON hr.leave_requests;
CREATE TRIGGER trg_leave_requests_audit
  AFTER UPDATE OR DELETE ON hr.leave_requests FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

-- Status-transition log writer. SECURITY DEFINER: app_user has no INSERT on the
-- log. note is read from app.leave_transition_note session GUC set by the API.
CREATE OR REPLACE FUNCTION hr.log_leave_status_change()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_changed_by UUID;
  v_note       TEXT;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.status_id IS NOT DISTINCT FROM OLD.status_id THEN
    RETURN NEW;
  END IF;
  BEGIN
    v_changed_by := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_changed_by := NULL; END;
  BEGIN
    v_note := NULLIF(current_setting('app.leave_transition_note', true), '');
  EXCEPTION WHEN OTHERS THEN v_note := NULL; END;

  INSERT INTO hr.leave_request_status_log (
    org_id, request_id, old_status_id, new_status_id, changed_by_id, note
  ) VALUES (
    NEW.org_id, NEW.id,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.status_id END,
    NEW.status_id,
    v_changed_by,
    v_note
  );
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_leave_request_status_log ON hr.leave_requests;
CREATE TRIGGER trg_leave_request_status_log
  AFTER INSERT OR UPDATE OF status_id ON hr.leave_requests
  FOR EACH ROW EXECUTE FUNCTION hr.log_leave_status_change();

DROP TRIGGER IF EXISTS trg_00_leave_request_approvals_set_org_id ON hr.leave_request_approvals;
CREATE TRIGGER trg_00_leave_request_approvals_set_org_id
  BEFORE INSERT ON hr.leave_request_approvals FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_leave_request_approvals_audit        ON hr.leave_request_approvals;
CREATE TRIGGER trg_leave_request_approvals_audit
  AFTER UPDATE OR DELETE ON hr.leave_request_approvals FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();


-- ===================================================================
-- 6. hr.can_approve_leave — approval authority (modeled on iam.can_assign_to)
--    TRUE when the approver is in the requester's management chain, OR has
--    rank >= 980 (ANCHOR_RANK.ORG_ADMIN) in the org, OR is hr_admin in the org, OR is tenant_admin/
--    super_admin of the owning tenant. SECURITY DEFINER: reads iam.* + entity.*
--    regardless of the calling role. Never lets a user approve their own leave.
-- ===================================================================
CREATE OR REPLACE FUNCTION hr.can_approve_leave(
  p_org_id       UUID,
  p_approver_id  UUID,
  p_requester_id UUID
) RETURNS BOOLEAN LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE
  v_role     TEXT;
  v_rank     INT;
  v_in_scope BOOLEAN;
  v_tenant   UUID;
BEGIN
  IF p_approver_id = p_requester_id THEN RETURN FALSE; END IF;

  -- 1) Approver is in the requester's management subtree (walks manager_id up).
  SELECT COUNT(*) > 0 INTO v_in_scope
  FROM iam.vw_user_team_members
  WHERE manager_id = p_approver_id
    AND member_id  = p_requester_id
    AND org_id     = p_org_id;
  IF COALESCE(v_in_scope, FALSE) THEN RETURN TRUE; END IF;

  -- 2) Approver's role/rank in this org (org_admin+ => rank 980; hr_admin => 75).
  SELECT ur.name, ur.rank INTO v_role, v_rank
  FROM iam.user_org_mapping uom
  JOIN iam.user_roles ur ON ur.id = uom.role_id
  WHERE uom.user_id = p_approver_id
    AND uom.org_id  = p_org_id
    AND uom.is_active;

  IF COALESCE(v_rank, -1) >= 980 THEN RETURN TRUE; END IF;
  IF v_role = 'hr_admin'        THEN RETURN TRUE; END IF;

  -- 3) tenant_admin / super_admin of the tenant that owns the request's org.
  SELECT tenant_id INTO v_tenant FROM entity.organizations WHERE id = p_org_id;
  IF EXISTS (
    SELECT 1
    FROM iam.user_org_mapping uom
    JOIN iam.user_roles ur        ON ur.id = uom.role_id
    JOIN entity.organizations o   ON o.id  = uom.org_id
    WHERE uom.user_id = p_approver_id
      AND uom.is_active
      AND o.tenant_id = v_tenant
      AND ur.name IN ('tenant_admin','super_admin')
  ) THEN
    RETURN TRUE;
  END IF;

  RETURN FALSE;
END; $$;

DROP TRIGGER IF EXISTS trg_attendance_rules_updated_at        ON hr.attendance_rules;
CREATE TRIGGER trg_attendance_rules_updated_at
  BEFORE UPDATE ON hr.attendance_rules FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_attendance_rules_soft_delete       ON hr.attendance_rules;
CREATE TRIGGER trg_attendance_rules_soft_delete
  BEFORE DELETE ON hr.attendance_rules FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_attendance_rules_set_org_id     ON hr.attendance_rules;
CREATE TRIGGER trg_00_attendance_rules_set_org_id
  BEFORE INSERT ON hr.attendance_rules FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_attendance_rules_set_created_by ON hr.attendance_rules;
CREATE TRIGGER trg_01_attendance_rules_set_created_by
  BEFORE INSERT ON hr.attendance_rules FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_attendance_rules_audit             ON hr.attendance_rules;
CREATE TRIGGER trg_attendance_rules_audit
  AFTER UPDATE OR DELETE ON hr.attendance_rules FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_shifts_updated_at        ON hr.shifts;
CREATE TRIGGER trg_shifts_updated_at
  BEFORE UPDATE ON hr.shifts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_shifts_soft_delete       ON hr.shifts;
CREATE TRIGGER trg_shifts_soft_delete
  BEFORE DELETE ON hr.shifts FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_shifts_set_org_id     ON hr.shifts;
CREATE TRIGGER trg_00_shifts_set_org_id
  BEFORE INSERT ON hr.shifts FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_shifts_set_created_by ON hr.shifts;
CREATE TRIGGER trg_01_shifts_set_created_by
  BEFORE INSERT ON hr.shifts FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_shifts_audit             ON hr.shifts;
CREATE TRIGGER trg_shifts_audit
  AFTER UPDATE OR DELETE ON hr.shifts FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_shift_segments_updated_at        ON hr.shift_segments;
CREATE TRIGGER trg_shift_segments_updated_at
  BEFORE UPDATE ON hr.shift_segments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_shift_segments_soft_delete       ON hr.shift_segments;
CREATE TRIGGER trg_shift_segments_soft_delete
  BEFORE DELETE ON hr.shift_segments FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_shift_segments_set_org_id     ON hr.shift_segments;
CREATE TRIGGER trg_00_shift_segments_set_org_id
  BEFORE INSERT ON hr.shift_segments FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_shift_segments_set_created_by ON hr.shift_segments;
CREATE TRIGGER trg_01_shift_segments_set_created_by
  BEFORE INSERT ON hr.shift_segments FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_shift_segments_audit             ON hr.shift_segments;
CREATE TRIGGER trg_shift_segments_audit
  AFTER UPDATE OR DELETE ON hr.shift_segments FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_shift_assignments_updated_at        ON hr.shift_assignments;
CREATE TRIGGER trg_shift_assignments_updated_at
  BEFORE UPDATE ON hr.shift_assignments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_shift_assignments_soft_delete       ON hr.shift_assignments;
CREATE TRIGGER trg_shift_assignments_soft_delete
  BEFORE DELETE ON hr.shift_assignments FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_shift_assignments_set_org_id     ON hr.shift_assignments;
CREATE TRIGGER trg_00_shift_assignments_set_org_id
  BEFORE INSERT ON hr.shift_assignments FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_shift_assignments_set_created_by ON hr.shift_assignments;
CREATE TRIGGER trg_01_shift_assignments_set_created_by
  BEFORE INSERT ON hr.shift_assignments FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_shift_assignments_audit             ON hr.shift_assignments;
CREATE TRIGGER trg_shift_assignments_audit
  AFTER UPDATE OR DELETE ON hr.shift_assignments FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_attendance_days_updated_at ON hr.attendance_days;
CREATE TRIGGER trg_attendance_days_updated_at
  BEFORE UPDATE ON hr.attendance_days FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_attendance_days_audit      ON hr.attendance_days;
CREATE TRIGGER trg_attendance_days_audit
  AFTER UPDATE OR DELETE ON hr.attendance_days FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_attendance_regularizations_updated_at        ON hr.attendance_regularizations;
CREATE TRIGGER trg_attendance_regularizations_updated_at
  BEFORE UPDATE ON hr.attendance_regularizations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_attendance_regularizations_soft_delete       ON hr.attendance_regularizations;
CREATE TRIGGER trg_attendance_regularizations_soft_delete
  BEFORE DELETE ON hr.attendance_regularizations FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_attendance_regularizations_set_org_id     ON hr.attendance_regularizations;
CREATE TRIGGER trg_00_attendance_regularizations_set_org_id
  BEFORE INSERT ON hr.attendance_regularizations FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_attendance_regularizations_set_created_by ON hr.attendance_regularizations;
CREATE TRIGGER trg_01_attendance_regularizations_set_created_by
  BEFORE INSERT ON hr.attendance_regularizations FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_attendance_regularizations_audit             ON hr.attendance_regularizations;
CREATE TRIGGER trg_attendance_regularizations_audit
  AFTER UPDATE OR DELETE ON hr.attendance_regularizations FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();


-- ===================================================================
-- 7. hr.can_approve — thin authority alias over hr.can_approve_leave (§Service).
--    Rename-agnostic: the underlying function checks the management chain +
--    rank>=980 + hr_admin + tenant_admin/super_admin. Reused for attendance
--    regularization approvals so authority stays defined in exactly one place.
-- ===================================================================
CREATE OR REPLACE FUNCTION hr.can_approve(
  p_org_id       UUID,
  p_approver_id  UUID,
  p_requester_id UUID
) RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT hr.can_approve_leave(p_org_id, p_approver_id, p_requester_id);
$$;

DROP TRIGGER IF EXISTS trg_reporting_lines_updated_at        ON hr.reporting_lines;
CREATE TRIGGER trg_reporting_lines_updated_at
  BEFORE UPDATE ON hr.reporting_lines FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_reporting_lines_soft_delete       ON hr.reporting_lines;
CREATE TRIGGER trg_reporting_lines_soft_delete
  BEFORE DELETE ON hr.reporting_lines FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_reporting_lines_set_org_id     ON hr.reporting_lines;
CREATE TRIGGER trg_00_reporting_lines_set_org_id
  BEFORE INSERT ON hr.reporting_lines FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_reporting_lines_set_created_by ON hr.reporting_lines;
CREATE TRIGGER trg_01_reporting_lines_set_created_by
  BEFORE INSERT ON hr.reporting_lines FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_reporting_lines_audit             ON hr.reporting_lines;
CREATE TRIGGER trg_reporting_lines_audit
  AFTER UPDATE OR DELETE ON hr.reporting_lines FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

DROP TRIGGER IF EXISTS trg_task_lists_updated_at        ON task.task_lists;
CREATE TRIGGER trg_task_lists_updated_at
  BEFORE UPDATE ON task.task_lists FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_task_lists_soft_delete       ON task.task_lists;
CREATE TRIGGER trg_task_lists_soft_delete
  BEFORE DELETE ON task.task_lists FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_task_lists_set_org_id     ON task.task_lists;
CREATE TRIGGER trg_00_task_lists_set_org_id
  BEFORE INSERT ON task.task_lists FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_task_lists_set_created_by ON task.task_lists;
CREATE TRIGGER trg_01_task_lists_set_created_by
  BEFORE INSERT ON task.task_lists FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_task_lists_audit             ON task.task_lists;
CREATE TRIGGER trg_task_lists_audit
  AFTER UPDATE OR DELETE ON task.task_lists FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

-- completed_at ↔ status consistency (auto-managed, mirrors the intent of
-- lms.check_follow_up_completion). Sets completed_at when the task enters the
-- terminal 'done' status and clears it on any transition away from 'done'. Runs
-- BEFORE so the value lands on the same row write.
CREATE OR REPLACE FUNCTION task.set_task_completion()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE v_status TEXT;
BEGIN
  SELECT name INTO v_status FROM task.task_statuses WHERE id = NEW.status_id;
  IF v_status = 'done' THEN
    IF NEW.completed_at IS NULL THEN NEW.completed_at := CLOCK_TIMESTAMP(); END IF;
  ELSE
    NEW.completed_at := NULL;
  END IF;
  RETURN NEW;
END; $$;

-- Append-only status-transition log writer. SECURITY DEFINER: app_user has no
-- INSERT on task.task_status_log. Note is read from the app.task_transition_note
-- session GUC set by the API before the update (mirrors hr.log_leave_status_change).
CREATE OR REPLACE FUNCTION task.log_task_status_change()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY DEFINER AS $$
DECLARE
  v_changed_by UUID;
  v_note       TEXT;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.status_id IS NOT DISTINCT FROM OLD.status_id THEN
    RETURN NEW;
  END IF;
  BEGIN
    v_changed_by := NULLIF(current_setting('app.current_user_id', true), '')::uuid;
  EXCEPTION WHEN OTHERS THEN v_changed_by := NULL; END;
  BEGIN
    v_note := NULLIF(current_setting('app.task_transition_note', true), '');
  EXCEPTION WHEN OTHERS THEN v_note := NULL; END;

  INSERT INTO task.task_status_log (
    org_id, task_id, old_status_id, new_status_id, changed_by_id, note
  ) VALUES (
    NEW.org_id, NEW.id,
    CASE WHEN TG_OP = 'INSERT' THEN NULL ELSE OLD.status_id END,
    NEW.status_id,
    v_changed_by,
    v_note
  );
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_tasks_updated_at        ON task.tasks;
CREATE TRIGGER trg_tasks_updated_at
  BEFORE UPDATE ON task.tasks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_tasks_completion         ON task.tasks;
CREATE TRIGGER trg_tasks_completion
  BEFORE INSERT OR UPDATE OF status_id ON task.tasks FOR EACH ROW EXECUTE FUNCTION task.set_task_completion();

DROP TRIGGER IF EXISTS trg_tasks_soft_delete       ON task.tasks;
CREATE TRIGGER trg_tasks_soft_delete
  BEFORE DELETE ON task.tasks FOR EACH ROW EXECUTE FUNCTION public.soft_delete_row();

DROP TRIGGER IF EXISTS trg_00_tasks_set_org_id     ON task.tasks;
CREATE TRIGGER trg_00_tasks_set_org_id
  BEFORE INSERT ON task.tasks FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_01_tasks_set_created_by ON task.tasks;
CREATE TRIGGER trg_01_tasks_set_created_by
  BEFORE INSERT ON task.tasks FOR EACH ROW EXECUTE FUNCTION public.set_created_by();

DROP TRIGGER IF EXISTS trg_tasks_audit             ON task.tasks;
CREATE TRIGGER trg_tasks_audit
  AFTER UPDATE OR DELETE ON task.tasks FOR EACH ROW EXECUTE FUNCTION audit.audit_row_changes();

-- The status-log trigger inserts into this table; declared after the table exists.
DROP TRIGGER IF EXISTS trg_tasks_status_log ON task.tasks;
CREATE TRIGGER trg_tasks_status_log
  AFTER INSERT OR UPDATE OF status_id ON task.tasks
  FOR EACH ROW EXECUTE FUNCTION task.log_task_status_change();

DROP TRIGGER IF EXISTS trg_00_task_comments_set_org_id ON task.task_comments;
CREATE TRIGGER trg_00_task_comments_set_org_id
  BEFORE INSERT ON task.task_comments FOR EACH ROW EXECUTE FUNCTION public.set_org_id();

DROP TRIGGER IF EXISTS trg_00_lms_member_roles_tenant_id ON lms.member_roles;
CREATE TRIGGER trg_00_lms_member_roles_tenant_id
  BEFORE INSERT OR UPDATE ON lms.member_roles
  FOR EACH ROW EXECUTE FUNCTION public.set_member_role_tenant_id();

DROP TRIGGER IF EXISTS trg_lms_member_roles_updated_at ON lms.member_roles;
CREATE TRIGGER trg_lms_member_roles_updated_at
  BEFORE UPDATE ON lms.member_roles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_00_hr_member_roles_tenant_id ON hr.member_roles;
CREATE TRIGGER trg_00_hr_member_roles_tenant_id
  BEFORE INSERT OR UPDATE ON hr.member_roles
  FOR EACH ROW EXECUTE FUNCTION public.set_member_role_tenant_id();

DROP TRIGGER IF EXISTS trg_hr_member_roles_updated_at ON hr.member_roles;
CREATE TRIGGER trg_hr_member_roles_updated_at
  BEFORE UPDATE ON hr.member_roles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS trg_00_task_member_roles_tenant_id ON task.member_roles;
CREATE TRIGGER trg_00_task_member_roles_tenant_id
  BEFORE INSERT OR UPDATE ON task.member_roles
  FOR EACH ROW EXECUTE FUNCTION public.set_member_role_tenant_id();

DROP TRIGGER IF EXISTS trg_task_member_roles_updated_at ON task.member_roles;
CREATE TRIGGER trg_task_member_roles_updated_at
  BEFORE UPDATE ON task.member_roles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ===================================================================
-- OWN-RANK HELPERS  (SECURITY DEFINER — bypass member_roles RLS so they
-- can be called inside OTHER tables' RLS policies without recursion.
-- Mirrors iam.fn_user_org_rank. Returns -1 when the user has no active
-- grant in that product+org, which is how "no product access" is encoded.
-- ===================================================================

CREATE OR REPLACE FUNCTION lms.fn_member_rank(p_user_id UUID, p_org_id UUID)
RETURNS INT LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE v_rank INT;
BEGIN
  SELECT r.rank INTO v_rank
  FROM lms.member_roles mr
  JOIN lms.roles r ON r.id = mr.role_id
  WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active;
  RETURN COALESCE(v_rank, -1);
END; $$;

CREATE OR REPLACE FUNCTION hr.fn_member_rank(p_user_id UUID, p_org_id UUID)
RETURNS INT LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE v_rank INT;
BEGIN
  SELECT r.rank INTO v_rank
  FROM hr.member_roles mr
  JOIN hr.roles r ON r.id = mr.role_id
  WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active;
  RETURN COALESCE(v_rank, -1);
END; $$;

CREATE OR REPLACE FUNCTION task.fn_member_rank(p_user_id UUID, p_org_id UUID)
RETURNS INT LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE v_rank INT;
BEGIN
  SELECT r.rank INTO v_rank
  FROM task.member_roles mr
  JOIN task.roles r ON r.id = mr.role_id
  WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active;
  RETURN COALESCE(v_rank, -1);
END; $$;

CREATE OR REPLACE FUNCTION lms.fn_member_role(p_user_id UUID, p_org_id UUID)
RETURNS TABLE(role TEXT, rank INT) LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT r.name, r.rank
  FROM lms.member_roles mr
  JOIN lms.roles r ON r.id = mr.role_id
  WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active
  UNION ALL
  SELECT NULL::text, -1
  WHERE NOT EXISTS (
    SELECT 1 FROM lms.member_roles mr
    WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active
  )
$$;

CREATE OR REPLACE FUNCTION hr.fn_member_role(p_user_id UUID, p_org_id UUID)
RETURNS TABLE(role TEXT, rank INT) LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT r.name, r.rank
  FROM hr.member_roles mr
  JOIN hr.roles r ON r.id = mr.role_id
  WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active
  UNION ALL
  SELECT NULL::text, -1
  WHERE NOT EXISTS (
    SELECT 1 FROM hr.member_roles mr
    WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active
  )
$$;

CREATE OR REPLACE FUNCTION task.fn_member_role(p_user_id UUID, p_org_id UUID)
RETURNS TABLE(role TEXT, rank INT) LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT r.name, r.rank
  FROM task.member_roles mr
  JOIN task.roles r ON r.id = mr.role_id
  WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active
  UNION ALL
  SELECT NULL::text, -1
  WHERE NOT EXISTS (
    SELECT 1 FROM task.member_roles mr
    WHERE mr.user_id = p_user_id AND mr.org_id = p_org_id AND mr.is_active
  )
$$;

DROP TRIGGER IF EXISTS trg_catalog_versions_updated_at ON entity.catalog_versions;
CREATE TRIGGER trg_catalog_versions_updated_at BEFORE UPDATE ON entity.catalog_versions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ═══════════════════════════════════════════════════════════════════
-- 5. entity._apply_catalog_rows — shared per-catalog copy helper.
--    Copies the default rows of (p_catalog_key, p_version) into the
--    tenant's private lookup table.
--
--    p_reset = FALSE (seed): insert only rows the tenant doesn't already
--      have (ON CONFLICT DO NOTHING) — never overwrites tenant edits.
--    p_reset = TRUE (reset):  additionally restore label/description/
--      sort_order/is_active (+ the per-catalog extra) of conflicting rows
--      back to the default. The row `id` is preserved on conflict, so FKs
--      from tenant data (e.g. task.tasks.status_id) stay valid; only
--      previously hard-deleted defaults get a fresh id. Tenant-custom rows
--      (names not in the catalog) are left untouched.
--
--    Returns the number of rows inserted/updated.
-- ═══════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION entity._apply_catalog_rows(
  p_tenant_id   UUID,
  p_catalog_key TEXT,
  p_version     INT,
  p_reset       BOOLEAN
) RETURNS INT
LANGUAGE plpgsql AS $$
DECLARE v_rows INT := 0;
BEGIN
  IF p_catalog_key = 'task.task_statuses' THEN
    INSERT INTO task.task_statuses (tenant_id, name, label, description, is_terminal, sort_order, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, COALESCE(d.is_terminal, FALSE), d.sort_order, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description,
          is_terminal = EXCLUDED.is_terminal, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSIF p_catalog_key = 'task.task_priorities' THEN
    INSERT INTO task.task_priorities (tenant_id, name, label, description, sort_order, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, d.sort_order, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description,
          sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSIF p_catalog_key = 'hr.leave_types' THEN
    INSERT INTO hr.leave_types (tenant_id, name, label, description, is_paid, sort_order, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, COALESCE(d.is_paid, TRUE), d.sort_order, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description,
          is_paid = EXCLUDED.is_paid, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSIF p_catalog_key = 'hr.employment_types' THEN
    INSERT INTO hr.employment_types (tenant_id, name, label, description, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSIF p_catalog_key = 'hr.attendance_statuses' THEN
    INSERT INTO hr.attendance_statuses (tenant_id, name, label, description, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSIF p_catalog_key = 'lms.roles' THEN
    INSERT INTO lms.roles (tenant_id, name, label, description, rank, sort_order, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, COALESCE(d.rank, 0), d.sort_order, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description,
          rank = EXCLUDED.rank, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSIF p_catalog_key = 'hr.roles' THEN
    INSERT INTO hr.roles (tenant_id, name, label, description, rank, sort_order, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, COALESCE(d.rank, 0), d.sort_order, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description,
          rank = EXCLUDED.rank, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSIF p_catalog_key = 'task.roles' THEN
    INSERT INTO task.roles (tenant_id, name, label, description, rank, sort_order, is_active)
    SELECT p_tenant_id, d.name, d.label, d.description, COALESCE(d.rank, 0), d.sort_order, d.is_active
    FROM entity.catalog_defaults d
    WHERE d.catalog_key = p_catalog_key AND d.version = p_version
    ON CONFLICT (tenant_id, name) DO UPDATE
      SET label = EXCLUDED.label, description = EXCLUDED.description,
          rank = EXCLUDED.rank, sort_order = EXCLUDED.sort_order, is_active = EXCLUDED.is_active
      WHERE p_reset;

  ELSE
    RAISE EXCEPTION '_apply_catalog_rows: unknown catalog_key %', p_catalog_key;
  END IF;

  GET DIAGNOSTICS v_rows = ROW_COUNT;
  RETURN v_rows;
END; $$;


-- ═══════════════════════════════════════════════════════════════════
-- 6. entity.seed_tenant_defaults — the provisioning entry point.
--    For every catalog whose gating modules overlap the tenant's ACTIVE
--    modules and that hasn't been seeded yet, copy the current version's
--    default rows into the tenant's private tables and record the version.
--    Idempotent: catalogs already in tenant_catalog_versions are skipped,
--    so re-running provisioning never overwrites tenant customisations.
-- ═══════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION entity.seed_tenant_defaults(p_tenant_id UUID)
RETURNS TABLE(catalog_key TEXT, seeded_version INT, rows_inserted INT)
LANGUAGE plpgsql AS $$
DECLARE
  v_active TEXT[];
  cv       RECORD;
  v_rows   INT;
BEGIN
  IF p_tenant_id IS NULL THEN
    RAISE EXCEPTION 'seed_tenant_defaults: tenant id is required';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM entity.tenants WHERE id = p_tenant_id) THEN
    RAISE EXCEPTION 'seed_tenant_defaults: tenant % not found', p_tenant_id;
  END IF;

  SELECT COALESCE(array_agg(module), ARRAY[]::TEXT[]) INTO v_active
  FROM entity.tenant_modules
  WHERE tenant_id = p_tenant_id AND is_active;

  FOR cv IN SELECT c.catalog_key, c.current_version, c.modules FROM entity.catalog_versions c LOOP
    -- Only seed catalogs for LICENSED products.
    IF NOT (cv.modules && v_active) THEN CONTINUE; END IF;
    -- Never re-seed a catalog the tenant already provisioned (non-retroactive).
    IF EXISTS (
      SELECT 1 FROM entity.tenant_catalog_versions t
      WHERE t.tenant_id = p_tenant_id AND t.catalog_key = cv.catalog_key
    ) THEN CONTINUE; END IF;

    v_rows := entity._apply_catalog_rows(p_tenant_id, cv.catalog_key, cv.current_version, FALSE);

    INSERT INTO entity.tenant_catalog_versions (tenant_id, catalog_key, version)
    VALUES (p_tenant_id, cv.catalog_key, cv.current_version);

    catalog_key    := cv.catalog_key;
    seeded_version := cv.current_version;
    rows_inserted  := v_rows;
    RETURN NEXT;
  END LOOP;
END; $$;


-- ═══════════════════════════════════════════════════════════════════
-- 7. entity.reset_tenant_catalog — explicit opt-in "reset to defaults".
--    Restores one catalog for one tenant back to a default version
--    (defaults to the current version). Re-adds deleted defaults and
--    restores default label/flags/sort_order on existing rows WITHOUT
--    changing row ids (FK-safe). Does NOT remove tenant-custom rows.
--    Records the reset on tenant_catalog_versions. Returns rows affected.
-- ═══════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION entity.reset_tenant_catalog(
  p_tenant_id   UUID,
  p_catalog_key TEXT,
  p_version     INT DEFAULT NULL
) RETURNS INT
LANGUAGE plpgsql AS $$
DECLARE
  v_current INT;
  v_version INT;
  v_rows    INT;
BEGIN
  IF p_tenant_id IS NULL OR p_catalog_key IS NULL THEN
    RAISE EXCEPTION 'reset_tenant_catalog: tenant id and catalog key are required';
  END IF;

  SELECT current_version INTO v_current FROM entity.catalog_versions WHERE catalog_key = p_catalog_key;
  IF v_current IS NULL THEN
    RAISE EXCEPTION 'reset_tenant_catalog: unknown catalog %', p_catalog_key;
  END IF;

  v_version := COALESCE(p_version, v_current);
  IF NOT EXISTS (
    SELECT 1 FROM entity.catalog_defaults WHERE catalog_key = p_catalog_key AND version = v_version
  ) THEN
    RAISE EXCEPTION 'reset_tenant_catalog: catalog % has no version %', p_catalog_key, v_version;
  END IF;

  v_rows := entity._apply_catalog_rows(p_tenant_id, p_catalog_key, v_version, TRUE);

  INSERT INTO entity.tenant_catalog_versions (tenant_id, catalog_key, version, reset_at)
  VALUES (p_tenant_id, p_catalog_key, v_version, CLOCK_TIMESTAMP())
  ON CONFLICT (tenant_id, catalog_key) DO UPDATE
    SET version = EXCLUDED.version, reset_at = CLOCK_TIMESTAMP();

  RETURN v_rows;
END; $$;

COMMIT;
