-- ===================================================================
-- 05_views.sql
--
-- All views. Early-bound on the functions in 04_, so it must follow them.
-- Every view is security_invoker so RLS is evaluated as the querying user.
--
-- Generated by the db_scripts consolidation. Fresh-install only:
-- there is no in-place upgrade path, no ALTER-after-the-fact section,
-- and no _migrations/ folder. Schema changes are made in the
-- CREATE statement itself and the database is rebuilt.
-- ===================================================================

BEGIN;

-- Dropped rather than replaced: the last return column was renamed
-- sample_emails -> sample_targets when login gained mobile numbers, and
-- CREATE OR REPLACE cannot rename a RETURNS TABLE column. The view is
-- SELECT * over the function, so it carries the old column name too and has
-- to go first. Both are rebuilt immediately below; no data lives here.
DROP VIEW     IF EXISTS audit.vw_password_spray_alerts;

-- Convenience view over the default thresholds (15 min / 10 accounts) for a
-- dashboard panel or a cron'd alert query.
CREATE OR REPLACE VIEW audit.vw_password_spray_alerts AS
  SELECT * FROM audit.fn_detect_password_spray(15, 10);

COMMENT ON VIEW audit.vw_password_spray_alerts IS
  'Password-spray alerts over the last 15 minutes (>=10 distinct accounts). Poll this from your alerting system.';

-- ===================================================================
-- VIEWS
-- ===================================================================

-- ── The two hierarchy views ────────────────────────────────────────
-- Both are now thin "as of today" wrappers over iam.reporting_lines (the single
-- platform hierarchy, see 02_tables_core.sql). Their names and columns are
-- unchanged from when they read iam.users.manager_id, which is what carries
-- every existing consumer — iam.can_assign_to, hr.can_approve_leave,
-- leads-service leads-history scope=team, tasks-service team scope, hr-service
-- leave/attendance subtree reads — onto the single tree with no query changes.
--
-- For any date other than today, call iam.fn_subtree_members(mgr, as_of) /
-- iam.fn_manager_chain(user, as_of) directly; a view cannot be parameterized.

-- Recursive org chart (depth + breadcrumb path).
-- Anchor note: reporting_lines.manager_id is NOT NULL and absence of a row means
-- "no manager", so top-of-tree is "an org member with no effective line" rather
-- than the old "manager_id IS NULL". Anchored on iam.user_org_mapping, which
-- also means a user shared across orgs is rooted once per org they belong to.
CREATE OR REPLACE VIEW iam.vw_user_org_chart WITH (security_invoker = true) AS
WITH RECURSIVE tree AS (
  SELECT u.id, uom.org_id, u.first_name, u.middle_name, u.last_name, u.full_name, u.email,
         ur.name AS role_name, NULL::UUID AS manager_id,
         NULL::TEXT AS manager_full_name,
         0 AS hierarchy_level,
         ARRAY[u.id] AS ancestor_ids,
         ARRAY[u.full_name]::TEXT[] AS path_names
  FROM iam.user_org_mapping uom
  JOIN iam.users      u  ON u.id  = uom.user_id
  JOIN iam.user_roles ur ON ur.id = uom.role_id
  WHERE uom.is_active AND NOT u.is_deleted
    AND NOT EXISTS (
      SELECT 1 FROM iam.reporting_lines rl
      WHERE rl.user_id = u.id AND rl.org_id = uom.org_id
        AND NOT rl.is_deleted
        AND rl.effective_from <= CURRENT_DATE
        AND (rl.effective_to IS NULL OR rl.effective_to > CURRENT_DATE)
    )
  UNION ALL
  SELECT u.id, rl.org_id, u.first_name, u.middle_name, u.last_name, u.full_name, u.email,
         ur.name AS role_name, rl.manager_id,
         t.full_name AS manager_full_name,
         t.hierarchy_level + 1,
         t.ancestor_ids || u.id,
         t.path_names   || u.full_name
  FROM iam.reporting_lines rl
  JOIN tree t         ON t.id  = rl.manager_id AND t.org_id = rl.org_id
  JOIN iam.users u    ON u.id  = rl.user_id
  JOIN iam.user_org_mapping uom ON uom.user_id = u.id AND uom.org_id = rl.org_id AND uom.is_active
  JOIN iam.user_roles ur        ON ur.id = uom.role_id
  WHERE NOT u.is_deleted
    AND NOT rl.is_deleted
    AND rl.effective_from <= CURRENT_DATE
    AND (rl.effective_to IS NULL OR rl.effective_to > CURRENT_DATE)
    AND NOT (u.id = ANY(t.ancestor_ids))
)
SELECT id AS user_id, org_id, first_name, middle_name, last_name, full_name, email,
       role_name, manager_id, manager_full_name, hierarchy_level,
       array_to_string(path_names, ' > ') AS reporting_path, ancestor_ids
FROM tree;

-- Recursive subtree membership — the "who is in my team" half of every
-- product's authority check. Rows are (manager, member) pairs at any depth;
-- depth >= 1 always, since a manager is not their own team member.
CREATE OR REPLACE VIEW iam.vw_user_team_members WITH (security_invoker = true) AS
SELECT m.id                AS manager_id,
       s.org_id,
       s.member_id,
       u.full_name         AS member_full_name,
       u.email             AS member_email,
       ur.name             AS member_role,
       s.direct_manager_id,
       s.depth,
       u.is_active
FROM iam.users m
CROSS JOIN LATERAL iam.fn_subtree_members(m.id, CURRENT_DATE) s
JOIN iam.users u              ON u.id  = s.member_id AND NOT u.is_deleted
JOIN iam.user_org_mapping uom ON uom.user_id = u.id AND uom.org_id = s.org_id AND uom.is_active
JOIN iam.user_roles ur        ON ur.id = uom.role_id
WHERE NOT m.is_deleted;

-- Primary lead listing.
-- city = ml.city (free-text, always populated); city_name = from geographic FK (when available).
CREATE OR REPLACE VIEW lms.vw_dashboard_leads WITH (security_invoker = true) AS
SELECT
  ml.id                AS lead_id,
  ml.org_id,
  o.name               AS org_name,
  ml.first_name,
  ml.middle_name,
  ml.last_name,
  ml.full_name,
  ml.phone,
  ml.email,
  ml.city,
  ci.name              AS city_name,
  st.name              AS state_name,
  co.name              AS country_name,
  ml.address_line1,
  ml.tags,
  ml.metadata,
  ls.name              AS stage,
  ls.label             AS stage_label,
  ls.followup_required,
  ls.is_rejected,
  ls.is_terminated,
  lso.name             AS outcome,
  lso.label            AS outcome_label,
  ml.outcome_comment,
  ml.stage_id,
  ml.outcome_id,
  ac.name              AS campaign_name,
  mp.name              AS platform,
  src.name             AS source,
  u.full_name          AS assigned_rep_name,
  u.email              AS assigned_rep_email,
  ml.assigned_user_id,
  ml.campaign_id,
  ml.is_active,
  ml.superseded_by,
  ml.is_deleted,
  ml.created_at,
  ml.updated_at,
  ml.scheduled_at,
  (ml.scheduled_at IS NOT NULL AND ml.scheduled_at < NOW()) AS is_followup_overdue,
  -- Display label for `source` above, the same name/label pairing stage and
  -- outcome get. Appended last rather than sitting next to `source` because
  -- CREATE OR REPLACE VIEW can only add columns at the end — re-asserting this
  -- file against a live database would fail on a mid-list insert.
  src.label            AS source_label
FROM  lms.marketing_leads     ml
JOIN  entity.organizations        o    ON o.id    = ml.org_id
LEFT JOIN lms.lead_stage       ls   ON ls.id   = ml.stage_id AND ls.tenant_id  = o.tenant_id
LEFT JOIN lms.lead_stage_outcome lso ON lso.id = ml.outcome_id AND lso.tenant_id = o.tenant_id
LEFT JOIN marketing.ad_campaigns     ac   ON ac.id   = ml.campaign_id
LEFT JOIN marketing.marketing_platforms mp ON mp.id  = ac.platform_id AND mp.tenant_id  = o.tenant_id
LEFT JOIN iam.users            u    ON u.id    = ml.assigned_user_id
LEFT JOIN lms.lead_sources     src  ON src.id  = ml.source_id AND src.tenant_id = o.tenant_id
-- geo.* is tenant-scoped, and a lead reaches its tenant only through its org,
-- so every geo join is qualified on the org's tenant_id. Belt and braces
-- alongside the trigger check in 04_functions_triggers.sql: a view is the
-- one place a stray row would fan out to the whole dashboard.
LEFT JOIN geo.cities           ci   ON ci.id   = ml.city_id    AND ci.tenant_id = o.tenant_id
LEFT JOIN geo.states           st   ON st.id   = ml.state_id   AND st.tenant_id = o.tenant_id
LEFT JOIN geo.countries        co   ON co.id   = ml.country_id AND co.tenant_id = o.tenant_id;

-- Unified lead timeline: status changes + follow-ups + interactions + assignment changes.
CREATE OR REPLACE VIEW lms.vw_lead_followup_timeline WITH (security_invoker = true) AS
SELECT
  lsl.id AS event_id, lsl.org_id, lsl.lead_id,
  'status_change'     AS event_type,
  lsl.changed_at      AS event_at,
  cb.full_name AS actor_name, cb.email AS actor_email,
  os.name AS old_stage,  os.label AS old_stage_label,
  ns.name AS new_stage,  ns.label AS new_stage_label,
  ofr.name AS old_outcome, ofr.label AS old_outcome_label,
  nfr.name AS new_outcome, nfr.label AS new_outcome_label,
  au.full_name AS assigned_to_name,
  lsl.transition_note AS note,
  NULL::uuid          AS followup_id,
  NULL::text          AS followup_status,
  NULL::timestamptz   AS scheduled_at,
  NULL::timestamptz   AS completed_at,
  NULL::text          AS interaction_type
FROM lms.lead_status_log lsl
-- Each UNION branch joins organizations for its own tenant_id: the catalog
-- tables below are tenant-scoped and this view is read under BYPASSRLS too.
JOIN entity.organizations        o   ON o.id   = lsl.org_id
LEFT JOIN iam.users              cb  ON cb.id  = lsl.changed_by_id
LEFT JOIN lms.lead_stage         os  ON os.id  = lsl.old_stage_id  AND os.tenant_id  = o.tenant_id
JOIN  lms.lead_stage             ns  ON ns.id  = lsl.new_stage_id  AND ns.tenant_id  = o.tenant_id
LEFT JOIN lms.lead_stage_outcome ofr ON ofr.id = lsl.old_outcome_id AND ofr.tenant_id = o.tenant_id
LEFT JOIN lms.lead_stage_outcome nfr ON nfr.id = lsl.new_outcome_id AND nfr.tenant_id = o.tenant_id
LEFT JOIN iam.users              au  ON au.id  = lsl.assigned_user_id

UNION ALL

SELECT
  lf.id, lf.org_id, lf.lead_id,
  'follow_up',
  COALESCE(lf.completed_at, lf.scheduled_at),
  u.full_name, u.email,
  NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  u.full_name, lf.notes,
  lf.id, fs.name, lf.scheduled_at, lf.completed_at, NULL
FROM lms.lead_follow_ups lf
JOIN entity.organizations o ON o.id = lf.org_id
JOIN lms.follow_up_statuses fs ON fs.id = lf.status_id AND fs.tenant_id = o.tenant_id
JOIN iam.users u ON u.id = lf.assigned_user_id
WHERE NOT lf.is_deleted

UNION ALL

SELECT
  li.id, li.org_id, li.lead_id,
  'interaction',
  li.occurred_at,
  u.full_name, u.email,
  NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  NULL, li.notes,
  NULL, NULL, NULL, NULL, it.name
FROM lms.lead_interactions li
JOIN entity.organizations o ON o.id = li.org_id
LEFT JOIN lms.interaction_types it ON it.id = li.interaction_type_id AND it.tenant_id = o.tenant_id
JOIN iam.users u ON u.id = li.user_id
WHERE NOT li.is_deleted

UNION ALL

SELECT
  l.id, l.org_id, l.lead_id,
  'assignment_change',
  l.assigned_at,
  cu.full_name, cu.email,
  NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
  COALESCE(new_u.full_name, 'Unassigned'),
  CASE
    WHEN old_u.full_name IS NULL THEN 'Assigned to '    || COALESCE(new_u.full_name, 'unknown')
    WHEN new_u.full_name IS NULL THEN 'Unassigned from '|| old_u.full_name
    ELSE 'Reassigned from ' || old_u.full_name || ' to ' || COALESCE(new_u.full_name, 'unknown')
  END,
  NULL, NULL, NULL, NULL, NULL
FROM lms.lead_assignment_log l
LEFT JOIN iam.users cu    ON cu.id = l.assigned_by_id
LEFT JOIN iam.users old_u ON old_u.id = l.previous_assignee_id
LEFT JOIN iam.users new_u ON new_u.id = l.assigned_to_id;

-- Assignment history for a lead (who held it, for how long).
CREATE OR REPLACE VIEW lms.vw_lead_assignment_timeline WITH (security_invoker = true) AS
SELECT
  l.id AS log_id, l.org_id, l.lead_id, ml.full_name AS lead_full_name,
  actor.full_name  AS assigned_by_name,  actor.email  AS assigned_by_email,
  target.full_name AS assigned_to_name,  target.email AS assigned_to_email,
  prev.full_name   AS previous_assignee_name,
  l.action, l.note, l.assigned_at,
  LEAD(l.assigned_at) OVER (PARTITION BY l.lead_id ORDER BY l.assigned_at)
    - l.assigned_at AS held_for
FROM lms.lead_assignment_log l
JOIN  lms.marketing_leads ml  ON ml.id    = l.lead_id
LEFT JOIN iam.users actor     ON actor.id  = l.assigned_by_id
LEFT JOIN iam.users target    ON target.id = l.assigned_to_id
LEFT JOIN iam.users prev      ON prev.id   = l.previous_assignee_id;

-- Follow-up queue: pending + missed only.
CREATE OR REPLACE VIEW lms.vw_sales_follow_up_pipeline WITH (security_invoker = true) AS
SELECT
  lf.id AS follow_up_id, lf.org_id, o.name AS org_name,
  ml.full_name AS lead_full_name, ml.phone AS lead_phone, ml.email AS lead_email,
  u.full_name AS assigned_rep_name, u.email AS assigned_rep_email,
  fs.name AS status, lf.scheduled_at, lf.completed_at, lf.notes
FROM lms.lead_follow_ups lf
-- organizations first: it carries the tenant_id the catalog joins below are
-- qualified on, and a join can only reference aliases introduced before it.
JOIN entity.organizations       o  ON o.id   = lf.org_id
JOIN lms.marketing_leads     ml ON ml.id  = lf.lead_id
JOIN iam.users               u  ON u.id   = lf.assigned_user_id
JOIN lms.follow_up_statuses  fs ON fs.id  = lf.status_id AND fs.tenant_id = o.tenant_id
WHERE fs.name IN ('pending','missed');

-- Enriched follow-up pipeline with overdue flag + last interaction.
CREATE OR REPLACE VIEW lms.vw_followup_pipeline_enriched WITH (security_invoker = true) AS
SELECT
  lf.id AS follow_up_id, lf.org_id, o.name AS org_name, lf.lead_id,
  ml.full_name AS lead_full_name, ml.phone AS lead_phone, ml.email AS lead_email,
  ls.name AS lead_stage, ls.label AS lead_stage_label, ml.tags AS lead_tags,
  u.id AS assigned_rep_id, u.full_name AS assigned_rep_name, u.email AS assigned_rep_email,
  fs.name AS follow_up_status, lf.scheduled_at, lf.completed_at, lf.notes, lf.created_at,
  (fs.name = 'pending' AND lf.scheduled_at < CLOCK_TIMESTAMP()) AS is_overdue,
  CASE WHEN fs.name = 'pending' AND lf.scheduled_at < CLOCK_TIMESTAMP()
       THEN EXTRACT(EPOCH FROM (CLOCK_TIMESTAMP() - lf.scheduled_at))::INT / 60
       ELSE NULL END AS minutes_overdue,
  last_ix.occurred_at AS last_interaction_at,
  last_ix.type_name   AS last_interaction_type
FROM lms.lead_follow_ups lf
-- organizations first: see lms.vw_sales_follow_up_pipeline above.
JOIN entity.organizations       o  ON o.id   = lf.org_id
JOIN lms.marketing_leads     ml ON ml.id  = lf.lead_id
JOIN lms.lead_stage          ls ON ls.id  = ml.stage_id AND ls.tenant_id = o.tenant_id
JOIN lms.follow_up_statuses  fs ON fs.id  = lf.status_id AND fs.tenant_id = o.tenant_id
JOIN iam.users               u  ON u.id   = lf.assigned_user_id
LEFT JOIN LATERAL (
  SELECT li.occurred_at, it.name AS type_name
  FROM lms.lead_interactions li
  LEFT JOIN lms.interaction_types it ON it.id = li.interaction_type_id
  WHERE li.lead_id = lf.lead_id AND NOT li.is_deleted
  ORDER BY li.occurred_at DESC LIMIT 1
) last_ix ON TRUE
WHERE NOT lf.is_deleted AND NOT ml.is_deleted AND fs.name IN ('pending','missed');

-- Per-org KPIs for analytics service.
CREATE OR REPLACE VIEW lms.vw_org_performance_snapshot WITH (security_invoker = true) AS
WITH lead_counts AS (
  SELECT ml.org_id,
    COUNT(*)                                        AS total_leads,
    COUNT(*) FILTER (WHERE ls.name = 'converted')   AS converted_leads,
    COUNT(*) FILTER (WHERE ls.name = 'unqualified') AS unqualified_leads
  FROM lms.marketing_leads ml JOIN lms.lead_stage ls ON ls.id = ml.stage_id
  WHERE NOT ml.is_deleted GROUP BY ml.org_id
),
interaction_stats AS (
  SELECT org_id, COUNT(*) AS total_interactions, COUNT(DISTINCT lead_id) AS leads_with_interactions
  FROM lms.lead_interactions WHERE NOT is_deleted GROUP BY org_id
),
follow_up_counts AS (
  SELECT lf.org_id,
    COUNT(*) FILTER (WHERE fs.name = 'pending') AS pending_follow_ups,
    COUNT(*) FILTER (WHERE fs.name = 'missed')  AS missed_follow_ups
  FROM lms.lead_follow_ups lf JOIN lms.follow_up_statuses fs ON fs.id = lf.status_id
  WHERE NOT lf.is_deleted GROUP BY lf.org_id
),
platform_usage AS (
  SELECT org_id, most_used_platform FROM (
    SELECT ac.org_id, mp.name AS most_used_platform, COUNT(ml.id) AS lead_count,
           ROW_NUMBER() OVER (PARTITION BY ac.org_id ORDER BY COUNT(ml.id) DESC) AS rn
    FROM marketing.ad_campaigns ac JOIN marketing.marketing_platforms mp ON mp.id = ac.platform_id
    LEFT JOIN lms.marketing_leads ml ON ml.campaign_id = ac.id AND NOT ml.is_deleted
    WHERE NOT ac.is_deleted GROUP BY ac.org_id, mp.name
  ) r WHERE rn = 1
)
SELECT
  o.id AS org_id, o.name AS org_name, o.tenant_id,
  COALESCE(lc.total_leads,       0)::INT AS total_leads,
  COALESCE(lc.converted_leads,   0)::INT AS converted_leads,
  COALESCE(lc.unqualified_leads, 0)::INT AS unqualified_leads,
  CASE WHEN COALESCE(ist.leads_with_interactions,0) = 0 THEN 0::NUMERIC(5,2)
       ELSE ROUND(ist.total_interactions::NUMERIC / ist.leads_with_interactions, 2)
  END AS avg_interactions_per_lead,
  COALESCE(fc.pending_follow_ups, 0)::INT AS pending_follow_ups,
  COALESCE(fc.missed_follow_ups,  0)::INT AS missed_follow_ups,
  pu.most_used_platform,
  CLOCK_TIMESTAMP() AS snapshot_at
FROM entity.organizations o
LEFT JOIN lead_counts lc ON lc.org_id = o.id
LEFT JOIN interaction_stats ist ON ist.org_id = o.id
LEFT JOIN follow_up_counts fc ON fc.org_id = o.id
LEFT JOIN platform_usage pu ON pu.org_id = o.id
WHERE NOT o.is_deleted;

-- Cross-org tenant KPIs (query as tenant_admin role).
CREATE OR REPLACE VIEW lms.vw_tenant_full_dashboard WITH (security_invoker = true) AS
WITH org_leads AS (
  SELECT ml.org_id,
    COUNT(*)                                               AS total_leads,
    COUNT(*) FILTER (WHERE ls.name = 'new')               AS new_leads,
    COUNT(*) FILTER (WHERE ls.name = 'contacting')        AS contacting_leads,
    COUNT(*) FILTER (WHERE ls.name = 'qualified')         AS qualified_leads,
    COUNT(*) FILTER (WHERE ls.name = 'converted')         AS converted_leads,
    COUNT(*) FILTER (WHERE ls.name = 'unqualified')       AS unqualified_leads,
    COUNT(*) FILTER (WHERE ls.name = 'transferred_out')   AS transferred_out_leads
  FROM lms.marketing_leads ml JOIN lms.lead_stage ls ON ls.id = ml.stage_id
  WHERE NOT ml.is_deleted GROUP BY ml.org_id
),
org_follow_ups AS (
  SELECT lf.org_id,
    COUNT(*) FILTER (WHERE fs.name = 'pending')   AS pending_follow_ups,
    COUNT(*) FILTER (WHERE fs.name = 'missed')    AS missed_follow_ups,
    COUNT(*) FILTER (WHERE fs.name = 'completed') AS completed_follow_ups
  FROM lms.lead_follow_ups lf JOIN lms.follow_up_statuses fs ON fs.id = lf.status_id
  WHERE NOT lf.is_deleted GROUP BY lf.org_id
),
org_platform AS (
  SELECT org_id, most_used_platform FROM (
    SELECT ac.org_id, mp.name AS most_used_platform, COUNT(ml.id) AS cnt,
           ROW_NUMBER() OVER (PARTITION BY ac.org_id ORDER BY COUNT(ml.id) DESC) AS rn
    FROM marketing.ad_campaigns ac JOIN marketing.marketing_platforms mp ON mp.id = ac.platform_id
    LEFT JOIN lms.marketing_leads ml ON ml.campaign_id = ac.id AND NOT ml.is_deleted
    WHERE NOT ac.is_deleted GROUP BY ac.org_id, mp.name
  ) r WHERE rn = 1
)
SELECT
  o.tenant_id, t.name AS tenant_name, o.id AS org_id, o.name AS org_name,
  ot.name AS org_type,
  o.city,
  ci.name AS city_name, st.name AS state_name,
  COALESCE(ol.total_leads,           0)::INT AS total_leads,
  COALESCE(ol.new_leads,             0)::INT AS new_leads,
  COALESCE(ol.contacting_leads,      0)::INT AS contacting_leads,
  COALESCE(ol.qualified_leads,       0)::INT AS qualified_leads,
  COALESCE(ol.converted_leads,       0)::INT AS converted_leads,
  COALESCE(ol.unqualified_leads,     0)::INT AS unqualified_leads,
  COALESCE(ol.transferred_out_leads, 0)::INT AS transferred_out_leads,
  CASE WHEN COALESCE(ol.total_leads, 0) = 0 THEN 0::NUMERIC(5,2)
       ELSE ROUND(ol.converted_leads::NUMERIC / ol.total_leads * 100, 2)
  END AS conversion_rate_pct,
  COALESCE(ofu.pending_follow_ups,   0)::INT AS pending_follow_ups,
  COALESCE(ofu.missed_follow_ups,    0)::INT AS missed_follow_ups,
  COALESCE(ofu.completed_follow_ups, 0)::INT AS completed_follow_ups,
  op.most_used_platform,
  CLOCK_TIMESTAMP() AS snapshot_at
FROM entity.organizations o
JOIN entity.tenants t ON t.id = o.tenant_id
LEFT JOIN entity.org_types ot ON ot.id = o.org_type_id
LEFT JOIN geo.cities    ci ON ci.id = o.city_id  AND ci.tenant_id = o.tenant_id
LEFT JOIN geo.states    st ON st.id = o.state_id AND st.tenant_id = o.tenant_id
LEFT JOIN org_leads ol ON ol.org_id = o.id
LEFT JOIN org_follow_ups ofu ON ofu.org_id = o.id
LEFT JOIN org_platform   op  ON op.org_id  = o.id
WHERE NOT o.is_deleted AND NOT t.is_deleted;

-- ── ADDITIONAL VIEWS (v1.2) ───────────────────────────────────────

-- All active org-user mappings with role and org context.
-- Used by APIs that need to know which orgs a user can access.
CREATE OR REPLACE VIEW iam.vw_user_org_access WITH (security_invoker = true) AS
SELECT
  uom.user_id,
  u.full_name     AS user_full_name,
  u.email         AS user_email,
  u.is_active     AS user_is_active,
  uom.org_id,
  o.name          AS org_name,
  o.tenant_id,
  t.name          AS tenant_name,
  ur.name         AS role_name,
  ur.label        AS role_label,
  ur.rank         AS role_rank,
  uom.granted_at,
  uom.updated_at  AS mapping_updated_at
FROM iam.user_org_mapping uom
JOIN iam.users          u  ON u.id  = uom.user_id  AND NOT u.is_deleted
JOIN entity.organizations  o  ON o.id  = uom.org_id   AND NOT o.is_deleted
JOIN entity.tenants        t  ON t.id  = o.tenant_id   AND NOT t.is_deleted
-- super_admin is the ONE role that is deliberately global (tenant_id IS NULL,
-- see 10_tenant_provisioning.sql), so a strict equality would drop every
-- super_admin's access row. Verified: it did, 26 -> 25.
JOIN iam.user_roles     ur ON ur.id = uom.role_id
                          AND (ur.tenant_id = o.tenant_id OR ur.tenant_id IS NULL)
WHERE uom.is_active;

-- Ad campaigns with resolved platform and status names (for dropdowns).
CREATE OR REPLACE VIEW marketing.vw_campaign_lookup WITH (security_invoker = true) AS
SELECT
  ac.id         AS campaign_id,
  ac.name       AS campaign_name,
  ac.org_id,
  o.name        AS org_name,
  mp.name       AS platform_name,
  mp.id         AS platform_id,
  cs.name       AS status_name,
  cs.id         AS status_id,
  ac.budget,
  ac.started_at,
  ac.ended_at,
  ac.created_at
FROM marketing.ad_campaigns      ac
JOIN entity.organizations     o  ON o.id  = ac.org_id      AND NOT o.is_deleted
JOIN marketing.marketing_platforms mp ON mp.id = ac.platform_id AND mp.tenant_id = o.tenant_id
JOIN marketing.campaign_statuses cs ON cs.id  = ac.status_id AND cs.tenant_id = o.tenant_id
WHERE NOT ac.is_deleted;

-- Per-rep lead counts by stage (org-scoped, for analytics / leaderboard).
CREATE OR REPLACE VIEW lms.vw_rep_performance WITH (security_invoker = true) AS
SELECT
  ml.org_id,
  o.name                AS org_name,
  u.id                  AS rep_id,
  u.full_name           AS rep_name,
  u.email               AS rep_email,
  ur.name               AS role_name,
  COUNT(*)              AS total_assigned,
  COUNT(*) FILTER (WHERE ls.name = 'new')            AS new_count,
  COUNT(*) FILTER (WHERE ls.name = 'contacting')     AS contacting_count,
  COUNT(*) FILTER (WHERE ls.name = 'qualified')      AS qualified_count,
  COUNT(*) FILTER (WHERE ls.name = 'converted')      AS converted_count,
  COUNT(*) FILTER (WHERE ls.name = 'unqualified')    AS unqualified_count,
  COUNT(*) FILTER (WHERE ls.name = 'transferred_out') AS transferred_out_count,
  CASE WHEN COUNT(*) = 0 THEN 0::NUMERIC(5,2)
       ELSE ROUND(
         COUNT(*) FILTER (WHERE ls.name = 'converted')::NUMERIC / COUNT(*) * 100, 2
       )
  END                   AS conversion_rate_pct
FROM lms.marketing_leads ml
-- organizations first: see lms.vw_sales_follow_up_pipeline above.
JOIN entity.organizations  o  ON o.id  = ml.org_id
JOIN iam.users          u  ON u.id  = ml.assigned_user_id AND NOT u.is_deleted
JOIN iam.user_roles     ur ON ur.id = u.role_id
                          AND (ur.tenant_id = o.tenant_id OR ur.tenant_id IS NULL)  -- global super_admin
JOIN lms.lead_stage     ls ON ls.id = ml.stage_id AND ls.tenant_id = o.tenant_id
WHERE NOT ml.is_deleted
GROUP BY ml.org_id, o.name, u.id, u.full_name, u.email, ur.name;

-- ─────────────────────────────────────────────────────────────────────────────
-- Daily lead report counters. Two views, one metric set, three result shapes:
--   branch level  -> lms.vw_lead_report_branch WHERE org_id = ?
--   tenant level  -> lms.vw_lead_report_branch WHERE tenant_id = ?  (one row per
--                    branch; the caller adds a GROUPING SETS rollup row)
--   user level    -> lms.vw_lead_report_user   (per assignee, plus one
--                    "Unassigned" row per branch)
--
-- Population is `NOT is_deleted AND is_active` in BOTH views. is_active = FALSE
-- means the row was superseded by a dedup re-submission or transferred out to
-- another branch (see COMMENT ON lms.marketing_leads.is_active). A transferred
-- lead is inactive in the source branch and active in the destination, so
-- counting inactive rows double-counts the same person in a tenant rollup --
-- the one thing a branch-breakdown report must never do. Note that
-- lms.vw_org_performance_snapshot above filters only NOT is_deleted and is
-- therefore inflated; do not copy it.
--
-- Follow-up counters read lms.marketing_leads.scheduled_at and use the SAME
-- expression as lms.vw_dashboard_leads.is_followup_overdue, deliberately
-- including terminal stages. If that rule ever tightens, it has to change here
-- and in vw_dashboard_leads together, or the emailed count stops matching the
-- overdue badge in the leads list.
--
-- NOW() (not CLOCK_TIMESTAMP()) inside the filters: it is stable for the whole
-- statement, so a lead whose scheduled_at crosses the boundary mid-scan cannot
-- land in both followup_scheduled and followup_overdue. CLOCK_TIMESTAMP() is
-- used only for the snapshot_at output column, matching the views above.
--
-- Neither view joins entity.tenants, and neither exposes tenant_name, even
-- though tenant_id is right there. Under security_invoker the CALLER's grants
-- apply, and neither app_user nor tenant_admin has SELECT on entity.tenants —
-- adding the join would make both views fail with "permission denied for table
-- tenants" for every HTTP caller on the tenant_admin path. (This is not
-- hypothetical: lms.vw_tenant_full_dashboard above does exactly that and is
-- unreadable by the tenant_admin role it is granted to.) The report's tenant
-- name is resolved separately, by the caller, which does hold that privilege.
-- ─────────────────────────────────────────────────────────────────────────────

-- Per-branch report counters. One row per non-deleted org -- a branch with no
-- leads still appears, as a zero row, so a silent join failure looks different
-- from a genuinely quiet branch.
--
-- new_leads_today is the only date-bounded metric, and it is bounded in the
-- BRANCH's own timezone (entity.organizations.timezone). date_trunc/::date on a
-- timestamptz truncates in UTC, which for an Asia/Kolkata branch (UTC+5:30)
-- files everything created before 05:30 local under the previous day and makes
-- the report disagree with the leads list. Hence AT TIME ZONE o.timezone.
CREATE OR REPLACE VIEW lms.vw_lead_report_branch WITH (security_invoker = true) AS
WITH counters AS (
  SELECT
    ml.org_id,
    COUNT(*)                                                         AS total_leads,
    COUNT(*) FILTER (WHERE ls.name = 'new')                          AS new_count,
    COUNT(*) FILTER (WHERE (ml.created_at AT TIME ZONE o.timezone)::date
                         = (NOW()          AT TIME ZONE o.timezone)::date) AS new_leads_today,
    COUNT(*) FILTER (WHERE ml.assigned_user_id IS NULL)              AS unassigned_count,
    COUNT(*) FILTER (WHERE ml.scheduled_at IS NOT NULL
                       AND ml.scheduled_at >= NOW())                 AS followup_scheduled,
    COUNT(*) FILTER (WHERE ml.scheduled_at IS NOT NULL
                       AND ml.scheduled_at <  NOW())                 AS followup_overdue,
    COUNT(*) FILTER (WHERE ls.name = 'converted')                    AS converted_count,
    COUNT(*) FILTER (WHERE ls.name = 'unqualified')                  AS unqualified_count
  FROM lms.marketing_leads ml
  JOIN entity.organizations o ON o.id = ml.org_id
  -- LEFT, not INNER: stage_id is nullable, and an inner join would silently drop
  -- stage-less leads from total_leads and new_leads_today.
  LEFT JOIN lms.lead_stage ls ON ls.id = ml.stage_id AND ls.tenant_id = o.tenant_id
  WHERE NOT ml.is_deleted AND ml.is_active
  GROUP BY ml.org_id
)
SELECT
  o.tenant_id,
  o.id                                     AS org_id,
  o.name                                   AS org_name,
  o.timezone                               AS org_timezone,
  (NOW() AT TIME ZONE o.timezone)::date    AS report_date,
  COALESCE(c.total_leads,        0)::INT    AS total_leads,
  COALESCE(c.new_count,          0)::INT    AS new_count,
  COALESCE(c.new_leads_today,    0)::INT    AS new_leads_today,
  COALESCE(c.unassigned_count,   0)::INT    AS unassigned_count,
  COALESCE(c.followup_scheduled, 0)::INT    AS followup_scheduled,
  COALESCE(c.followup_overdue,   0)::INT    AS followup_overdue,
  COALESCE(c.converted_count,    0)::INT    AS converted_count,
  COALESCE(c.unqualified_count,  0)::INT    AS unqualified_count,
  CLOCK_TIMESTAMP()                        AS snapshot_at
FROM entity.organizations o
LEFT JOIN counters c ON c.org_id = o.id
WHERE NOT o.is_deleted;

-- Per (branch, assignee) report counters, with an explicit "Unassigned" bucket
-- per branch. That bucket is just the assigned_user_id IS NULL group: grouping
-- on a nullable column already yields exactly one NULL group per branch, so no
-- UNION ALL and no second scan is needed, and because assigned_user_id is
-- ON DELETE SET NULL an orphaned assignment folds in here rather than vanishing.
--
-- Keyed on ml.org_id -- the branch the LEAD belongs to, not the assignee's home
-- org (iam.users.org_id). A rep with iam.user_org_mapping rows in two branches
-- therefore appears once per branch, which is what a branch breakdown must show.
-- Branches with no leads at all produce no row here (use vw_lead_report_branch
-- for the guaranteed-complete branch list).
--
-- unassigned_count is carried here too -- it equals total_leads on the
-- Unassigned row and 0 elsewhere -- purely so the metric column set is identical
-- across all three result shapes and one renderer serves them all.
--
-- Same population, timezone and follow-up rules as lms.vw_lead_report_branch.
CREATE OR REPLACE VIEW lms.vw_lead_report_user WITH (security_invoker = true) AS
SELECT
  o.tenant_id,
  ml.org_id,
  o.name                                   AS org_name,
  ml.assigned_user_id,                     -- NULL = the Unassigned bucket
  COALESCE(u.full_name, 'Unassigned')      AS assignee,
  u.email                                  AS assignee_email,
  (ml.assigned_user_id IS NULL)            AS is_unassigned,
  (NOW() AT TIME ZONE o.timezone)::date    AS report_date,
  COUNT(*)::INT                                                    AS total_leads,
  COUNT(*) FILTER (WHERE ls.name = 'new')::INT                     AS new_count,
  COUNT(*) FILTER (WHERE (ml.created_at AT TIME ZONE o.timezone)::date
                       = (NOW()          AT TIME ZONE o.timezone)::date)::INT AS new_leads_today,
  COUNT(*) FILTER (WHERE ml.assigned_user_id IS NULL)::INT          AS unassigned_count,
  COUNT(*) FILTER (WHERE ml.scheduled_at IS NOT NULL
                     AND ml.scheduled_at >= NOW())::INT             AS followup_scheduled,
  COUNT(*) FILTER (WHERE ml.scheduled_at IS NOT NULL
                     AND ml.scheduled_at <  NOW())::INT             AS followup_overdue,
  COUNT(*) FILTER (WHERE ls.name = 'converted')::INT                AS converted_count,
  COUNT(*) FILTER (WHERE ls.name = 'unqualified')::INT              AS unqualified_count,
  CLOCK_TIMESTAMP()                        AS snapshot_at
FROM lms.marketing_leads ml
JOIN entity.organizations o ON o.id = ml.org_id AND NOT o.is_deleted
LEFT JOIN lms.lead_stage ls ON ls.id = ml.stage_id AND ls.tenant_id = o.tenant_id
LEFT JOIN iam.users      u  ON u.id  = ml.assigned_user_id AND NOT u.is_deleted
WHERE NOT ml.is_deleted AND ml.is_active
GROUP BY o.tenant_id, ml.org_id, o.name, o.timezone,
         ml.assigned_user_id, u.full_name, u.email;

-- Campaign performance (tenant_admin scope).
CREATE OR REPLACE VIEW marketing.vw_tenant_campaign_summary WITH (security_invoker = true) AS
WITH cls AS (
  SELECT sub.campaign_id,
    SUM(sub.stage_cnt)::INT AS total_leads,
    COALESCE(SUM(sub.stage_cnt) FILTER (WHERE ls.name = 'converted'), 0)::INT AS converted_leads,
    jsonb_object_agg(ls.name, sub.stage_cnt) AS leads_by_stage
  FROM (
    SELECT campaign_id, stage_id, COUNT(*) AS stage_cnt
    FROM lms.marketing_leads WHERE campaign_id IS NOT NULL AND NOT is_deleted
    GROUP BY campaign_id, stage_id
  ) sub JOIN lms.lead_stage ls ON ls.id = sub.stage_id GROUP BY sub.campaign_id
)
SELECT
  o.tenant_id, ac.org_id, o.name AS org_name,
  ac.id AS campaign_id, ac.name AS campaign_name,
  mp.name AS platform, cs.name AS campaign_status, ac.budget,
  COALESCE(cls.total_leads, 0)::INT AS total_leads,
  COALESCE(cls.leads_by_stage, '{}'::jsonb) AS leads_by_stage,
  CASE WHEN COALESCE(cls.total_leads, 0) = 0 THEN 0::NUMERIC(5,2)
       ELSE ROUND(COALESCE(cls.converted_leads,0)::NUMERIC / cls.total_leads * 100, 2)
  END AS conversion_rate
FROM marketing.ad_campaigns ac
JOIN entity.organizations o ON o.id = ac.org_id
JOIN marketing.marketing_platforms mp ON mp.id = ac.platform_id AND mp.tenant_id = o.tenant_id
JOIN marketing.campaign_statuses cs ON cs.id = ac.status_id AND cs.tenant_id = o.tenant_id
LEFT JOIN cls ON cls.campaign_id = ac.id
WHERE NOT ac.is_deleted;

CREATE OR REPLACE VIEW ext.vw_meta_forms
  WITH (security_invoker = true)
AS
  SELECT
    f.id, f.tenant_id, f.page_id, f.form_id, f.name, f.status, f.leads_count,
    f.meta_created_time, f.last_synced_at, f.created_at, f.updated_at,
    m.org_id,
    (m.id IS NOT NULL) AS is_mapped
  FROM ext.meta_forms f
  LEFT JOIN ext.meta_page_form_org_map m
    ON m.form_id = f.form_id AND m.tenant_id = f.tenant_id AND m.is_active;

CREATE OR REPLACE VIEW ext.vw_meta_capi_event_types AS
SELECT id, code, label, description, is_active, sort_order
FROM ext.meta_capi_event_types
WHERE is_active = TRUE
ORDER BY sort_order, label;

-- security_invoker: without it this view runs as its OWNER, which would hand
-- every tenant's stage->event wiring to any caller and quietly defeat the RLS
-- on ext.lead_stage_capi_event_map. The join to lms.lead_stage is qualified on
-- tenant_id as well as id for the same reason the geo joins are — the
-- composite FK already guarantees it, and the predicate keeps it true if the
-- FK is ever dropped.
CREATE OR REPLACE VIEW ext.vw_lead_stage_capi_event_map
  WITH (security_invoker = true)
AS
SELECT
  m.id,
  m.tenant_id,
  m.stage_id,
  ls.name  AS stage_code,
  ls.label AS stage_label,
  m.capi_event_type_id,
  et.code  AS capi_event_code,
  et.label AS capi_event_label,
  m.created_at,
  m.updated_at
FROM ext.lead_stage_capi_event_map m
JOIN lms.lead_stage ls            ON ls.id = m.stage_id AND ls.tenant_id IS NOT DISTINCT FROM m.tenant_id
JOIN ext.meta_capi_event_types et ON et.id = m.capi_event_type_id;

-- ── VIEW: complete meta leads joined to lms.marketing_leads + address/professional/demographics ─
CREATE OR REPLACE VIEW ext.view_meta_leads_complete
  WITH (security_invoker = true)
AS
  SELECT ml.id, ml.org_id, ml.marketing_lead_id, ml.meta_lead_id,
         ml.page_id, ml.form_id, ml.campaign_id AS meta_campaign_id,
         ml.adset_id, ml.ad_id, ml.platform,
         ml.lead_created_at AS meta_created_at,
         ml.full_name AS meta_full_name, ml.email AS meta_email,
         ml.phone AS meta_phone, ml.whatsapp_number,
         ml.raw_field_data,
         mk.first_name, mk.last_name, mk.phone AS crm_phone, mk.email AS crm_email,
         mk.stage_id, mk.outcome_id, mk.assigned_user_id, mk.campaign_id AS crm_campaign_id,
         mk.created_at AS crm_created_at,
         addr.street_address, addr.city, addr.state, addr.province,
         addr.country, addr.postal_code, addr.zip_code,
         prof.job_title, prof.company_name, prof.work_email, prof.work_phone_number,
         demo.date_of_birth, demo.gender, demo.marital_status,
         demo.relationship_status, demo.military_status
  FROM ext.meta_leads ml
  LEFT JOIN lms.marketing_leads mk         ON ml.marketing_lead_id = mk.id
  LEFT JOIN ext.meta_lead_addresses addr   ON addr.meta_lead_id = ml.id
  LEFT JOIN ext.meta_lead_professional prof ON prof.meta_lead_id = ml.id
  LEFT JOIN ext.meta_lead_demographics demo ON demo.meta_lead_id = ml.id;


-- ===================================================================
-- 7. Views (security_invoker — underlying-table RLS applies to the caller)
-- ===================================================================

-- Per (user, org, leave_type) running balance = SUM(ledger.amount).
CREATE OR REPLACE VIEW hr.vw_leave_balances WITH (security_invoker = true) AS
SELECT
  ll.user_id,
  ll.org_id,
  ll.leave_type_id,
  lt.name         AS leave_type_name,
  lt.label        AS leave_type_label,
  SUM(ll.amount)  AS balance
FROM hr.leave_ledger ll
-- Catalog joins are qualified on tenant_id: these views are read under
-- BYPASSRLS service roles too, where RLS does not filter for us.
JOIN entity.organizations o ON o.id = ll.org_id
JOIN hr.leave_types  lt ON lt.id = ll.leave_type_id AND lt.tenant_id = o.tenant_id
GROUP BY ll.user_id, ll.org_id, ll.leave_type_id, lt.name, lt.label;

-- Requests joined with requester name, type/status labels, and latest approval.
CREATE OR REPLACE VIEW hr.vw_leave_requests_enriched WITH (security_invoker = true) AS
SELECT
  lr.id,
  lr.user_id,
  u.full_name      AS user_full_name,
  u.email          AS user_email,
  lr.org_id,
  lr.leave_type_id,
  lt.name          AS leave_type_name,
  lt.label         AS leave_type_label,
  lr.start_date,
  lr.end_date,
  lr.start_half,
  lr.end_half,
  lr.days_count,
  lr.reason,
  lr.status_id,
  lrs.name         AS status_name,
  lrs.label        AS status_label,
  lr.document_url,
  lr.is_open,
  la.level         AS latest_approval_level,
  la.approver_id   AS latest_approver_id,
  la.action        AS latest_approval_action,
  la.acted_at      AS latest_approval_acted_at,
  lr.created_at,
  lr.updated_at
FROM hr.leave_requests lr
JOIN iam.users                    u   ON u.id   = lr.user_id
-- Catalog joins are qualified on tenant_id: these views are read under
-- BYPASSRLS service roles too, where RLS does not filter for us.
JOIN entity.organizations         o   ON o.id  = lr.org_id
JOIN hr.leave_types               lt  ON lt.id  = lr.leave_type_id AND lt.tenant_id  = o.tenant_id
JOIN hr.leave_request_statuses    lrs ON lrs.id = lr.status_id     AND lrs.tenant_id = o.tenant_id
LEFT JOIN LATERAL (
  SELECT level, approver_id, action, acted_at
  FROM hr.leave_request_approvals a
  WHERE a.leave_request_id = lr.id
  ORDER BY a.level DESC
  LIMIT 1
) la ON TRUE
WHERE NOT lr.is_deleted;

-- Approved leaves with user info, for team-calendar date-range queries.
CREATE OR REPLACE VIEW hr.vw_team_leave_calendar WITH (security_invoker = true) AS
SELECT
  lr.id,
  lr.user_id,
  u.full_name    AS user_full_name,
  lr.org_id,
  lr.leave_type_id,
  lt.name        AS leave_type_name,
  lt.label       AS leave_type_label,
  lr.start_date,
  lr.end_date,
  lr.start_half,
  lr.end_half,
  lr.days_count
FROM hr.leave_requests lr
JOIN iam.users               u   ON u.id   = lr.user_id
-- Catalog joins are qualified on tenant_id: these views are read under
-- BYPASSRLS service roles too, where RLS does not filter for us.
JOIN entity.organizations    o   ON o.id  = lr.org_id
JOIN hr.leave_types          lt  ON lt.id  = lr.leave_type_id AND lt.tenant_id  = o.tenant_id
JOIN hr.leave_request_statuses lrs ON lrs.id = lr.status_id   AND lrs.tenant_id = o.tenant_id
WHERE lrs.name = 'approved'
  AND NOT lr.is_deleted;


-- ===================================================================
-- 8. Views (security_invoker — underlying-table RLS applies to the caller)
-- ===================================================================

-- Per (user, org, month) status counts, late count, avg worked_minutes.
-- Payroll-export source. Month is the org-local YYYY-MM of work_date.
CREATE OR REPLACE VIEW hr.vw_attendance_monthly_summary WITH (security_invoker = true) AS
SELECT
  ad.org_id,
  ad.user_id,
  u.full_name                                            AS user_full_name,
  u.email                                                AS user_email,
  to_char(ad.work_date, 'YYYY-MM')                       AS month,
  COUNT(*) FILTER (WHERE st.name = 'present')            AS present_count,
  COUNT(*) FILTER (WHERE st.name = 'absent')             AS absent_count,
  COUNT(*) FILTER (WHERE st.name = 'half_day')           AS half_day_count,
  COUNT(*) FILTER (WHERE st.name = 'on_leave')           AS on_leave_count,
  COUNT(*) FILTER (WHERE st.name = 'holiday')            AS holiday_count,
  COUNT(*) FILTER (WHERE st.name = 'weekly_off')         AS weekly_off_count,
  COUNT(*) FILTER (WHERE st.name = 'wfh')                AS wfh_count,
  COUNT(*) FILTER (WHERE ad.is_late)                     AS late_count,
  COUNT(*) FILTER (WHERE ad.is_early_exit)               AS early_exit_count,
  AVG(ad.worked_minutes)::numeric(10,2)                  AS avg_worked_minutes
FROM hr.attendance_days ad
JOIN iam.users               u  ON u.id  = ad.user_id
-- Catalog joins are qualified on tenant_id: these views are read under
-- BYPASSRLS service roles too, where RLS does not filter for us.
JOIN entity.organizations    o  ON o.id  = ad.org_id
JOIN hr.attendance_statuses  st ON st.id = ad.status_id AND st.tenant_id = o.tenant_id
GROUP BY ad.org_id, ad.user_id, u.full_name, u.email, to_char(ad.work_date, 'YYYY-MM');

-- Today's org attendance: active employees LEFT JOINed to their attendance_days
-- row for CURRENT_DATE; unmatched employees surface as 'not_marked'. Used by the
-- org dashboard; the /team endpoint queries a parameterized date in the repo for
-- arbitrary days.
CREATE OR REPLACE VIEW hr.vw_org_attendance_today WITH (security_invoker = true) AS
SELECT
  ep.org_id,
  ep.user_id,
  u.full_name                          AS user_full_name,
  u.email                              AS user_email,
  ad.work_date,
  ad.first_in,
  ad.last_out,
  ad.worked_minutes,
  COALESCE(st.name,  'not_marked')     AS status_name,
  COALESCE(st.label, 'Not Marked')     AS status_label,
  COALESCE(ad.is_late, FALSE)          AS is_late,
  COALESCE(ad.is_early_exit, FALSE)    AS is_early_exit
FROM hr.employee_profiles ep
JOIN iam.users u ON u.id = ep.user_id
LEFT JOIN hr.attendance_days ad
       ON ad.user_id = ep.user_id AND ad.work_date = CURRENT_DATE
LEFT JOIN hr.attendance_statuses st ON st.id = ad.status_id AND st.tenant_id = ep.tenant_id
WHERE ep.is_active AND NOT ep.is_deleted;


-- ===================================================================
-- 6. Views (security_invoker — underlying-table RLS applies to the caller)
--    These resolve lookup labels + user names for the list/detail read paths.
--    Visibility narrowing (own/team/private) still happens in the repository;
--    the views are org-scoped projections, not access-control boundaries.
-- ===================================================================

-- Enriched task projection: lookup labels, list name/visibility, assignee &
-- creator names. Reused by the list/detail endpoints.
CREATE OR REPLACE VIEW task.vw_tasks_enriched WITH (security_invoker = true) AS
SELECT
  t.id,
  t.org_id,
  t.list_id,
  tl.name        AS list_name,
  tl.visibility  AS list_visibility,
  tl.owner_id    AS list_owner_id,
  t.title,
  t.description,
  t.assignee_id,
  ua.full_name   AS assignee_name,
  ua.email       AS assignee_email,
  t.created_by,
  uc.full_name   AS created_by_name,
  t.due_at,
  t.priority_id,
  tp.name        AS priority_name,
  tp.label       AS priority_label,
  tp.sort_order  AS priority_sort_order,
  t.status_id,
  ts.name        AS status_name,
  ts.label       AS status_label,
  ts.is_terminal AS status_is_terminal,
  t.parent_task_id,
  t.related_entity_type,
  t.related_entity_id,
  t.tags,
  t.completed_at,
  t.recurrence_rule,
  t.created_at,
  t.updated_at
FROM task.tasks t
LEFT JOIN task.task_lists      tl ON tl.id = t.list_id
-- Catalog joins are qualified on tenant_id: these views are read under
-- BYPASSRLS service roles too, where RLS does not filter for us.
JOIN      entity.organizations o  ON o.id  = t.org_id
LEFT JOIN task.task_priorities tp ON tp.id = t.priority_id AND tp.tenant_id = o.tenant_id
JOIN      task.task_statuses   ts ON ts.id = t.status_id   AND ts.tenant_id = o.tenant_id
LEFT JOIN iam.users            ua ON ua.id = t.assignee_id
LEFT JOIN iam.users            uc ON uc.id = t.created_by
WHERE NOT t.is_deleted;


-- ===================================================================
-- RESOLVER VIEWS  (vw_ + security_invoker: RLS on member_roles applies
-- through the view for the calling role). Resolve role -> name/label/rank.
-- ===================================================================

CREATE OR REPLACE VIEW lms.vw_member_roles WITH (security_invoker = true) AS
SELECT
  mr.user_id,
  u.full_name  AS user_name,
  u.email      AS user_email,
  mr.org_id,
  o.name       AS org_name,
  mr.tenant_id,
  mr.role_id,
  r.name       AS role,
  r.label      AS role_label,
  r.rank       AS rank,
  mr.is_active,
  mr.granted_by,
  mr.granted_at,
  mr.updated_at
FROM lms.member_roles mr
JOIN      iam.users            u ON u.id = mr.user_id
JOIN      entity.organizations o ON o.id = mr.org_id
JOIN      lms.roles            r ON r.id = mr.role_id AND r.tenant_id = mr.tenant_id;

CREATE OR REPLACE VIEW hr.vw_member_roles WITH (security_invoker = true) AS
SELECT
  mr.user_id,
  u.full_name  AS user_name,
  u.email      AS user_email,
  mr.org_id,
  o.name       AS org_name,
  mr.tenant_id,
  mr.role_id,
  r.name       AS role,
  r.label      AS role_label,
  r.rank       AS rank,
  mr.is_active,
  mr.granted_by,
  mr.granted_at,
  mr.updated_at
FROM hr.member_roles mr
JOIN      iam.users            u ON u.id = mr.user_id
JOIN      entity.organizations o ON o.id = mr.org_id
JOIN      hr.roles             r ON r.id = mr.role_id AND r.tenant_id = mr.tenant_id;

CREATE OR REPLACE VIEW task.vw_member_roles WITH (security_invoker = true) AS
SELECT
  mr.user_id,
  u.full_name  AS user_name,
  u.email      AS user_email,
  mr.org_id,
  o.name       AS org_name,
  mr.tenant_id,
  mr.role_id,
  r.name       AS role,
  r.label      AS role_label,
  r.rank       AS rank,
  mr.is_active,
  mr.granted_by,
  mr.granted_at,
  mr.updated_at
FROM task.member_roles mr
JOIN      iam.users            u ON u.id = mr.user_id
JOIN      entity.organizations o ON o.id = mr.org_id
JOIN      task.roles           r ON r.id = mr.role_id AND r.tenant_id = mr.tenant_id;

COMMIT;
