-- ===================================================================
-- 07_grants.sql
--
-- All privileges: schema USAGE, table/function grants, and
-- ALTER DEFAULT PRIVILEGES. Every object it names exists by now.
--
-- Generated by the db_scripts consolidation. Fresh-install only:
-- there is no in-place upgrade path, no ALTER-after-the-fact section,
-- and no _migrations/ folder. Schema changes are made in the
-- CREATE statement itself and the database is rebuilt.
-- ===================================================================

BEGIN;

GRANT SELECT, INSERT, UPDATE ON lms.lead_links TO app_user;
GRANT SELECT, INSERT, UPDATE ON lms.lead_links TO tenant_admin;
GRANT ALL PRIVILEGES          ON lms.lead_links TO root_service;

-- Read-only for app sessions: rows are only ever written by the cron job as
-- root_service (withServiceTx). app_user/tenant_admin access is for a future
-- in-app history view, not required by the public report page itself, which
-- reads via root_service like the job does.
GRANT SELECT        ON lms.lead_report_snapshot TO app_user;
GRANT SELECT        ON lms.lead_report_snapshot TO tenant_admin;
GRANT ALL PRIVILEGES ON lms.lead_report_snapshot TO root_service;

GRANT SELECT, INSERT, UPDATE ON iam.api_clients TO tenant_admin;
GRANT SELECT, INSERT, UPDATE ON iam.api_clients TO app_user;
GRANT ALL PRIVILEGES          ON iam.api_clients TO root_service;

GRANT SELECT, INSERT, UPDATE, DELETE ON iam.api_client_orgs TO tenant_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON iam.api_client_orgs TO app_user;
GRANT ALL PRIVILEGES                 ON iam.api_client_orgs TO root_service;

GRANT EXECUTE ON FUNCTION audit.fn_detect_password_spray(INT, INT) TO root_service;
GRANT SELECT ON audit.vw_password_spray_alerts TO root_service;

GRANT SELECT ON TABLE comms.message_templates TO app_user, tenant_admin;
REVOKE INSERT, UPDATE, DELETE ON TABLE comms.message_templates FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES ON TABLE comms.message_templates TO root_service;

-- ── notify.push_subscriptions ─────────────────────────────────────
-- notifications-service reads and writes this table through root_service
-- (DATABASE_URL_SERVICE / withServiceTx), which bypasses RLS: it fans out to
-- every device of a target user without an app session to scope it. It needs
-- the full four -- INSERT on subscribe, DELETE on unsubscribe and on
-- 404/410-pruning, UPDATE for last_used_at, SELECT to find the endpoints.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notify.push_subscriptions TO root_service;

-- The same four for the app-session roles, so the subscribe/unsubscribe route
-- can also run under withRoleTx. RLS -- not the grant -- is what confines those
-- sessions to the acting user's own registrations; see 08_rls.sql.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notify.push_subscriptions TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notify.push_subscriptions TO tenant_admin;

-- Vector similarity stub — uncomment after pgvector confirmed and embedding column added
-- CREATE INDEX IF NOT EXISTS idx_marketing_leads_embedding_ivfflat
--   ON lms.marketing_leads USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- ===================================================================
-- GRANTS
-- ===================================================================

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE ALL    ON SCHEMA public FROM PUBLIC;
GRANT  USAGE  ON SCHEMA public TO PUBLIC;
GRANT  USAGE  ON SCHEMA public    TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA geo       TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA entity    TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA iam       TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA lms       TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA marketing TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA audit     TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA ext       TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA comms     TO app_user, tenant_admin, root_service;
GRANT  USAGE  ON SCHEMA notify    TO app_user, tenant_admin, root_service;

-- app_user: DML on operational tables; SELECT-only on audit + lookups
GRANT SELECT, INSERT, UPDATE ON TABLE
  iam.users, marketing.ad_campaigns, lms.marketing_leads, lms.lead_interactions, lms.lead_follow_ups TO app_user;
REVOKE DELETE ON TABLE
  iam.users, marketing.ad_campaigns, lms.marketing_leads, lms.lead_interactions, lms.lead_follow_ups FROM app_user;

GRANT SELECT ON TABLE
  iam.user_roles, lms.lead_stage, lms.lead_stage_outcome, lms.interaction_types, lms.follow_up_statuses,
  marketing.marketing_platforms, marketing.campaign_statuses, entity.org_types, entity.tenant_domains, entity.tenant_plan_types,
  lms.lead_sources, entity.organizations,
  geo.countries, geo.states, geo.cities
TO app_user;

GRANT SELECT ON TABLE lms.lead_assignment_log, lms.lead_status_log, audit.marketing_leads_history, audit.audit_log TO app_user;
REVOKE INSERT, UPDATE, DELETE ON TABLE lms.lead_assignment_log, lms.lead_status_log, audit.marketing_leads_history, audit.audit_log FROM app_user;

GRANT SELECT ON TABLE
  lms.vw_dashboard_leads, iam.vw_user_org_chart, iam.vw_user_team_members,
  lms.vw_lead_followup_timeline, lms.vw_lead_assignment_timeline,
  lms.vw_sales_follow_up_pipeline, lms.vw_followup_pipeline_enriched,
  lms.vw_org_performance_snapshot,
  lms.vw_lead_report_branch, lms.vw_lead_report_user,
  iam.vw_user_org_access, marketing.vw_campaign_lookup, lms.vw_rep_performance
TO app_user;

GRANT EXECUTE ON FUNCTION iam.can_assign_to(UUID,UUID,UUID) TO app_user;

-- ── iam.reporting_lines (the platform hierarchy) ──────────────────
-- Reads are open to every subject role (RLS narrows them to the current org).
-- Writes are org_admin+/tenant_admin acts, gated by RLS rather than by GRANT,
-- so identity-service can re-org on the user's behalf under their own identity.
GRANT SELECT, INSERT, UPDATE ON iam.reporting_lines TO app_user;
REVOKE DELETE                ON iam.reporting_lines FROM app_user;
GRANT SELECT, INSERT, UPDATE ON iam.reporting_lines TO tenant_admin;
REVOKE DELETE                ON iam.reporting_lines FROM tenant_admin;
GRANT ALL PRIVILEGES         ON iam.reporting_lines TO root_service;

-- The three hierarchy functions are the single authority primitive for all
-- three products, so every login that answers "is X under me?" can call them.
GRANT EXECUTE ON FUNCTION iam.fn_is_in_subtree(UUID,UUID,DATE)  TO app_user, tenant_admin;
GRANT EXECUTE ON FUNCTION iam.fn_subtree_members(UUID,DATE)     TO app_user, tenant_admin;
GRANT EXECUTE ON FUNCTION iam.fn_manager_chain(UUID,DATE)       TO app_user, tenant_admin;

-- tenant_admin: cross-org DML
GRANT SELECT, INSERT, UPDATE ON TABLE
  iam.users, marketing.ad_campaigns, lms.marketing_leads, lms.lead_interactions, lms.lead_follow_ups TO tenant_admin;
REVOKE DELETE ON TABLE
  iam.users, marketing.ad_campaigns, lms.marketing_leads, lms.lead_interactions, lms.lead_follow_ups FROM tenant_admin;

GRANT SELECT ON TABLE
  entity.organizations, lms.lead_assignment_log, lms.lead_status_log, audit.marketing_leads_history TO tenant_admin;

-- entity.tenants: REQUIRED, and safe because RLS is the boundary here.
-- lms.vw_tenant_full_dashboard and iam.vw_user_org_access both join it and are
-- granted to tenant_admin below, but every view is `security_invoker = true`
-- (so RLS evaluates as the querying user), which means the CALLER needs this
-- grant. Without it both views were unreadable by the very role they are
-- granted to, and /analytics/dashboard 500'd with "permission denied for table
-- tenants" for every tenant_admin/super_admin caller.
--
-- This does NOT widen tenant visibility: entity.tenants has RLS ENABLED and
-- FORCED, and `tenant_admin_self_policy` names tenant_admin and tenant_dash_svc
-- explicitly (naming the service login matters -- both roles are NOINHERIT)
-- restricting rows to `id = app.current_tenant_id`. Verified: as tenant_admin
-- with the GUC set, 1 of 2 tenant rows is visible. SELECT only -- the policy is
-- FOR ALL, but nothing here needs to write the tenant registry.
GRANT SELECT ON TABLE entity.tenants TO tenant_admin;
GRANT SELECT ON TABLE audit.audit_log TO tenant_admin;
REVOKE INSERT, UPDATE, DELETE ON TABLE audit.audit_log FROM tenant_admin;
GRANT SELECT ON TABLE
  iam.user_roles, lms.lead_stage, lms.lead_stage_outcome, lms.interaction_types, lms.follow_up_statuses,
  marketing.marketing_platforms, marketing.campaign_statuses, entity.org_types, entity.tenant_domains, entity.tenant_plan_types,
  lms.lead_sources,
  geo.countries, geo.states, geo.cities
TO tenant_admin;

-- geo.* is a tenant catalog now, and tenant_admin curates it (lookup-admin →
-- admin-service). INSERT/UPDATE only: "delete" is is_active = FALSE, because
-- entity.organizations and lms.marketing_leads reference these rows
-- ON DELETE RESTRICT and a place that has been used must stay resolvable.
GRANT INSERT, UPDATE ON TABLE geo.countries, geo.states, geo.cities TO tenant_admin;
REVOKE DELETE ON TABLE geo.countries, geo.states, geo.cities FROM tenant_admin, app_user;

GRANT SELECT ON TABLE
  lms.vw_dashboard_leads, iam.vw_user_org_chart, iam.vw_user_team_members,
  lms.vw_lead_followup_timeline, lms.vw_lead_assignment_timeline,
  lms.vw_sales_follow_up_pipeline, lms.vw_followup_pipeline_enriched,
  marketing.vw_tenant_campaign_summary, lms.vw_tenant_full_dashboard,
  lms.vw_org_performance_snapshot,
  lms.vw_lead_report_branch, lms.vw_lead_report_user,
  iam.vw_user_org_access, marketing.vw_campaign_lookup, lms.vw_rep_performance
TO tenant_admin;

GRANT EXECUTE ON FUNCTION iam.can_assign_to(UUID,UUID,UUID) TO tenant_admin;

-- root_service: unrestricted across all schemas
DO $$
DECLARE s TEXT;
BEGIN
  FOREACH s IN ARRAY ARRAY['public','geo','entity','iam','lms','marketing','audit','ext','comms'] LOOP
    EXECUTE format('GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA %I TO root_service', s);
    EXECUTE format('GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA %I TO root_service', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT ALL PRIVILEGES ON TABLES    TO root_service', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT ALL PRIVILEGES ON SEQUENCES TO root_service', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON TABLES TO app_user', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON TABLES TO tenant_admin', s);
  END LOOP;
END; $$;
GRANT app_user TO lead_svc;
GRANT app_user TO campaign_svc;
GRANT app_user TO user_mgmt_svc;
GRANT app_user TO notif_svc;
GRANT app_user TO intake_svc;
GRANT tenant_admin TO tenant_dash_svc;
DO $$
DECLARE s TEXT;
BEGIN
  FOREACH s IN ARRAY ARRAY['public','geo','entity','iam','lms','marketing','audit','ext','comms'] LOOP
    EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA %I TO analytics_svc', s);
    EXECUTE format('REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I FROM analytics_svc', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON TABLES TO analytics_svc', s);
  END LOOP;
END; $$;

-- Schema USAGE for all service roles
DO $$
DECLARE s TEXT;
BEGIN
  FOREACH s IN ARRAY ARRAY['public','geo','entity','iam','lms','marketing','audit','ext','comms','notify'] LOOP
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO lead_svc, campaign_svc, user_mgmt_svc, notif_svc, intake_svc, tenant_dash_svc, analytics_svc', s);
  END LOOP;
END; $$;

GRANT EXECUTE ON FUNCTION iam.fn_actor_can_act_in_org(UUID, UUID) TO app_user, tenant_admin;

-- ── GRANTS: iam.user_org_mapping ──────────────────────────────────────
GRANT SELECT, INSERT, UPDATE ON TABLE iam.user_org_mapping TO app_user;
REVOKE DELETE ON TABLE iam.user_org_mapping FROM app_user;

GRANT SELECT, INSERT, UPDATE ON TABLE iam.user_org_mapping TO tenant_admin;
REVOKE DELETE ON TABLE iam.user_org_mapping FROM tenant_admin;

GRANT ALL PRIVILEGES ON TABLE iam.user_org_mapping TO root_service;

-- ── GRANTS: lms.lead_assignment_weights ───────────────────────────────
-- Mirrors iam.user_org_mapping above, because it is written by the same
-- identity-service code paths (user create/edit carry the weights in the same
-- payload as the branch/role assignments) under the same roles. Those paths are
-- split across both transaction wrappers -- createUser/updateUser/
-- updateAssignmentWeights run under withRoleTx as app_user or tenant_admin,
-- while reconcileOrgAssignments/addOrgMapping/moveUserBranch run under
-- withServiceTx as root_service -- so all three roles need the grant or half
-- the write paths break.
GRANT SELECT, INSERT, UPDATE ON TABLE lms.lead_assignment_weights TO app_user;
REVOKE DELETE ON TABLE lms.lead_assignment_weights FROM app_user;

GRANT SELECT, INSERT, UPDATE ON TABLE lms.lead_assignment_weights TO tenant_admin;
REVOKE DELETE ON TABLE lms.lead_assignment_weights FROM tenant_admin;

GRANT ALL PRIVILEGES ON TABLE lms.lead_assignment_weights TO root_service;

GRANT SELECT ON TABLE lms.vw_lead_assignment_weights TO app_user, tenant_admin;

-- tenant_admin can also manage entity.organizations
GRANT INSERT, UPDATE ON TABLE entity.organizations TO tenant_admin;

GRANT EXECUTE ON FUNCTION iam.fn_user_active_orgs(UUID)  TO app_user, tenant_admin;
GRANT EXECUTE ON FUNCTION iam.fn_org_active_users(UUID)  TO app_user, tenant_admin;
-- Read by the RLS policies on lms.lead_assignment_weights (08_rls.sql), so
-- every role that touches that table has to be able to call it.
GRANT EXECUTE ON FUNCTION iam.fn_mapping_org(UUID)       TO app_user, tenant_admin;
GRANT EXECUTE ON FUNCTION entity.fn_org_tenant(UUID)     TO app_user, tenant_admin;
GRANT EXECUTE ON FUNCTION iam.fn_user_org_rank(UUID,UUID) TO app_user, tenant_admin;
-- Replaces the bare fn_user_org_rank >= 980 term in the iam.user_org_mapping,
-- iam.users and iam.reporting_lines WRITE policies. SECURITY DEFINER, so its
-- own calls to fn_user_org_role / fn_role_capability_matrix run as the owner
-- and need no further grant here.
GRANT EXECUTE ON FUNCTION iam.fn_user_can_manage_users(UUID,UUID) TO app_user, tenant_admin;
-- Product-service logins are created later (lead_svc below, hr/task in 03,
-- lms_svc in 04), so their EXECUTE grant lives further down this file
-- alongside iam.fn_role_capability_matrix's.
GRANT EXECUTE ON FUNCTION iam.fn_user_org_role(UUID,UUID) TO app_user, tenant_admin;
-- Product-service logins are created later, so their EXECUTE grant lives
-- further down this file alongside iam.fn_user_org_role's.
GRANT EXECUTE ON FUNCTION iam.fn_role_capability_matrix(UUID) TO app_user, tenant_admin;

GRANT ALL ON TABLE iam.token_blocklist TO root_service;
REVOKE ALL  ON TABLE iam.token_blocklist FROM app_user, tenant_admin;

REVOKE INSERT, UPDATE, DELETE ON TABLE audit.activities FROM app_user, tenant_admin;
GRANT SELECT ON TABLE audit.activities TO app_user;
GRANT SELECT ON TABLE audit.activities TO tenant_admin;
GRANT ALL    ON TABLE audit.activities TO root_service;

-- ── Grants for Meta tables ────────────────────────────────────────
GRANT SELECT, INSERT, UPDATE ON ext.meta_tenant_config      TO tenant_admin;
GRANT SELECT, INSERT, UPDATE ON ext.meta_page_form_org_map  TO tenant_admin;
-- SELECT/INSERT/UPDATE/DELETE, not the SELECT/INSERT this line used to carry.
-- The N-6 admin path (admin_tenant_config_policy in 08_rls.sql) reaches this
-- table as app_user and offers PATCH and DELETE; a policy that permits a
-- statement the GRANT does not is dead, and the caller gets "permission denied
-- for table meta_page_form_org_map" instead. DELETE is a real delete here: the
-- table has no is_deleted column and no soft_delete_row trigger.
GRANT SELECT, INSERT, UPDATE, DELETE ON ext.meta_page_form_org_map  TO app_user;
GRANT SELECT, INSERT, UPDATE ON ext.meta_forms              TO tenant_admin;
GRANT SELECT                 ON ext.vw_meta_forms           TO tenant_admin;
GRANT SELECT, INSERT, UPDATE ON ext.meta_leads               TO app_user;
GRANT SELECT, INSERT         ON ext.meta_lead_custom_fields   TO app_user;
GRANT SELECT, INSERT         ON ext.meta_capi_outbound_logs   TO app_user;
GRANT SELECT, INSERT         ON ext.meta_lead_addresses       TO app_user;
GRANT SELECT, INSERT         ON ext.meta_lead_professional    TO app_user;
GRANT SELECT, INSERT         ON ext.meta_lead_demographics    TO app_user;
GRANT SELECT                 ON ext.view_meta_leads_complete   TO app_user;
GRANT SELECT                       ON ext.meta_capi_event_types        TO app_user;
GRANT SELECT, INSERT, UPDATE       ON ext.lead_stage_capi_event_map    TO app_user;
GRANT SELECT                       ON ext.vw_meta_capi_event_types     TO app_user;
GRANT SELECT                       ON ext.vw_lead_stage_capi_event_map TO app_user;

GRANT ALL PRIVILEGES ON ext.meta_tenant_config       TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_page_form_org_map   TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_forms               TO root_service;
GRANT SELECT         ON ext.vw_meta_forms            TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_leads               TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_lead_custom_fields  TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_capi_outbound_logs  TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_lead_addresses      TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_lead_professional   TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_lead_demographics   TO root_service;
GRANT SELECT         ON ext.view_meta_leads_complete  TO root_service;
GRANT ALL PRIVILEGES ON ext.meta_capi_event_types     TO root_service;
GRANT ALL PRIVILEGES ON ext.lead_stage_capi_event_map TO root_service;
GRANT SELECT ON ext.vw_meta_capi_event_types     TO root_service;
GRANT SELECT ON ext.vw_lead_stage_capi_event_map TO root_service;
GRANT app_user TO meta_svc;

GRANT USAGE ON SCHEMA public TO meta_svc;
GRANT USAGE ON SCHEMA ext    TO meta_svc;
GRANT USAGE ON SCHEMA lms    TO meta_svc;
GRANT USAGE ON SCHEMA iam    TO meta_svc;
GRANT USAGE ON SCHEMA entity TO meta_svc;
GRANT app_user TO hr_svc;
GRANT app_user TO task_svc;


-- ── Schema USAGE grants ────────────────────────────────────────────
-- New schemas usable by the standard subject roles + service superuser,
-- matching the "GRANT USAGE ON SCHEMA ..." block in 01_init-db.sql.
GRANT USAGE ON SCHEMA hr   TO app_user, tenant_admin, root_service;
GRANT USAGE ON SCHEMA task TO app_user, tenant_admin, root_service;

-- New service roles need USAGE on every schema they touch (they SET ROLE
-- app_user at runtime, but still connect as themselves first).
DO $$
DECLARE s TEXT;
BEGIN
  FOREACH s IN ARRAY ARRAY['public','geo','entity','iam','lms','marketing','audit','ext','hr','task'] LOOP
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO hr_svc, task_svc', s);
  END LOOP;
END; $$;

-- root_service: unrestricted on the two new schemas + default privileges for
-- future tables. app_user / tenant_admin get SELECT-by-default (explicit DML
-- grants are declared per-table below, like every operational table in 01).
DO $$
DECLARE s TEXT;
BEGIN
  FOREACH s IN ARRAY ARRAY['hr','task'] LOOP
    EXECUTE format('GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA %I TO root_service', s);
    EXECUTE format('GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA %I TO root_service', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT ALL PRIVILEGES ON TABLES    TO root_service', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT ALL PRIVILEGES ON SEQUENCES TO root_service', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON TABLES TO app_user', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT ON TABLES TO tenant_admin', s);
  END LOOP;
END; $$;

GRANT SELECT          ON entity.tenant_modules TO app_user;
GRANT SELECT          ON entity.tenant_modules TO tenant_admin;
GRANT ALL PRIVILEGES  ON entity.tenant_modules TO root_service;

-- ── Lookup grants ──────────────────────────────────────────────────
GRANT SELECT         ON hr.employment_types, hr.leave_types, hr.leave_request_statuses, hr.attendance_statuses TO app_user;
GRANT SELECT         ON hr.employment_types, hr.leave_types, hr.leave_request_statuses, hr.attendance_statuses TO tenant_admin;
GRANT ALL PRIVILEGES ON hr.employment_types, hr.leave_types, hr.leave_request_statuses, hr.attendance_statuses TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.designations TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.designations TO tenant_admin;
REVOKE DELETE                ON hr.designations FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.designations TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.employee_profiles TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.employee_profiles TO tenant_admin;
REVOKE DELETE                ON hr.employee_profiles FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.employee_profiles TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.holiday_calendars TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.holiday_calendars TO tenant_admin;
REVOKE DELETE                ON hr.holiday_calendars FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.holiday_calendars TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.holidays TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.holidays TO tenant_admin;
REVOKE DELETE                ON hr.holidays FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.holidays TO root_service;

GRANT SELECT                 ON hr.leave_policies TO app_user;
REVOKE INSERT, UPDATE, DELETE ON hr.leave_policies FROM app_user;
GRANT SELECT, INSERT, UPDATE ON hr.leave_policies TO tenant_admin;
REVOKE DELETE                ON hr.leave_policies FROM tenant_admin;
GRANT ALL PRIVILEGES         ON hr.leave_policies TO root_service;

GRANT SELECT                 ON hr.hr_settings TO app_user;
REVOKE INSERT, UPDATE, DELETE ON hr.hr_settings FROM app_user;
GRANT SELECT, INSERT, UPDATE ON hr.hr_settings TO tenant_admin;
REVOKE DELETE                ON hr.hr_settings FROM tenant_admin;
GRANT ALL PRIVILEGES         ON hr.hr_settings TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.leave_requests TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.leave_requests TO tenant_admin;
REVOKE DELETE                ON hr.leave_requests FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.leave_requests TO root_service;

GRANT SELECT                  ON hr.leave_request_status_log TO app_user;
GRANT SELECT                  ON hr.leave_request_status_log TO tenant_admin;
REVOKE INSERT, UPDATE, DELETE ON hr.leave_request_status_log FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES          ON hr.leave_request_status_log TO root_service;

GRANT SELECT                  ON hr.leave_ledger TO app_user;
GRANT SELECT                  ON hr.leave_ledger TO tenant_admin;
REVOKE INSERT, UPDATE, DELETE ON hr.leave_ledger FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES          ON hr.leave_ledger TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.leave_request_approvals TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.leave_request_approvals TO tenant_admin;
REVOKE DELETE                ON hr.leave_request_approvals FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.leave_request_approvals TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.attendance_regularization_approvals TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.attendance_regularization_approvals TO tenant_admin;
REVOKE DELETE                ON hr.attendance_regularization_approvals FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.attendance_regularization_approvals TO root_service;

GRANT EXECUTE ON FUNCTION hr.can_approve_leave(UUID,UUID,UUID) TO app_user, tenant_admin;

GRANT SELECT ON hr.vw_leave_balances, hr.vw_leave_requests_enriched, hr.vw_team_leave_calendar
  TO app_user, tenant_admin, root_service;

GRANT SELECT, INSERT, UPDATE ON hr.attendance_rules TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.attendance_rules TO tenant_admin;
REVOKE DELETE                ON hr.attendance_rules FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.attendance_rules TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.shifts TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.shifts TO tenant_admin;
REVOKE DELETE                ON hr.shifts FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.shifts TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.shift_segments TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.shift_segments TO tenant_admin;
REVOKE DELETE                ON hr.shift_segments FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.shift_segments TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.shift_assignments TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.shift_assignments TO tenant_admin;
REVOKE DELETE                ON hr.shift_assignments FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.shift_assignments TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.attendance_geo_exceptions TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.attendance_geo_exceptions TO tenant_admin;
REVOKE DELETE                ON hr.attendance_geo_exceptions FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.attendance_geo_exceptions TO root_service;

GRANT SELECT, INSERT          ON hr.attendance_events TO app_user;
GRANT SELECT                  ON hr.attendance_events TO tenant_admin;
REVOKE UPDATE, DELETE         ON hr.attendance_events FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES          ON hr.attendance_events TO root_service;

GRANT SELECT                  ON hr.attendance_days TO app_user;
GRANT SELECT                  ON hr.attendance_days TO tenant_admin;
REVOKE INSERT, UPDATE, DELETE ON hr.attendance_days FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES          ON hr.attendance_days TO root_service;

GRANT SELECT, INSERT, UPDATE ON hr.attendance_regularizations TO app_user;
GRANT SELECT, INSERT, UPDATE ON hr.attendance_regularizations TO tenant_admin;
REVOKE DELETE                ON hr.attendance_regularizations FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON hr.attendance_regularizations TO root_service;

GRANT EXECUTE ON FUNCTION hr.can_approve(UUID,UUID,UUID) TO app_user, tenant_admin;

GRANT SELECT ON hr.vw_attendance_monthly_summary, hr.vw_org_attendance_today
  TO app_user, tenant_admin, root_service;

-- ── Lookup grants ──────────────────────────────────────────────────
GRANT SELECT         ON task.task_statuses, task.task_priorities TO app_user;
GRANT SELECT         ON task.task_statuses, task.task_priorities TO tenant_admin;
GRANT ALL PRIVILEGES ON task.task_statuses, task.task_priorities TO root_service;

GRANT SELECT, INSERT, UPDATE ON task.task_lists TO app_user;
GRANT SELECT, INSERT, UPDATE ON task.task_lists TO tenant_admin;
REVOKE DELETE                ON task.task_lists FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON task.task_lists TO root_service;

GRANT SELECT, INSERT, UPDATE ON task.tasks TO app_user;
GRANT SELECT, INSERT, UPDATE ON task.tasks TO tenant_admin;
REVOKE DELETE                ON task.tasks FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES         ON task.tasks TO root_service;

GRANT SELECT                  ON task.task_status_log TO app_user;
GRANT SELECT                  ON task.task_status_log TO tenant_admin;
REVOKE INSERT, UPDATE, DELETE ON task.task_status_log FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES          ON task.task_status_log TO root_service;

GRANT SELECT, INSERT          ON task.task_comments TO app_user;
GRANT SELECT                  ON task.task_comments TO tenant_admin;
REVOKE UPDATE, DELETE         ON task.task_comments FROM app_user, tenant_admin;
GRANT ALL PRIVILEGES          ON task.task_comments TO root_service;

GRANT SELECT ON task.vw_tasks_enriched TO app_user, tenant_admin, root_service;

-- Grants for lms/hr/task.roles, .member_roles and .vw_member_roles were
-- removed here (schema_version 1.19.0) along with the tables/views.
-- Membership only (NOINHERIT role => no privilege leak) — satisfies every
-- RLS policy scoped "TO app_user" without needing SET ROLE. Mirrors the
-- `GRANT app_user TO hr_svc/task_svc` pattern from 10_init-hr-task-schemas.sql.
-- lms_svc does not use the tenant_admin pool (no DATABASE_URL_TENANT for
-- leads-service/meta-conversion-api), so it is not made a member of
-- tenant_admin — least privilege, nothing to gain from that membership today.
GRANT app_user TO lms_svc;

-- lms_svc write access to the 7 tenant-scoped LMS lookups (historically
-- `GRANT INSERT, UPDATE ON TABLE %s TO lms_svc` inside the per-table RLS loop
-- in 26_tenant-scope-lms-lookups.sql; moved here because lms_svc doesn't
-- exist yet when 02_schema.sql -- where those 7 tables are now created -- runs).
GRANT INSERT, UPDATE ON TABLE
  lms.lead_stage, lms.lead_stage_outcome, lms.interaction_types,
  lms.follow_up_statuses, lms.lead_sources,
  marketing.marketing_platforms, marketing.campaign_statuses
  TO lms_svc;


-- ===================================================================
-- 2. Schema USAGE — narrow every product login down to its own schema(s)
-- + the shared schemas it actually reads. hr_svc/task_svc previously got
-- blanket USAGE on every schema (10_init-hr-task-schemas.sql, run when
-- app_user was the only isolation mechanism); revoke that down now.
-- ===================================================================
REVOKE USAGE ON SCHEMA lms, marketing, ext, audit FROM hr_svc, task_svc;
REVOKE USAGE ON SCHEMA hr, task               FROM lms_svc;

-- comms is shared, not a product schema: every product sends messages, so all
-- three logins read the template catalog. Read-only — the catalog is seeded and
-- administered, never written on the send path.
GRANT USAGE ON SCHEMA public, iam, entity, geo, comms, lms, marketing, ext TO lms_svc;
GRANT USAGE ON SCHEMA public, iam, entity, geo, comms, hr                  TO hr_svc;
GRANT USAGE ON SCHEMA public, iam, entity, geo, comms, task                TO task_svc;


-- ===================================================================
-- 3. Defense-in-depth — explicit REVOKE of all privileges on the OTHER
-- products' schemas. No-op today (nothing was ever GRANTed directly to
-- these roles on the wrong schema — they only ever had access via
-- SET ROLE app_user, which the app layer no longer does for them), but
-- this makes the isolation boundary an explicit, auditable statement
-- rather than an absence.
-- ===================================================================
REVOKE ALL PRIVILEGES ON ALL TABLES    IN SCHEMA hr, task            FROM lms_svc;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr, task            FROM lms_svc;
REVOKE ALL PRIVILEGES ON ALL TABLES    IN SCHEMA lms, marketing, ext FROM hr_svc, task_svc;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA lms, marketing, ext FROM hr_svc, task_svc;
REVOKE ALL PRIVILEGES ON ALL TABLES    IN SCHEMA hr                  FROM task_svc;
REVOKE ALL PRIVILEGES ON ALL TABLES    IN SCHEMA task                FROM hr_svc;


-- ===================================================================
-- 4. Shared schemas — READ-ONLY (D8: "read shared iam/entity/geo").
-- Two exceptions kept at SELECT+INSERT+UPDATE (iam.users,
-- iam.user_org_mapping) because product UIs today manage team-member
-- role assignment directly through these tables under app_user's
-- existing org_admin_manage_policy/org_admin_insert_policy/
-- org_admin_update_policy RLS policies (01_init-db.sql) — restricting
-- to read-only here would break existing "manage team" functionality in
-- every product. P1.3/Tier C settled role assignment onto the single
-- iam.user_roles ladder instead of a per-product table, so this stays.
-- ===================================================================
GRANT SELECT ON ALL TABLES IN SCHEMA geo, entity TO lms_svc, hr_svc, task_svc;
GRANT SELECT ON ALL TABLES IN SCHEMA iam         TO lms_svc, hr_svc, task_svc;
GRANT SELECT ON ALL TABLES IN SCHEMA comms       TO lms_svc, hr_svc, task_svc;
GRANT SELECT, INSERT, UPDATE ON TABLE iam.users, iam.user_org_mapping
  TO lms_svc, hr_svc, task_svc;

-- iam.reporting_lines is a third exception to the read-only rule: hr-service
-- writes it when HR admins re-org. All three logins read it (the blanket iam
-- SELECT above already covers that) because all three resolve authority from it.
-- They connect under RLS, so the org_admin+ write policy still applies.
GRANT SELECT, INSERT, UPDATE ON TABLE iam.reporting_lines TO hr_svc;

GRANT EXECUTE ON FUNCTION iam.fn_is_in_subtree(UUID,UUID,DATE)  TO lms_svc, hr_svc, task_svc;
GRANT EXECUTE ON FUNCTION iam.fn_subtree_members(UUID,DATE)     TO lms_svc, hr_svc, task_svc;
GRANT EXECUTE ON FUNCTION iam.fn_manager_chain(UUID,DATE)       TO lms_svc, hr_svc, task_svc;

ALTER DEFAULT PRIVILEGES IN SCHEMA geo    GRANT SELECT ON TABLES TO lms_svc, hr_svc, task_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA entity GRANT SELECT ON TABLES TO lms_svc, hr_svc, task_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA iam    GRANT SELECT ON TABLES TO lms_svc, hr_svc, task_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA comms  GRANT SELECT ON TABLES TO lms_svc, hr_svc, task_svc;


-- ===================================================================
-- 5. Own-schema DML — mirror exactly what app_user already has on each
-- product's own tables (same tiers as 01_init-db.sql / 10/11/13/14/17),
-- granted directly so it does not depend on SET ROLE app_user.
-- ===================================================================

-- ── lms_svc: lms / marketing / ext ─────────────────────────────────
GRANT SELECT, INSERT, UPDATE ON TABLE
  lms.marketing_leads, lms.lead_interactions, lms.lead_follow_ups, marketing.ad_campaigns
  TO lms_svc;

GRANT SELECT ON TABLE
  lms.lead_stage, lms.lead_stage_outcome, lms.interaction_types, lms.follow_up_statuses,
  lms.lead_sources, marketing.marketing_platforms, marketing.campaign_statuses,
  lms.lead_assignment_log, lms.lead_status_log, audit.marketing_leads_history, audit.audit_log,
  lms.vw_dashboard_leads, lms.vw_lead_followup_timeline, lms.vw_lead_assignment_timeline,
  lms.vw_sales_follow_up_pipeline, lms.vw_followup_pipeline_enriched, lms.vw_org_performance_snapshot,
  lms.vw_rep_performance, lms.vw_lead_report_branch, lms.vw_lead_report_user,
  marketing.vw_campaign_lookup,
  iam.vw_user_org_chart, iam.vw_user_team_members, iam.vw_user_org_access
  TO lms_svc;

GRANT SELECT, INSERT, UPDATE ON TABLE lms.lead_links TO lms_svc;

-- Read-only for lms_svc: leads-service only ever READS weights (the
-- auto-assignment picker); identity-service owns every write. Granted
-- explicitly rather than left to the ALTER DEFAULT PRIVILEGES below, which
-- only covers tables created AFTER this script runs.
GRANT SELECT ON TABLE lms.lead_assignment_weights, lms.vw_lead_assignment_weights TO lms_svc;
GRANT EXECUTE ON FUNCTION iam.fn_mapping_org(UUID) TO lms_svc;

-- meta-conversion-api runs as lms_svc (DB_PRODUCT_SCOPED_LOGIN=true), and
-- lms_svc holds NO privilege on ext.meta_page_form_org_map: the
-- `ALTER DEFAULT PRIVILEGES IN SCHEMA ext` line below only covers tables
-- created AFTER it runs, and this one is created in 02_tables_core.sql. Its
-- page-org-map admin API writes the table directly under
-- withTenantConfigTx, so the grant has to be explicit.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ext.meta_page_form_org_map TO lms_svc;
-- Read-only, for GET /meta/pages resolving the selected tenant's stored Meta
-- credentials and for validating ?tenant_id= against entity.tenants.
GRANT SELECT ON TABLE ext.meta_tenant_config TO lms_svc;
-- Called from ext.meta_page_form_org_map's admin_tenant_config_policy WITH
-- CHECK, which is evaluated as the querying role.
GRANT EXECUTE ON FUNCTION entity.fn_org_tenant(UUID) TO lms_svc;
-- iam.api_clients / iam.api_client_orgs (N-4, moved from ext) are managed
-- exclusively by identity-service; lms_svc's blanket `SELECT ON ALL TABLES IN
-- SCHEMA iam` above already covers any incidental read, no product-specific
-- write grant needed.
GRANT EXECUTE ON FUNCTION iam.can_assign_to(UUID,UUID,UUID) TO lms_svc;

-- ── Campaign types (1.49.0) ─────────────────────────────────────────
-- NAME THE SERVICE LOGINS. `TO app_user` is not enough for any of these: every
-- *_svc login is NOINHERIT, so a privilege held only by app_user is not held by
-- lms_svc or lead_svc at all. (08_rls.sql's widening block fixes the POLICY half
-- of this automatically; there is no equivalent for GRANTs, which is why each
-- one below is spelled out.) Granted explicitly rather than left to the
-- ALTER DEFAULT PRIVILEGES lines below, which only cover tables created AFTER
-- this script runs -- these are created in 02_tables_core.sql.
--
-- WRITE for lms_svc: the campaign-types admin screen (a later phase) is served
-- by a product-scoped login. READ for lead_svc: the intake path only resolves a
-- type, it never edits the catalog.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE marketing.campaign_types TO lms_svc;
GRANT SELECT                         ON TABLE marketing.campaign_types TO lead_svc;
GRANT SELECT                         ON TABLE marketing.campaign_types TO app_user, tenant_admin;
GRANT ALL PRIVILEGES                 ON TABLE marketing.campaign_types TO root_service;

-- ext.meta_campaigns: meta_svc is the WRITER (the campaign fetch and the sync
-- scripts own this cache), lms_svc writes the mapping half from the admin
-- console, lead_svc reads it on the intake path to resolve an inbound lead's
-- campaign to a type.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ext.meta_campaigns TO meta_svc;
-- meta_svc reaches marketing for the FIRST time here. Its schema USAGE list
-- (public/ext/lms/iam/entity, above) predates campaign types, and
-- marketing.fn_match_campaign_type is deliberately NOT security definer -- it
-- reads marketing.campaign_types as the CALLER, so without both of these the
-- sync scripts' every match attempt fails with "permission denied for schema
-- marketing", not a wrong answer. Read-only: the catalog is the console's.
GRANT USAGE  ON SCHEMA marketing                        TO meta_svc;
GRANT SELECT ON TABLE  marketing.campaign_types         TO meta_svc;
GRANT SELECT, INSERT, UPDATE         ON TABLE ext.meta_campaigns TO lms_svc;
GRANT SELECT                         ON TABLE ext.meta_campaigns TO lead_svc;
GRANT SELECT                         ON TABLE ext.meta_campaigns TO app_user, tenant_admin;
GRANT ALL PRIVILEGES                 ON TABLE ext.meta_campaigns TO root_service;

-- Both new functions. fn_user_sees_campaign_type is evaluated inside
-- lms.marketing_leads' RLS USING clause, so EVERY role that reads a lead needs
-- EXECUTE on it or the read fails with a permission error on the policy itself.
GRANT EXECUTE ON FUNCTION marketing.fn_match_campaign_type(UUID, TEXT)
  TO app_user, tenant_admin, root_service, lms_svc, lead_svc, meta_svc;
GRANT EXECUTE ON FUNCTION lms.fn_user_sees_campaign_type(UUID, UUID, UUID)
  TO app_user, tenant_admin, root_service, lms_svc, lead_svc, meta_svc;

-- 1.50.1: the deactivate/delete guard's view into ext.* for leads-service, which
-- has no grant on that schema by design. Service logins named explicitly: GRANTs
-- have no equivalent of 08_rls.sql's policy-widening block.
GRANT EXECUTE ON FUNCTION marketing.fn_campaign_type_usage(UUID)
  TO tenant_admin, root_service, lms_svc, lead_svc;

ALTER DEFAULT PRIVILEGES IN SCHEMA lms       GRANT SELECT, INSERT, UPDATE ON TABLES TO lms_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA marketing GRANT SELECT, INSERT, UPDATE ON TABLES TO lms_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA ext       GRANT SELECT, INSERT, UPDATE ON TABLES TO lms_svc;

-- ── scratch.meta_pull_* — Meta lead pull staging (1.50.0) ───────────
--
-- DELETE IS GRANTED HERE ON PURPOSE, AND IT BREAKS THIS FILE'S CONVENTION.
-- Everywhere else in 07_grants.sql a service login gets SELECT/INSERT/UPDATE
-- and nothing more, because a domain row is soft-deleted (is_deleted = TRUE via
-- the soft_delete_row trigger) and a real DELETE is a bug. These two tables are
-- the exception the `scratch` schema exists to mark: they carry no is_deleted
-- column and no soft-delete trigger, and POST /meta/lead-pull/runs BEGINS by
-- deleting the tenant's previous run so nothing from the last pull survives
-- into the next (the FK cascade takes the staged rows with it). Without DELETE
-- the feature's first statement fails. Do not "restore consistency" by removing
-- it -- read the table comments in 02_tables_core.sql first.
--
-- NAME THE SERVICE LOGINS. `TO app_user` is not enough: every *_svc login is
-- NOINHERIT, so a privilege held only by app_user is not held by lms_svc at
-- all. 08_rls.sql's widening block fixes the POLICY half of this automatically;
-- there is no equivalent for GRANTs.
--
-- lms_svc is the login that actually runs this feature: meta-conversion-api
-- connects as DB_LMS_SVC_USER with DB_PRODUCT_SCOPED_LOGIN=true, so
-- withTenantConfigTx runs AS lms_svc and never does SET ROLE app_user.
-- meta_svc is named alongside it because meta-sync-scripts shares this data.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE scratch.meta_pull_runs,  scratch.meta_pull_leads TO lms_svc;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE scratch.meta_pull_runs,  scratch.meta_pull_leads TO meta_svc;
-- admin_tenant_config_policy below is `TO app_user`, and a policy permitting a
-- statement the GRANT does not is dead. tenant_admin is deliberately NOT
-- granted: this is a platform super_admin surface reached only through
-- withTenantConfigTx, and there is no tenant_admin policy on either table, so a
-- grant would buy nothing but the impression of access.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE scratch.meta_pull_runs,  scratch.meta_pull_leads TO app_user;
GRANT ALL PRIVILEGES                 ON TABLE scratch.meta_pull_runs,  scratch.meta_pull_leads TO root_service;

-- entity.fn_org_tenant is called from scratch.meta_pull_leads' WITH CHECK, so
-- every role that inserts a staged row needs EXECUTE on it or the write fails
-- with a permission error on the policy itself rather than a policy violation.
GRANT EXECUTE ON FUNCTION entity.fn_org_tenant(UUID)
  TO app_user, tenant_admin, root_service, lms_svc, meta_svc;

-- ── hr_svc: hr ──────────────────────────────────────────────────────
GRANT SELECT         ON TABLE hr.employment_types, hr.leave_types, hr.leave_request_statuses, hr.attendance_statuses TO hr_svc;
-- hr.departments moved to iam.departments (Tier C); hr_svc write grant on it is
-- in db_scripts/06_rls.sql alongside the iam.departments RLS.
GRANT SELECT, INSERT, UPDATE ON TABLE hr.designations, hr.employee_profiles TO hr_svc;
GRANT SELECT, INSERT, UPDATE ON TABLE hr.holiday_calendars, hr.holidays TO hr_svc;
GRANT SELECT                 ON TABLE hr.leave_policies, hr.hr_settings TO hr_svc;
GRANT SELECT, INSERT, UPDATE ON TABLE hr.leave_requests, hr.leave_request_approvals,
  hr.attendance_regularization_approvals TO hr_svc;
GRANT SELECT                 ON TABLE hr.leave_request_status_log, hr.leave_ledger TO hr_svc;
-- hr.shift_segments must be named explicitly, exactly like hr.shifts: the
-- ALTER DEFAULT PRIVILEGES below only affects tables created AFTER it runs, and
-- 03_product_schema.sql creates every hr table before this file executes. An
-- existing database can appear to work anyway (the default ACL is already in
-- place from a prior deploy, so a table added later inherits it) while a fresh
-- install ends up with zero hr_svc privilege on the table -- create-shift then
-- fails on the segment INSERT with "permission denied".
GRANT SELECT, INSERT, UPDATE ON TABLE hr.attendance_rules, hr.shifts, hr.shift_segments, hr.shift_assignments, hr.attendance_geo_exceptions, hr.attendance_regularizations TO hr_svc;
GRANT SELECT, INSERT         ON TABLE hr.attendance_events TO hr_svc;
GRANT SELECT                 ON TABLE hr.attendance_days TO hr_svc;
GRANT SELECT ON TABLE
  hr.vw_leave_balances, hr.vw_leave_requests_enriched, hr.vw_team_leave_calendar,
  hr.vw_attendance_monthly_summary, hr.vw_org_attendance_today
  TO hr_svc;

ALTER DEFAULT PRIVILEGES IN SCHEMA hr GRANT SELECT, INSERT, UPDATE ON TABLES TO hr_svc;

-- ── task_svc: task ──────────────────────────────────────────────────
GRANT SELECT                 ON TABLE task.task_statuses, task.task_priorities TO task_svc;
GRANT SELECT, INSERT, UPDATE ON TABLE task.task_lists, task.tasks TO task_svc;
GRANT SELECT                 ON TABLE task.task_status_log TO task_svc;
GRANT SELECT, INSERT         ON TABLE task.task_comments TO task_svc;
GRANT SELECT                 ON TABLE task.vw_tasks_enriched TO task_svc;

ALTER DEFAULT PRIVILEGES IN SCHEMA task GRANT SELECT, INSERT, UPDATE ON TABLES TO task_svc;

-- Tier C: every product service now resolves role/rank/department from the one
-- iam ladder via iam.fn_user_org_role (see 02_schema.sql), so each product login
-- needs EXECUTE on it. Declared here because these logins are created after 02.
GRANT EXECUTE ON FUNCTION iam.fn_user_org_role(UUID, UUID) TO lms_svc, hr_svc, task_svc, lead_svc;

-- Tier C3: same for the capability matrix, which every service loads at startup.
GRANT EXECUTE ON FUNCTION iam.fn_role_capability_matrix(UUID) TO lms_svc, hr_svc, task_svc, lead_svc;

-- ===================================================================
-- readonly_user membership for every app-pool login (P0 #1 defense-in-depth)
--
-- withRoleTx does `SET LOCAL ROLE readonly_user` for read_only actors. A login
-- may only SET ROLE to a role it is a member of, so grant readonly_user to every
-- login that can currently become app_user. Done dynamically so future *_svc
-- logins are covered without editing this list. readonly_user is itself a member
-- of app_user (see 01) and is excluded.
-- ===================================================================
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT m.rolname
    FROM pg_auth_members am
    JOIN pg_roles m ON m.oid = am.member
    JOIN pg_roles g ON g.oid = am.roleid
    WHERE g.rolname = 'app_user' AND m.rolname <> 'readonly_user'
  LOOP
    EXECUTE format('GRANT readonly_user TO %I', r.rolname);
  END LOOP;
END $$;


-- ═══════════════════════════════════════════════════════════════════
-- 4. GRANTs
--    Registry tables are global reference data (no tenant_id, no RLS):
--    readable by subject roles for a future "preview defaults" UI, written
--    only by root_service. tenant_catalog_versions is SELECT-only for
--    subject roles; root_service (the seeder) writes it.
-- ═══════════════════════════════════════════════════════════════════
GRANT SELECT         ON entity.catalog_defaults, entity.catalog_versions TO app_user;
GRANT SELECT         ON entity.catalog_defaults, entity.catalog_versions TO tenant_admin;
GRANT ALL PRIVILEGES ON entity.catalog_defaults, entity.catalog_versions TO root_service;

GRANT SELECT         ON entity.tenant_catalog_versions TO app_user;
GRANT SELECT         ON entity.tenant_catalog_versions TO tenant_admin;
GRANT ALL PRIVILEGES ON entity.tenant_catalog_versions TO root_service;


-- ═══════════════════════════════════════════════════════════════════
-- 8. Function privileges — these functions cross tenant boundaries and
--    must only run as the BYPASSRLS service account (called from
--    @crm/db's withServiceTx at provisioning / from the tenant-scoped
--    reset path). Revoke the default PUBLIC EXECUTE so a subject role
--    (app_user / tenant_admin) can never invoke cross-tenant seeding.
-- ═══════════════════════════════════════════════════════════════════
REVOKE ALL ON FUNCTION entity._apply_catalog_rows(UUID, TEXT, INT, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION entity.seed_tenant_defaults(UUID)                     FROM PUBLIC;
REVOKE ALL ON FUNCTION entity.reset_tenant_catalog(UUID, TEXT, INT)          FROM PUBLIC;
GRANT EXECUTE ON FUNCTION entity._apply_catalog_rows(UUID, TEXT, INT, BOOLEAN) TO root_service;
GRANT EXECUTE ON FUNCTION entity.seed_tenant_defaults(UUID)                     TO root_service;
GRANT EXECUTE ON FUNCTION entity.reset_tenant_catalog(UUID, TEXT, INT)          TO root_service;
GRANT INSERT, UPDATE ON TABLE hr.leave_types TO hr_svc;
GRANT INSERT, UPDATE ON TABLE hr.employment_types TO hr_svc;
GRANT INSERT, UPDATE ON TABLE hr.attendance_statuses TO hr_svc;
GRANT INSERT, UPDATE ON TABLE task.task_statuses TO task_svc;
GRANT INSERT, UPDATE ON TABLE task.task_priorities TO task_svc;
GRANT SELECT              ON iam.departments TO app_user, tenant_admin;
GRANT INSERT, UPDATE      ON iam.departments TO app_user, hr_svc;
GRANT SELECT ON iam.capabilities TO app_user, tenant_admin;
GRANT SELECT                        ON iam.role_capabilities TO app_user, tenant_admin;
GRANT INSERT, UPDATE, DELETE        ON iam.role_capabilities TO app_user;
-- ===================================================================
-- ext.*: grants the previous scripts acquired implicitly
--
-- These were inherited from ALTER DEFAULT PRIVILEGES because every ext
-- object happened to be created after the statement that set them. With
-- grants collected here — after all tables exist — default privileges no
-- longer apply retroactively, so the same access is stated directly.
-- ===================================================================
GRANT SELECT ON ext.lead_stage_capi_event_map    TO tenant_admin;
GRANT SELECT ON ext.meta_capi_event_types        TO tenant_admin;
GRANT SELECT ON ext.meta_capi_outbound_logs      TO tenant_admin;
GRANT SELECT ON ext.meta_lead_addresses          TO tenant_admin;
GRANT SELECT ON ext.meta_lead_custom_fields      TO tenant_admin;
GRANT SELECT ON ext.meta_lead_demographics       TO tenant_admin;
GRANT SELECT ON ext.meta_lead_professional       TO tenant_admin;
GRANT SELECT ON ext.meta_leads                   TO tenant_admin;
GRANT SELECT ON ext.view_meta_leads_complete     TO tenant_admin;
GRANT SELECT ON ext.vw_lead_stage_capi_event_map TO tenant_admin;
GRANT SELECT ON ext.vw_meta_capi_event_types     TO tenant_admin;

GRANT SELECT ON ext.meta_forms                   TO app_user;
GRANT SELECT ON ext.meta_tenant_config           TO app_user;
GRANT SELECT ON ext.vw_meta_forms                TO app_user;

COMMIT;
