import { uuid, text, boolean, timestamp, jsonb } from 'drizzle-orm/pg-core';
import { crmSchema } from '../pg-schemas';

export const vwDashboardLeads = crmSchema.view('vw_dashboard_leads', {
  leadId:           uuid('lead_id').notNull(),
  orgId:            uuid('org_id').notNull(),
  orgName:          text('org_name').notNull(),
  firstName:        text('first_name').notNull(),
  middleName:       text('middle_name'),
  lastName:         text('last_name').notNull(),
  fullName:         text('full_name').notNull(),
  phone:            text('phone'),
  email:            text('email'),
  city:             text('city'),
  cityName:         text('city_name'),
  stateName:        text('state_name'),
  countryName:      text('country_name'),
  addressLine1:     text('address_line1'),
  tags:             text('tags').array().notNull(),
  metadata:         jsonb('metadata').notNull(),
  stage:            text('stage'),
  stageLabel:       text('stage_label'),
  followupRequired: boolean('followup_required'),
  isRejected:       boolean('is_rejected'),
  isTerminated:     boolean('is_terminated'),
  outcome:          text('outcome'),
  outcomeLabel:     text('outcome_label'),
  outcomeComment:   text('outcome_comment'),
  stageId:          uuid('stage_id'),
  outcomeId:        uuid('outcome_id'),
  campaignName:     text('campaign_name'),
  platform:         text('platform'),
  source:           text('source'),
  assignedRepName:  text('assigned_rep_name'),
  assignedRepEmail: text('assigned_rep_email'),
  assignedUserId:   uuid('assigned_user_id'),
  campaignId:       uuid('campaign_id'),
  isDeleted:        boolean('is_deleted').notNull(),
  createdAt:        timestamp('created_at', { withTimezone: true }).notNull(),
  updatedAt:        timestamp('updated_at', { withTimezone: true }).notNull(),
}).existing();
