import { uuid, text, bigint, timestamp, jsonb, date } from 'drizzle-orm/pg-core';
import { extSchema } from '../pg-schemas';

export const vwMetaLeadsComplete = extSchema.view('view_meta_leads_complete', {
  id:                 uuid('id').notNull(),
  orgId:              uuid('org_id').notNull(),
  marketingLeadId:    uuid('marketing_lead_id'),
  metaLeadId:         bigint('meta_lead_id', { mode: 'bigint' }).notNull(),
  formId:             bigint('form_id', { mode: 'bigint' }).notNull(),
  metaCampaignId:     bigint('meta_campaign_id', { mode: 'bigint' }),
  adsetId:            bigint('adset_id', { mode: 'bigint' }),
  adId:               bigint('ad_id', { mode: 'bigint' }),
  platform:           text('platform'),
  metaCreatedAt:      timestamp('meta_created_at', { withTimezone: true }).notNull(),
  metaFullName:       text('meta_full_name'),
  metaEmail:          text('meta_email'),
  metaPhone:          text('meta_phone'),
  whatsappNumber:     text('whatsapp_number'),
  rawFieldData:        jsonb('raw_field_data'),
  firstName:          text('first_name'),
  lastName:           text('last_name'),
  crmPhone:           text('crm_phone'),
  crmEmail:           text('crm_email'),
  stageId:            uuid('stage_id'),
  outcomeId:          uuid('outcome_id'),
  assignedUserId:     uuid('assigned_user_id'),
  crmCampaignId:      uuid('crm_campaign_id'),
  crmCreatedAt:       timestamp('crm_created_at', { withTimezone: true }),
  streetAddress:      text('street_address'),
  city:               text('city'),
  state:              text('state'),
  province:           text('province'),
  country:            text('country'),
  postalCode:         text('postal_code'),
  zipCode:            text('zip_code'),
  jobTitle:           text('job_title'),
  companyName:        text('company_name'),
  workEmail:          text('work_email'),
  workPhoneNumber:    text('work_phone_number'),
  dateOfBirth:        date('date_of_birth'),
  gender:             text('gender'),
  maritalStatus:      text('marital_status'),
  relationshipStatus: text('relationship_status'),
  militaryStatus:     text('military_status'),
}).existing();
